<?php

function gridstack_menu() {
  $items = [];


  $items['update_user_gridstack_data'] = array(
    'page callback' => 'update_user_gridstack_data',
    'access callback' => TRUE,
  );
  return $items;
}


function gridstack_page_build(&$page) {
  // Check if gridstack class is in markup
  if (isset($page['content']['system_main']['main']['#markup'])) {
    if (stripos($page['content']['system_main']['main']['#markup'], 'grid-stack')) {
      drupal_add_js(['gridstack_user_settings' => load_user_gridstack_data()], 'setting');
      drupal_add_css(drupal_get_path('module', 'gridstack') . '/stylesheets/gridstack.css', ['preprocess' => true, 'group' => CSS_DEFAULT]);
      drupal_add_js(libraries_get_path('lodash') . '/lodash.min.js', ['scope' => 'footer', 'preprocess' => true, 'group' => JS_LIBRARY, 'type' => 'file', 'cache' => true, 'requires_jquery' => true]);
      drupal_add_js(drupal_get_path('module', 'gridstack') . '/js/gridstack.js', ['scope' => 'footer', 'preprocess' => true, 'group' => JS_LIBRARY, 'type' => 'file', 'cache' => true, 'requires_jquery' => true]);
      drupal_add_js(drupal_get_path('module', 'gridstack') . '/js/eportal_grid_engine.js', ['scope' => 'footer', 'preprocess' => true, 'group' => JS_LIBRARY, 'type' => 'file', 'cache' => true, 'requires_jquery' => true]);
    }
  }
}


function load_user_gridstack_data() {
  // Format of gridstack data     {x: 2, y: 5, width: 1, height: 1}
  $return_array = array();
  global $user;
  $user_data = user_load($user->uid);
  if (isset($user_data->field_gridstack_settings[LANGUAGE_NONE][0])) {
    foreach ($user_data->field_gridstack_settings[LANGUAGE_NONE] as $key => $value) {
      $pane_id = $value["field_pane_id"][LANGUAGE_NONE][0]["safe_value"];
      $x_coordinate = intval($value["field_x_coordinate"][LANGUAGE_NONE][0]["value"]);
      $y_coordinate = intval($value["field_y_coordinate"][LANGUAGE_NONE][0]["value"]);
      $return_array[] = array(
        'x' => $x_coordinate,
        'y' => $y_coordinate,
        'width' => 5,
        'height' => 1,
        'id' => $pane_id
      );
    }
  }
  return $return_array;
}


/**
 * Accepts POST data to update users gridstack settings
 *Accessed by ajax request
 */
function update_user_gridstack_data() {
  global $user;
  $user_data = user_load($user->uid);
  if (isset($_POST['grid_data'])) {
    $user_grid_data = $user_data->field_gridstack_settings;
    unset($user_grid_data);
    foreach ($_POST['grid_data'] as $index => $obj) {
      $pane_id = $obj['id'];
      $x_coor = $obj['x'];
      $y_coor = $obj['y'];
      $width = $obj['width'];
      $height = $obj['width'];

      $multifield_gridstack_obj = array(
        'field_pane_id_value' => $pane_id,
        'field_pane_id_value_format' => NULL,
        'field_x_coordinate_value' => $x_coor,
        'field_x_coordinate_value_format' => NULL,
        'field_y_coordinate_value' => $y_coor,
        'field_y_coordinate_value_format' => NULL,
        'field_pane_id' => array(
          LANGUAGE_NONE => array(
            0 => array(
              'value' => $pane_id
            ),
          ),
        ),
        'field_x_coordinate' => array(
          LANGUAGE_NONE => array(
            0 => array(
              'value' => $x_coor
            ),
          ),
        ),
        'field_y_coordinate' => array(
          LANGUAGE_NONE => array(
            0 => array(
              'value' => $y_coor
            ),
          ),
        ),
        'field_grid_width' => array(
          LANGUAGE_NONE => array(
            0 => array(
              'value' => $width
            ),
          ),
        ),
        'field_grid_height' => array(
          LANGUAGE_NONE => array(
            0 => array(
              'value' => $height
            ),
          ),
        ),
      );
      $user_grid_data[LANGUAGE_NONE][$index] = $multifield_gridstack_obj;
    }
    $edit = array(
      'field_gridstack_settings' => $user_grid_data
    );
    try {
    user_save($user_data, $edit);
    } catch (Exception $e) {
      exit();
    }
  }
}
