<?php
/**
 * Created by PhpStorm.
 * User: smolinsk
 * Date: 10/20/2017
 * Time: 11:19 AM
 */

/**
 * Implements hook_views_api().
 */
function partner_area_views_api() {
  return array(
    'api' => 3.0,
    'path' => drupal_get_path('module', 'partner_area')
  );
}

/**
 * Implements hook_ctools_plugin_api().
 */
function partner_area_ctools_plugin_api($module, $api) {
  if ($module == 'page_manager' && $api == 'pages_default') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_menu().
 */
function partner_area_menu() {
  $items = array();

  $items['partner_area/test'] = array(
    'page callback' => 'partner_area_install',
    'access callback' => TRUE,
    'file' => 'partner_area.admin.inc',
  );

  $items['admin/config/system/partner_area'] = array(
    'title' => 'Partner Settings',
    'description' => 'Description of your On this date settings page',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('partner_area_admin_form'),
    'access arguments' => array('administer partner_area settings'),
    'file' => 'partner_area.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_preprocess().
 */
function partner_area_preprocess(&$variables, $hook) {
  // Adding critical CSS
  if($hook == 'page'){
    drupal_add_css(drupal_get_path('module', 'partner_area') .'/css/partner_area.css', [
      'preprocess' => TRUE,
      'group' => CSS_THEME
    ]);
  }
}

