<?php

/**
 * UPDATES
 */
function recommended_resources_update_7101() {
  global $base_url;
  $view = views_get_view('lgc_resources', TRUE);
  // Set default
  $view->display['default']->display_options['query']['options']['json_file'] = $base_url . '/rcs_lgc_resources_json_all';
  // Override User
  $view->display['rcs_resources_user']->display_options['query']['options']['json_file'] = $base_url . '/rcs_lgc_resources_json_by_user';
  views_save_view($view);
}