/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

//>>built
define("dojo/cldr/nls/lt/chinese",{"dateFormatItem-Ehm":"E h:mm a","field-second-relative+0":"dabar","field-weekday":"Savait\u0117s diena","field-wed-relative+0":"\u0161is tre\u010diadienis","dateFormatItem-GyMMMEd":"E, MMM d, U","dateFormatItem-MMMEd":"E, MMM d","field-wed-relative+1":"kitas tre\u010diadienis","field-tue-relative+-1":"paskutinis antradienis","dateFormat-long":"MMMM d, U","field-fri-relative+-1":"paskutinis penktadienis","field-wed-relative+-1":"paskutinis tre\u010diadienis","months-format-wide":"M\u0117nuo1 M\u0117nuo2 M\u0117nuo3 M\u0117nuo4 M\u0117nuo5 M\u0117nuo6 M\u0117nuo7 M\u0117nuo8 M\u0117nuo9 M\u0117nuo10 M\u0117nuo11 M\u0117nuo12".split(" "),
"dateFormatItem-yyyyQQQ":"QQQ U","dateTimeFormat-medium":"{1}, {0}","dateFormat-full":"EEEE, MMMM d, U","dateFormatItem-yyyyMEd":"E, M/d/y","field-thu-relative+-1":"paskutinis ketvirtadienis","dateFormatItem-Md":"M/d","dateFormatItem-yMd":"M/d/y","field-era":"Era","field-year":"Metai","field-hour":"Valanda","months-format-abbr":"M\u0117n1 M\u0117n2 M\u0117n3 M\u0117n4 M\u0117n5 M\u0117n6 M\u0117n7 M\u0117n8 M\u0117n9 M\u0117n10 M\u0117n11 M\u0117n12".split(" "),"field-sat-relative+0":"\u0161is \u0161e\u0161tadienis",
"field-sat-relative+1":"kitas \u0161e\u0161tadienis","field-day-relative+0":"\u0161iandien","field-day-relative+1":"rytoj","field-thu-relative+0":"\u0161is ketvirtadienis","dateFormatItem-GyMMMd":"MMM d, U","field-thu-relative+1":"kitas ketvirtadienis","dateFormatItem-H":"HH","dateFormatItem-Gy":"U","dateFormatItem-yyyyMMMEd":"E, MMM d, U","dateFormatItem-M":"L","dateFormatItem-yyyyMMM":"MMM U","dateFormatItem-yyyyMMMd":"MMM d, U","field-sun-relative+0":"\u0161is sekmadienis","dateFormatItem-Hm":"HH:mm",
"field-sun-relative+1":"kitas sekmadienis","field-minute":"Minut\u0117","field-dayperiod":"AM/PM","dateFormatItem-d":"d","dateFormatItem-ms":"mm:ss","field-day-relative+-1":"vakar","dateFormatItem-h":"H a","dateTimeFormat-long":"{1} {0}","dateFormatItem-MMMd":"MMM d","dateFormatItem-MEd":"E, M/d","dateTimeFormat-full":"{1} {0}","field-fri-relative+0":"\u0161is penktadienis","field-fri-relative+1":"kitas penktadienis","field-day":"Diena","field-zone":"Laiko juosta","dateFormatItem-y":"U","field-year-relative+-1":"pra\u0117j\u0119 metai",
"field-month-relative+-1":"pra\u0117j\u0119s m\u0117nuo","dateFormatItem-hm":"HH:mm","dateFormatItem-yyyyMd":"M/d/y","field-month":"M\u0117nuo","dateFormatItem-MMM":"LLL","field-tue-relative+0":"\u0161is antradienis","field-tue-relative+1":"kitas antradienis","dateFormatItem-EHm":"E HH:mm","field-mon-relative+0":"\u0161is pirmadienis","field-mon-relative+1":"kitas pirmadienis","dateFormat-short":"M/d/yy","dateFormatItem-EHms":"E HH:mm:ss","dateFormatItem-Ehms":"E h:mm:ss a","field-second":"Sekund\u0117",
"field-sat-relative+-1":"paskutinis \u0161e\u0161tadienis","field-sun-relative+-1":"paskutinis sekmadienis","field-month-relative+0":"\u0161is m\u0117nuo","field-month-relative+1":"kitas m\u0117nuo","dateFormatItem-Ed":"d E","field-week":"Savait\u0117","dateFormat-medium":"MMM d, U","field-year-relative+0":"\u0161ie metai","field-week-relative+-1":"pra\u0117jusi savait\u0117","dateFormatItem-yyyyM":"M/y","field-year-relative+1":"kiti metai","dateFormatItem-yyyyQQQQ":"QQQQ U","dateTimeFormat-short":"{1}, {0}",
"dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-hms":"HH:mm:ss","dateFormatItem-GyMMM":"MMM U","field-mon-relative+-1":"paskutinis pirmadienis","dateFormatItem-yyyy":"U","field-week-relative+0":"\u0161i savait\u0117","field-week-relative+1":"kita savait\u0117"});