/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

//>>built
define("dojo/cldr/nls/lt/generic",{"dateFormatItem-Ehm":"E h:mm a","field-second-relative+0":"dabar","field-weekday":"Savait\u0117s diena","field-wed-relative+0":"\u0161is tre\u010diadienis","dateFormatItem-GyMMMEd":"E, MMM d, y G","dateFormatItem-MMMEd":"E, MMM d","field-wed-relative+1":"kitas tre\u010diadienis","field-tue-relative+-1":"paskutinis antradienis","dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateFormat-long":"MMMM d, y G","field-fri-relative+-1":"paskutinis penktadienis","field-wed-relative+-1":"paskutinis tre\u010diadienis",
"dateFormatItem-yyyyQQQ":"QQQ y G","dateTimeFormat-medium":"{1}, {0}","dateFormat-full":"EEEE, MMMM d, y G","dateFormatItem-yyyyMEd":"E, M/d/y GGGGG","field-thu-relative+-1":"paskutinis ketvirtadienis","dateFormatItem-Md":"M/d","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","field-era":"Era","field-year":"Metai","dateTimeFormats-appendItem-Era":"{0} {1}","field-hour":"Valanda","field-sat-relative+0":"\u0161is \u0161e\u0161tadienis","field-sat-relative+1":"kitas \u0161e\u0161tadienis","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})",
"field-day-relative+0":"\u0161iandien","field-day-relative+1":"rytoj","field-thu-relative+0":"\u0161is ketvirtadienis","dateFormatItem-GyMMMd":"MMM d, y G","field-thu-relative+1":"kitas ketvirtadienis","dateFormatItem-H":"HH","dateFormatItem-Gy":"y G","dateFormatItem-yyyyMMMEd":"E, MMM d, y G","dateFormatItem-M":"L","dateFormatItem-yyyyMMM":"MMM y G","dateFormatItem-yyyyMMMd":"MMM d, y G","field-sun-relative+0":"\u0161is sekmadienis","dateFormatItem-Hm":"HH:mm","field-sun-relative+1":"kitas sekmadienis",
"field-minute":"Minut\u0117","field-dayperiod":"AM/PM","dateFormatItem-d":"d","dateFormatItem-ms":"mm:ss","field-day-relative+-1":"vakar","dateFormatItem-h":"H a","dateTimeFormat-long":"{1} {0}","dateFormatItem-MMMd":"MMM d","dateFormatItem-MEd":"E, M/d","dateTimeFormat-full":"{1} {0}","field-fri-relative+0":"\u0161is penktadienis","field-fri-relative+1":"kitas penktadienis","field-day":"Diena","field-zone":"Laiko juosta","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","dateFormatItem-y":"y G",
"field-year-relative+-1":"pra\u0117j\u0119 metai","field-month-relative+-1":"pra\u0117j\u0119s m\u0117nuo","dateFormatItem-hm":"HH:mm","dateTimeFormats-appendItem-Year":"{0} {1}","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dateFormatItem-yyyyMd":"M/d/y GGGGG","field-month":"M\u0117nuo","dateFormatItem-MMM":"LLL","field-tue-relative+0":"\u0161is antradienis","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","field-tue-relative+1":"kitas antradienis","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})",
"dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormatItem-EHm":"E HH:mm","field-mon-relative+0":"\u0161is pirmadienis","field-mon-relative+1":"kitas pirmadienis","dateFormat-short":"M/d/y GGGGG","dateFormatItem-EHms":"E HH:mm:ss","dateFormatItem-Ehms":"E h:mm:ss a","field-second":"Sekund\u0117","field-sat-relative+-1":"paskutinis \u0161e\u0161tadienis","field-sun-relative+-1":"paskutinis sekmadienis","field-month-relative+0":"\u0161is m\u0117nuo","field-month-relative+1":"kitas m\u0117nuo",
"dateFormatItem-Ed":"d E","dateTimeFormats-appendItem-Timezone":"{0} {1}","field-week":"Savait\u0117","dateFormat-medium":"MMM d, y G","field-year-relative+0":"\u0161ie metai","field-week-relative+-1":"pra\u0117jusi savait\u0117","dateFormatItem-yyyyM":"M/y GGGGG","field-year-relative+1":"kiti metai","dateFormatItem-yyyyQQQQ":"QQQQ y G","dateTimeFormat-short":"{1}, {0}","dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-hms":"HH:mm:ss","dateFormatItem-GyMMM":"MMM y G","field-mon-relative+-1":"paskutinis pirmadienis",
"dateFormatItem-yyyy":"y G","field-week-relative+0":"\u0161i savait\u0117","field-week-relative+1":"kita savait\u0117"});