export default {
  NAMESPACE: 'BeWellInformed/',
  SET_SELECTED_PARTNER: 'SET_SELECTED_PARTNER',
  SET_WATER_ANALYSIS_REQUEST: 'SET_WATER_ANALYSIS_REQUEST',
  UPDATE_PARTNERS: 'UPDATE_PARTNERS',
  UPDATE_PARTNER_RESOURCE: 'UPDATE_PARTNER_RESOURCE',
  UPDATE_PARTNER_XML: 'UPDATE_PARTNER_PARTNER_XML',
  UPDATE_PARTNER_FLOWCHART_XML: 'UPDATE_PARTNER_FLOWCHART_XML',
};
