<?php
/**
 * Implements hook_menu().
 **/

function session_timeout_warning_menu() {
  $items = array();

  $items['timeout-logout'] = array(
    'page callback' => 'timeout_logout',
    'access callback' => TRUE,
  );
  $items['renew-session'] = array(
    'page callback' => 'renew_session',
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Page callback for 'timeout-logout'
 * @see https://api.drupal.org/api/drupal/modules%21user%21user.pages.inc/function/user_logout_current_user/7.x
 */
function timeout_logout() {
  // set session variable, to be picked up by eenterprise_bridge_auth_logout()
  $_SESSION['is_timeout'] = TRUE;
  drupal_goto('user/logout');
}

/**
 * Page callback for 'renew-session'
 */
function renew_session() {
  $_SESSION['promptAt'] = time() + (60 * 15); // 15 minute timeout
  $_SESSION['logoutAt'] = time() + (60 * 20); // 20 minute timeout
  return_cdx_facility_management_token();
}

/**
 * Implements hook_page_build().
 * @see https://api.drupal.org/comment/56528#comment-56528
 * Add client-side business logic, tracking for prompt and logout
 */
function session_timeout_warning_page_build(&$page) {
  global $user;

  // Add javascript variables for tracking session timeout. Do no add for anonymous or admin user
  if (!user_is_anonymous() && !($user->uid === 1)) {
    drupal_add_js(drupal_get_path('module', 'session_timeout_warning') . '/js/script.js');

    if (!isset($_SESSION['promptAt']) || !isset($_SESSION['logoutAt'])) {
      $_SESSION['promptAt'] = time() + (60 * 15); // 15 minute timeout
      $_SESSION['logoutAt'] = time() + (60 * 20); // 20 minute timeout
    }
    drupal_add_js(
      array(
        'promptAt' => $_SESSION['promptAt'],
        'logoutAt' => $_SESSION['logoutAt'],
        'currentUser' => $user->uid,
      ),
      'setting'
    );
  }
}
