<?php
/**
 * Implements hook_menu().
 **/

function session_timeout_warning_menu() {
  $items = array();

  $items['renew-session'] = array(
    'page callback' => 'renew_session',
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Page callback for 'renew-session'
 */
function renew_session() {
  $_SESSION['promptAt'] = time() + (60 * 15); // 15 minute timeout
  $_SESSION['logoutAt'] = time() + (60 * 20); // 20 minute timeout
  return_cdx_facility_management_token();
}

/**
 * Implements hook_page_build().
 * @see https://api.drupal.org/comment/56528#comment-56528
 * Add client-side business logic, tracking for prompt and logout
 */
function session_timeout_warning_page_build(&$page) {
  global $user;

  // Add javascript variables for tracking session timeout
  if (!user_is_anonymous() || $user->id !== 1) {
    drupal_add_js(drupal_get_path('module', 'session_timeout_warning') . '/js/script.js');

    if (!isset($_SESSION['promptAt']) || !isset($_SESSION['logoutAt'])) {
      $_SESSION['promptAt'] = time() + (60 * 15); // 15 minute timeout
      $_SESSION['logoutAt'] = time() + (60 * 20); // 20 minute timeout
    }
    drupal_add_js(
      array(
        'promptAt' => $_SESSION['promptAt'],
        'logoutAt' => $_SESSION['logoutAt'],
        'currentUser' => $user->uid,
      ),
      'setting'
    );
  }
}
