<?php

/**
 * Implements hook_preprocess_HOOK().
 */
function eactivity_dataflow_preprocess_panels_pane(&$variables) {
  // When viewing 'Progress Tracker' or 'To Do' widgets/views, load our javascript
  if ($variables['pane']->subtype == 'views-to_do-block_1' || $variables['pane']->subtype == 'views-progress_tracker-block_1') {
    drupal_add_js(drupal_get_path('module', 'eactivity_dataflow') . '/js/script.js', [
      'scope' => 'footer',
      'preprocess' => TRUE,
      'group' => JS_DEFAULT,
      'type' => 'file',
      'cache' => TRUE,
      'requires_jquery' => TRUE
    ]);
    drupal_add_css(drupal_get_path('module', 'eactivity_dataflow') . '/css/eactivity_dataflow.css', [
      'preprocess' => TRUE,
      'group' => CSS_THEME
    ]);
    drupal_add_js(array('eactivity_dataflow' => array('todo_refresh_count' => $_SESSION['todo_refresh_count'])), 'setting');
  }
}
