<?php

/**
 * Implements hook_preprocess_HOOK().
 */
function eactivity_dataflow_preprocess_panels_pane(&$variables) {
  // When viewing 'Progress Tracker' or 'To Do' widgets/views, load our javascript
  if ($variables['pane']->subtype == 'views-to_do-block_1' || $variables['pane']->subtype == 'views-progress_tracker-block_1') {
    drupal_add_js(drupal_get_path('module', 'eactivity_dataflow') . '/js/script.js');
  }
}
