node_import_export.settings:
  type: config_object
  label: 'Node Import-Export label settings'
  mapping:
    node_import_export_import:
      type: string
      label: 'What to do when importing existing nodes.'
    node_import_export_format:
      type: string
      label: 'Which Format to use while exporting nodes.'
