<?php
/**
 * @file
 * Module file for APIs.
 */


/***
 * TODO
 * - Need to automate grabbing the most current api base path
 *
 *
 */

function eenterprise_api_menu()
{
    $items = array();
    $items['api/1.1/%/%'] = array(
        'page callback' => 'process_request',
        'access callback' => TRUE,
        'page arguments' => array(2, 3),
    );
    return $items;
}


function process_request($resource, $id)
{
    // create new http request with $resource, attaching $id as an argument to work with service_views

//    drupal_add_http_header('Content-Type', 'application/json; utf-8');
//    drupal_add_http_header('Access-Control-Allow-Origin', "*");
//    drupal_add_http_header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE');

    $args = '?args[0]=' . $id;
    $host = $_SERVER['HTTP_HOST'];
    $htt = $_SERVER['HTTPS'];
    if (isset($htt))
        $htt = 'https://';
    else
        $htt = 'http://';
    $request = $htt . $host . "/api/1.1/" . $resource . $args;
    print(drupal_http_request($request)->data);
    exit();
}

/**
 * Implements hook_theme_registry_alter().
 */
function eenterprise_api_theme_registry_alter(&$theme_registry)
{
    // Defined path to the current module.
    $module_path = drupal_get_path('module', 'eenterprise_api');
    // Find all .tpl.php files in this module's folder recursively.
    $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
    // Iterate through all found template file objects.
    foreach ($template_file_objects as $key => $template_file_object) {
        // If the template has not already been overridden by a theme.
        if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
            // Alter the theme path and template elements.
            $theme_registry[$key]['theme path'] = $module_path;
            $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
            $theme_registry[$key]['type'] = 'module';
        }
    }
}


function rest_request()
{
    if (isset($_GET['url'])) {
        $url = urldecode($_GET['url']);
        try {
            $ch = curl_init();
            curl_setopt($ch, CURLOPT_URL, $url);
            curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

            // Set so curl_exec returns the result instead of outputting it.
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            // Get the response and close the channel.
            $response = curl_exec($ch);
            curl_close($ch);
            if (FALSE === $response)
                throw new Exception(curl_error($ch), curl_errno($ch));

            echo json_encode($response);

        } catch (Exception $e) {
            echo json_encode(array("url" => $url, "error" => $e));
        }
    } else {
        echo json_encode(array("error" => "invalid parameters."));
    }


}


function apply_pagination_rules(&$output, &$view, $limit)
{
//    echo '<h1>Output</h1>';
//    dpm($output);
//    echo '<h1>View</h1>';
//    dpm($view);
}

/*
 * METADATA defined here
 *
 * @param array $output
 *   Results of the view execution. These will be sent to services for rendering.
 * @param object $view
 *   Views object.
 */
function eenterprise_api_services_views_execute_view_alter(&$output, $view)
{
    attach_metadata($view, $output);
}

/**
 * @param $view
 * @param $query
 *
 * *** For the query to be overidden, the pagination must be turned off for the service view. "Display all options"
 */
function eenterprise_api_views_query_alter(&$view, &$query)
{
    if ($view->name == 'other_items_of_interest' && $view->current_display == "services_1") {
        if (isset($_GET['limit'])) {
            $limit = $_GET['limit'];
            $query->set_limit($limit);
            if (isset($_GET['page'])) {
                $page = $_GET['page'];
                // Formula for offset from page and items per page
                $offset = ($page - 1) * ($limit + 1);
                $query->set_offset($offset);

            }
        }
    }
}

/**
 * @param $view_name
 * @param $content_type
 * Checks headers for error codes
 * Content type refers to json or xml
 * Includes metadata
 * Checks for Post or Get sorting/paging/limiting arguments
 */
function process_service_view_response($view_name, $content_type, $request_header)
{
    $error_handler = return_error_codes($request_header);
    if ($error_handler->error)
        return $error_handler->error_message;
    else
        return return_service_view_response($view_name, $content_type);
}


/**
 * @param $request_header
 * Reads request header and decides if valid request, returns appropriate http error code
 */
function return_error_codes($request_header)
{

}

function get_content_total($content_type)
{
    $query = "SELECT COUNT(*) amount FROM {node} n " .
        "WHERE n.type = :type";
    $result = db_query($query, array(':type' => $content_type))->fetch();
    return $result->amount;
}

/**
 * @param $view
 * @param $output
 * appends metadata for a view to output
 */
function attach_metadata($view, &$output)
{
    // Get total

    $limit = FALSE;
    $page = FALSE;

    if (isset($_GET['limit']))
        $limit = $_GET['limit'];
    if (isset($_GET['page']))
        $page = $_GET['page'];


    $page_results = count($view->result);

    if ($limit) {
        $items_per_page = $limit;
        $total_results = get_content_total("state_resource");
        if ($page) {
            $current_page = $page;
        }
    } else {
        $items_per_page = count($view->result);
        $current_page = 1;
    }
    $total_pages = $total_results / $items_per_page - 1;
    if ($page ==  1 || !$limit)
        $start = 1;
    else if ($items_per_page == 1)
        $start = $current_page * $items_per_page;
    else
        $start = $current_page * $items_per_page - 1;



    $end = $start + $page_results - 1;
    $paged_output = array(
        'metadata' => array(
            'current_page' => $current_page,
            'total_pages' => ceil($total_pages),
            'items_per_page' => $items_per_page,
            'display_start' => $start,
            'display_end' => $end,
            'total_results' => $total_results),
        'results' => $output,
    );
    $output = $paged_output;
}
