/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

//>>built
define("dojo/cldr/nls/et/generic",{"dateFormatItem-Ehm":"E H:mm","field-second-relative+0":"praegu","field-weekday":"N\u00e4dalap\u00e4ev","field-wed-relative+0":"see kolmap\u00e4ev","dateFormatItem-GyMMMEd":"E, dd.MM.yy G","dateFormatItem-MMMEd":"E, dd.MM","field-wed-relative+1":"j\u00e4rgmine kolmap\u00e4ev","field-tue-relative+-1":"eelmine teisip\u00e4ev","dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateFormat-long":"dd. MMMM yy G","field-fri-relative+-1":"eelmine reede","field-wed-relative+-1":"eelmine kolmap\u00e4ev",
"dateFormatItem-yyyyQQQ":"QQQ y G","dateTimeFormat-medium":"{1}, {0}","dateFormat-full":"EEEE, d, MMMM y G","dateFormatItem-yyyyMEd":"E, dd.MM.yy GGGGG","field-thu-relative+-1":"eelmine neljap\u00e4ev","dateFormatItem-Md":"M/d","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","field-era":"Ajaj\u00e4rk","field-year":"Aasta","dateTimeFormats-appendItem-Era":"{0} {1}","field-hour":"Tund","field-sat-relative+0":"see laup\u00e4ev","field-sat-relative+1":"j\u00e4rgmine laup\u00e4ev","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})",
"field-day-relative+0":"t\u00e4na","field-day-relative+1":"homme","field-thu-relative+0":"see neljap\u00e4ev","dateFormatItem-GyMMMd":"dd.MM.yy G","field-thu-relative+1":"j\u00e4rgmine neljap\u00e4ev","dateFormatItem-H":"HH","dateFormatItem-Gy":"y G","dateFormatItem-yyyyMMMEd":"E, dd.MM.yy G","dateFormatItem-M":"L","dateFormatItem-yyyyMMM":"MMM y G","dateFormatItem-yyyyMMMd":"dd.MM.yy G","field-sun-relative+0":"see p\u00fchap\u00e4ev","dateFormatItem-Hm":"HH:mm","field-sun-relative+1":"j\u00e4rgmine p\u00fchap\u00e4ev",
"field-minute":"Minut","field-dayperiod":"e.l./p.l.","dateFormatItem-d":"d","dateFormatItem-ms":"mm:ss","field-day-relative+-1":"eile","dateFormatItem-h":"h a","dateTimeFormat-long":"{1} kell {0}","dateFormatItem-MMMd":"d. MMM","dateFormatItem-MEd":"E, dd.MM","dateTimeFormat-full":"{1} kell {0}","field-fri-relative+0":"see reede","field-fri-relative+1":"j\u00e4rgmine reede","field-day":"P\u00e4ev","field-zone":"Ajav\u00f6\u00f6nd","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","dateFormatItem-y":"y G",
"field-year-relative+-1":"eelmine aasta","field-month-relative+-1":"eelmine kuu","dateFormatItem-hm":"h:mm a","dateTimeFormats-appendItem-Year":"{0} {1}","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dateFormatItem-yyyyMd":"dd.MM.yy GGGGG","field-month":"Kuu","dateFormatItem-MMM":"LLL","field-tue-relative+0":"see teisip\u00e4ev","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","field-tue-relative+1":"j\u00e4rgmine teisip\u00e4ev","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})",
"dateFormatItem-EHm":"E HH:mm","field-mon-relative+0":"see esmap\u00e4ev","field-mon-relative+1":"j\u00e4rgmine esmasp\u00e4ev","dateFormat-short":"dd.MM.yy GGGGG","dateFormatItem-EHms":"E HH:mm:ss","dateFormatItem-Ehms":"E h:mm:ss a","field-second":"Sekund","field-sat-relative+-1":"eelmine laup\u00e4ev","field-sun-relative+-1":"eelmine p\u00fchap\u00e4ev","field-month-relative+0":"see kuu","field-month-relative+1":"j\u00e4rgmine kuu","dateFormatItem-Ed":"d E","dateTimeFormats-appendItem-Timezone":"{0} {1}",
"field-week":"N\u00e4dal","dateFormat-medium":"dd.MM.yy G","field-year-relative+0":"see aasta","field-week-relative+-1":"eelmine n\u00e4dal","dateFormatItem-yyyyM":"MM.yy GGGGG","field-year-relative+1":"j\u00e4rgmine aasta","dateFormatItem-yyyyQQQQ":"QQQQ y G","dateTimeFormat-short":"{1}, {0}","dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-hms":"h:mm:ss a","dateFormatItem-GyMMM":"MMM y G","field-mon-relative+-1":"eelmine esmasp\u00e4ev","dateFormatItem-yyyy":"y G","field-week-relative+0":"see n\u00e4dal",
"field-week-relative+1":"j\u00e4rgmine n\u00e4dal"});