//>>built
define("dgrid/editor","dojo/_base/kernel dojo/_base/lang dojo/_base/array dojo/_base/Deferred dojo/on dojo/aspect dojo/has dojo/query ./Grid put-selector/put dojo/_base/sniff".split(" "),function(z,r,A,u,l,m,q,B,v,p){function s(a,b){a.value=b;if("radio"==a.type||"checkbox"==a.type)a.checked=a.defaultChecked=!!b}function w(a,b){if("number"==typeof b)a=isNaN(a)?a:parseFloat(a);else if("boolean"==typeof b)a="true"==a?!0:"false"==a?!1:a;else if(b instanceof Date){var d=new Date(a);a=isNaN(d.getTime())?
a:d}return a}function C(a,b,d,c,f){var e,g,k;if((d&&d.valueOf())!=(c&&c.valueOf())&&(e=b.element,g=b.row,k=b.column,k.field&&g))if(b={grid:a,cell:b,rowId:g.id,oldValue:d,value:c,bubbles:!0,cancelable:!0},f&&f.type&&(b.parentType=f.type),l.emit(e,"dgrid-datachange",b))a.updateDirty?(a.updateDirty(g.id,k.field,c),k.autoSave&&setTimeout(function(){a._trackError("save")},0)):g.data[k.field]=c;else{var h;(h=e.widget)?(h._dgridIgnoreChange=!0,h.set("value",d),setTimeout(function(){h._dgridIgnoreChange=
!1},0)):(h=e.input)&&s(h,d);return d}return c}function t(a,b,d){var c=a.cell(b.domNode||b),f=c.column,e,g;g=a._activeCell;if(!b.isValid||b.isValid())if(d=C(a,c,g?a._activeValue:b._dgridLastValue,"function"==typeof b.get?w(b.get("value")):w(b["checkbox"==b.type||"radio"==b.type?"checked":"value"]),d),g?a._activeValue=d:b._dgridLastValue=d,"radio"===b.type&&b.name&&!f.editOn&&f.field)for(e in g=a.row(b),B("input[type\x3dradio][name\x3d"+b.name+"]",a.contentNode).forEach(function(c){var h=a.row(c);c!==
b&&c._dgridLastValue&&(c._dgridLastValue=!1,a.updateDirty?a.updateDirty(h.id,f.field,!1):h.data[f.field]=!1)}),a.dirty)g.id!==e&&a.dirty[e][f.field]&&a.updateDirty(e,f.field,!1)}function x(a){var b=a.editor,d=a.editOn,c=a.grid,f="string"!=typeof b,e,g,k;e=a.editorArgs||{};"function"==typeof e&&(e=e.call(c,a));if(f)g=new b(e),a=g.focusNode||g.domNode,a.className+=" dgrid-input",g.connect(g,d?"onBlur":"onChange",function(){g._dgridIgnoreChange||t(c,this,{type:"widget"})});else if(k=function(a){var b=
a.target;"_dgridLastValue"in b&&-1<b.className.indexOf("dgrid-input")&&t(c,b,a)},a.grid._hasInputListener||(c._hasInputListener=!0,c.on("change",function(a){k(a)})),g=a=p(("textarea"==b?"textarea":"input[type\x3d"+b+"]")+".dgrid-input",r.mixin({name:a.field,tabIndex:isNaN(a.tabIndex)?-1:a.tabIndex},e)),9>q("ie")||q("ie")&&q("quirks"))"radio"==b||"checkbox"==b?l(g,"click",function(a){k(a)}):l(g,"change",function(a){k(a)});return g}function D(a,b){function d(){var a=f._activeCell;k.blur();"function"===
typeof f.focus&&setTimeout(function(){f.focus(a)},e&&9>q("ie")?15:0)}var c=x(a),f=a.grid,e=c.domNode,g=c.domNode||c,k=c.focusNode||g,h=e?function(){c.set("value",c._dgridLastValue)}:function(){s(c,c._dgridLastValue);t(a.grid,c)};l(k,"keydown",function(b){b=b.keyCode||b.which;27==b?(h(),f._activeValue=c._dgridLastValue,d()):13==b&&!1!==a.dismissOnEnter&&d()});(a._editorBlurHandle=l.pausable(c,"blur",function(){var b=g.parentNode,h=b.children.length-1,d={alreadyHooked:!0},e=f.cell(g);l.emit(e.element,
"dgrid-editor-hide",{grid:f,cell:e,column:a,editor:c,bubbles:!0,cancelable:!1});a._editorBlurHandle.pause();b.removeChild(g);if(e.row){for(p(e.element,"!dgrid-cell-editing");h--;)p(b.firstChild,"!");v.appendIfNode(b,a.renderCell(a.grid.row(b).data,f._activeValue,b,f._activeOptions?r.delegate(d,f._activeOptions):d))}f._focusedEditorCell=f._activeCell=f._activeValue=f._activeOptions=null})).pause();return c}function y(a,b,d,c){var f=a.domNode,e=b.grid;f||s(a,c);d.innerHTML="";p(d,".dgrid-cell-editing");
p(d,a.domNode||a);f&&(a._started||a.startup(),a._dgridIgnoreChange=!0,a.set("value",c),setTimeout(function(){a._dgridIgnoreChange=!1},0));a._dgridLastValue=c;e._activeCell&&(e._activeValue=c,l.emit(d,"dgrid-editor-show",{grid:e,cell:e.cell(d),column:b,editor:a,bubbles:!0,cancelable:!1}))}function E(a){function b(a){c.grid._activeCell=f;y(c.editorInstance,c,f,k);c._editTimer=setTimeout(function(){h.focus&&h.focus();c._editorBlurHandle&&c._editorBlurHandle.resume();c._editTimer=null;a.resolve(h)},0)}
var d,c,f,e,g,k,h,n;a.column||(a=this.cell(a));if(!a||!a.element)return null;c=a.column;g=c.field;f=a.element.contents||a.element;if(h=c.editorInstance){if(c.grid._activeCell!=f&&(d=a.row,k=(e=this.dirty&&this.dirty[d.id])&&g in e?e[g]:c.get?c.get(d.data):d.data[g],!c.canEdit||c.canEdit(a.row.data,k)))return n=new u,a=h.domNode||h,a.offsetWidth?(a.blur(),setTimeout(function(){b(n)},0)):b(n),n.promise}else if(c.editor&&(h=f.widget||f.input))return n=new u,h.focus&&h.focus(),n.resolve(h),n.promise;
return null}r.getObject("dgrid.editor",!0);return dgrid.editor=function(a,b,d){function c(a){var b=a.grid,c,d;b.edit||(b.edit=E,e.push(l(b.domNode,".dgrid-input:focusin",function(){b._focusedEditorCell=b.cell(this)})),c=b._editorFocusoutHandle=l.pausable(b.domNode,".dgrid-input:focusout",function(){b._focusedEditorCell=null}),e.push(c),e.push(m.before(b,"removeRow",function(a){var f=b._focusedEditorCell;a=b.row(a);f&&f.row.id===a.id&&(d=f,c.pause(),setTimeout(function(){c.resume();d=null},0))})),
e.push(m.after(b,"insertRow",function(a){var c=b.row(a);d&&d.row.id===c.id&&b.edit(b.cell(c,d.column.id));return a})))}var f=a.renderCell||v.defaultRenderCell,e=[],g;a||(a={});a.editor=b=b||a.editor||"text";a.editOn=d=d||a.editOn;g="string"!=typeof b;a.widgetArgs&&(z.deprecated("column.widgetArgs","use column.editorArgs instead","dgrid 0.4"),a.editorArgs=a.widgetArgs);m.after(a,"init",d?function(){c(a);a.editorInstance=D(a,f)}:function(){var b=a.grid;c(a);g&&e.push(m.before(b,"removeRow",function(c){if(c=
(c=b.cell(c,a.id).element)&&(c.contents||c).widget)b._editorFocusoutHandle.pause(),c.destroyRecursive()}))});m.after(a,"destroy",function(){A.forEach(e,function(a){a.remove()});a._editorBlurHandle&&a._editorBlurHandle.remove();a._editTimer&&clearTimeout(a._editTimer);d&&g&&a.editorInstance.destroyRecursive();a.grid.edit=null});a.renderCell=d?function(b,c,e,g){var m=a.grid;if(!g||!g.alreadyHooked)l("TD"==e.tagName?e:e.parentNode,d,function(){m._activeOptions=g;m.edit(this)});return f.call(a,b,c,e,
g)}:function(b,c,d,e){if(!a.canEdit||a.canEdit(b,c))b=x(a),y(b,a,d,c),d[g?"widget":"input"]=b;else return f.call(a,b,c,d,e)};return a}});