<?php

/**
 *
 */
function to_do_menu() {
  $items = array();

  $items['to_do/load_data'] = array(
    'page callback' => 'load_to_do_datatable_json',
    'access callback' => TRUE,
  );

  $items['to_do/load_data/%'] = array(
    'page callback' => 'load_to_do_datatable_json',
    'access callback' => TRUE,
    'page arguments' => array(2),
  );


  return $items;
}

/**
 * Implements hook_block_info().
 */
function to_do_block_info() {
  $blocks = array();
  $blocks['to_do'] = array(
    'info' => t('To Do Block'),
  );
  return $blocks;
}


/**
 * Implements hook_theme().
 * @see http://www.devdungeon.com/content/using-tpl-template-files-custom-drupal-7-modules
 */
function to_do_theme() {
  return array(
    // Name to be called with theme(). theme('to_do')
    'to_do' => array(
      // Default variables
      'variables' => array(),
      // Which .tpl.php file to use my-cdx.tpl.php
      'template' => 'to-do',
      'path' => drupal_get_path('module', 'to_do') . '/templates'
    ),
    'td_status_modal' => array(
      // Default variables
      'variables' => array(),
      // Which .tpl.php file to use my-cdx.tpl.php
      'template' => 'to-do-status-modal',
      'path' => drupal_get_path('module', 'to_do') . '/templates'
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function to_do_block_view($delta = '') {
  $block = array();

  if ($delta == 'to_do') {
    drupal_add_js(drupal_get_path('module', 'datatables') . '/dataTables/media/js/jquery.dataTables.js', [
      'scope' => 'footer',
      'preprocess' => TRUE,
      'group' => JS_LIBRARY,
      'type' => 'file',
      'cache' => TRUE,
      'requires_jquery' => TRUE
    ]);

    drupal_add_js(libraries_get_path('yadcf-ordered-hierarchy-filter') . '/0.9.0.beta.5/jquery.dataTables.yadcf.js', [
      'scope' => 'footer',
      'preprocess' => TRUE,
      'group' => JS_LIBRARY,
      'type' => 'file',
      'cache' => TRUE,
      'requires_jquery' => TRUE
    ]);

    drupal_add_js(drupal_get_path('module', 'to_do') . '/js/to_do.js', [
      'scope' => 'footer',
      'preprocess' => TRUE,
      'group' => JS_DEFAULT,
      'type' => 'file',
      'cache' => TRUE,
      'requires_jquery' => TRUE
    ]);
    drupal_add_css(drupal_get_path('module', 'to_do') . '/css/to_do.css', [
      'preprocess' => TRUE,
      'group' => CSS_THEME
    ]);


    if (user_access('access content')) { //good idea to check user perms here
      // Set Modal Template
      $status_details_html = theme('td_status_modal');
      drupal_add_js(array("toDoStatusModal" => $status_details_html), 'setting');


      $block['subject'] = t('To Do');
      $block['content'] = theme('to_do');
      return $block;
    }
  }

  return $block;
}

/**
 * Load the json and pass it to the progress tracker datatable
 * this is a menu item function
 */
function load_to_do_datatable_json($use_cache = true) {
  if (!module_exists('eactivity_dataflow')) {
    drupal_json_output('EACTIVITY DATAFLOW module is not enabled.');
  }

  // Json formatted for Datatables
  $eactivity_dt_json = [];
  $to_do_data = load_eactivity_data('to_do', $use_cache);

  foreach ($to_do_data as $id => $eactivity_item) {

    if($id == 'cached') {
      $cached = $eactivity_item;
      continue;
    }

    $cedri_details = $eactivity_item['cedri_details'];
    $parenthesis_index = strpos($eactivity_item['title'], ')');
    $subheading = substr($eactivity_item['title'], $parenthesis_index + 1);
    $part_code = $cedri_details['part_code'];
    $report_type = $cedri_details['partner_system_report_type'];
    $sub_part_code = $cedri_details['sub_part_code'];

    $title =
      "<a class='favorites-ignore ga-tracking'  data-ga-event-label='to do handoff' target='_blank' href='" . $eactivity_item['handoff_url'] . "'>" .
      "<span class='report-name'>Review " .
      $report_type . " (" .
      $part_code . ", " . $sub_part_code . ") " .
      "</span><span class='subpart-name'>$subheading</span>" .
      "</a>" .
      "<span class='item-subscript-text'>" . $cedri_details['facility_name'] . "</span>";

    $status_note = $part_code . " - " . $cedri_details['part_name'] .
      "<br /> " . $sub_part_code . " - " . $cedri_details['sub_part_name'];

    $sub_part_code = $cedri_details['sub_part_code'];

    $status_anchor =
      "<a class='simple-dialog favorites-ignore td-status ga-tracking' " .
      "data-title='" . $cedri_details['facility_name'] . "' " .
      "data-status-note='" . $status_note . "' " .
      "data-due-date='" . $eactivity_item['date'] . "'" .
      "data-ga-event-label='to do details'" .
      ">Details</a>";


    $title .= "<br />" . $status_anchor;

    // Which tab does the date fall under?
    $timestamp = strtotime($eactivity_item['date']);
    $next_week_start = strtotime("monday next week");
    $two_weeks_start = strtotime("monday next week +1 week");

    if ($timestamp < $next_week_start) {
      $timeframe = "this_week";
    } else if ($timestamp < $two_weeks_start) {
      $timeframe = "next_week";
    } else {
      $timeframe = "beyond";
    }

    $eactivity_dt_row = [
      "", // Empty to allow for datatables to have index column
      $title,
      $eactivity_item['domain'],
      "<span class='date-display-single'>" . $eactivity_item['date'] . "</span><span class='date-subscript-text'>" . $eactivity_item['date_type'] . "</span>",
      $part_code,
      $sub_part_code,
      $report_type,
      $timeframe,
    ];

    $eactivity_dt_json[] = $eactivity_dt_row;
  }

  drupal_json_output(array("data" => $eactivity_dt_json, 'cached' => $cached));
}

