<?php

/**
 * @file
 * Contains jwt_auth_provider.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function jwt_auth_provider_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the jwt_auth_provider module.
    case 'help.page.jwt_auth_provider':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides Authentication provider of JWT') . '</p>';
      return $output;

    default:
  }
}
