// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.11/esri/copyright.txt for details.
//>>built
define("esri/arcgis/csv","dojo/_base/lang dojo/_base/array dojo/_base/Deferred dojo/sniff dojo/number dojox/data/CsvStore ../kernel ../config ../request ../SpatialReference ../geometry/Geometry ../geometry/jsonUtils ../geometry/webMercatorUtils".split(" "),function(h,e,x,y,J,K,L,z,M,r,p,A,B){function C(a){var b=0,c="";e.forEach([","," ",";","|","\t"],function(d){var f=a.split(d).length;f>b&&(b=f,c=d)});return c}function D(a,b){if(!a||"[object Date]"!==Object.prototype.toString.call(a)||isNaN(a.getTime()))return!1;
var c=!0;if(y("chrome")&&/\d+\W*$/.test(b)){var d=b.match(/[a-zA-Z]{2,}/);if(d){for(var c=!1,f=0,l=d.length,e=/^((jan(uary)?)|(feb(ruary)?)|(mar(ch)?)|(apr(il)?)|(may)|(jun(e)?)|(jul(y)?)|(aug(ust)?)|(sep(tember)?)|(oct(ober)?)|(nov(ember)?)|(dec(ember)?)|(am)|(pm)|(gmt)|(utc))$/i;!c&&f<=l&&!(c=!e.test(d[f]));)f++;c=!c}}return c}function E(a,b,c){var d=a.indexOf("\n"),d=h.trim(a.substr(0,d)),f=b.columnDelimiter;f||(f=C(d));var l=new K({data:a,separator:f});l.fetch({onComplete:function(a,f){var g=
0,d={layerDefinition:b.layerDefinition,featureSet:{features:[],geometryType:"esriGeometryPoint"}},w=d.layerDefinition.objectIdField;!w&&!e.some(d.layerDefinition.fields,function(a){return"esriFieldTypeOID"==a.type?(w=a.name,!0):!1})&&(d.layerDefinition.fields.push({name:"__OBJECTID",alias:"__OBJECTID",type:"esriFieldTypeOID",editable:!1,domain:null}),w="__OBJECTID");var h,q,s=l._attributes,r=[],t=[];e.forEach(d.layerDefinition.fields,function(a,g){"esriFieldTypeDate"===a.type?r.push(a.name):("esriFieldTypeDouble"===
a.type||"esriFieldTypeInteger"===a.type)&&t.push(a.name)});b.locationInfo&&"coordinates"===b.locationInfo.locationType?(h=b.locationInfo.latitudeFieldName,q=b.locationInfo.longitudeFieldName):e.forEach(s,function(a){var g;g=e.indexOf(F,a.toLowerCase());-1!==g&&(h=a);g=e.indexOf(G,a.toLowerCase());-1!==g&&(q=a)},this);if(!h||!q)setTimeout(function(){console.error("File does not seem to contain fields with point coordinates.")},1),c&&c(null,Error("File does not seem to contain fields with point coordinates."));
else{-1===e.indexOf(t,h)&&t.push(h);-1===e.indexOf(t,q)&&t.push(q);var s=0,p=a.length;for(s;s<p;s++){var u=a[s],v=l.getAttributes(u),n={};e.forEach(v,function(a,g){if(a){var b=a;0===a.length&&e.forEach(d.layerDefinition.fields,function(g,b){g.name==="attribute_"+(b-1)&&(a="attribute_"+(b-1))});if(-1<e.indexOf(r,a)){var b=l.getValue(u,b),c=new Date(b);n[a]=D(c,b)?c.getTime():null}else if(-1<e.indexOf(t,a)){c=J.parse(l.getValue(u,b));if((a==h||a==q)&&(isNaN(c)||181<Math.abs(c)))c=parseFloat(l.getValue(u,
b));isNaN(c)?n[a]=null:n[a]=c}else n[a]=l.getValue(u,b)}});n[w]=g;g++;var v=n[h],m=n[q];null==m||(null==v||isNaN(v)||isNaN(m))||d.featureSet.features.push({geometry:{x:m,y:v,spatialReference:{wkid:4326}},attributes:n})}d.layerDefinition.name="csv";c&&c(d)}},onError:function(a){console.error("Error fetching items from CSV store: ",a);c&&c(null,a)}});return!0}function m(a,b,c,d,f,l){0===a.length&&f(null);var m=A.getGeometryType(b),k=[];e.forEach(a,function(a){a=new m(a);a.spatialReference=c;k.push(a)},
this);b=[102113,102100,3857];c.wkid&&4326===c.wkid&&d.wkid&&-1<e.indexOf(b,d.wkid)?(e.forEach(k,function(a){a.xmin?(a.xmin=Math.max(a.xmin,-180),a.xmax=Math.min(a.xmax,180),a.ymin=Math.max(a.ymin,-89.99),a.ymax=Math.min(a.ymax,89.99)):a.rings?e.forEach(a.rings,function(a){e.forEach(a,function(a){a[0]=Math.min(Math.max(a[0],-180),180);a[1]=Math.min(Math.max(a[1],-89.99),89.99)},this)},this):a.paths?e.forEach(a.paths,function(a){e.forEach(a,function(a){a[0]=Math.min(Math.max(a[0],-180),180);a[1]=Math.min(Math.max(a[1],
-89.99),89.99)},this)},this):a.x&&(a.x=Math.min(Math.max(a.x,-180),180),a.y=Math.min(Math.max(a.y,-89.99),89.99))},this),a=[],e.forEach(k,function(b){b=B.geographicToWebMercator(b);102100!==d.wkid&&(b.spatialReference=d);a.push(b.toJson())},this),f(a)):null!==c.wkid&&-1<e.indexOf(b,c.wkid)&&null!==d.wkid&&4326===d.wkid?(a=[],e.forEach(k,function(b){a.push(B.webMercatorToGeographic(b).toJson())},this),f(a)):(b=function(b,c){b&&b.length===a.length?(a=[],e.forEach(b,function(b){b&&(b.rings&&0<b.rings.length&&
0<b.rings[0].length&&0<b.rings[0][0].length&&!isNaN(b.rings[0][0][0])&&!isNaN(b.rings[0][0][1])||b.paths&&0<b.paths.length&&0<b.paths[0].length&&0<b.paths[0][0].length&&!isNaN(b.paths[0][0][0])&&!isNaN(b.paths[0][0][1])||b.xmin&&!isNaN(b.xmin)&&b.ymin&&!isNaN(b.ymin)||b.x&&!isNaN(b.x)&&b.y&&!isNaN(b.y))?a.push(b.toJson()):a.push(null)},this),f(a)):l(b,c)},z.defaults.geometryService?z.defaults.geometryService.project(k,d,h.hitch(this,b),l):f(null))}function H(a,b){var c=[102113,102100,3857];return a&&
b&&a.wkid===b.wkid&&a.wkt===b.wkt||a&&b&&a.wkid&&b.wkid&&-1<e.indexOf(c,a.wkid)&&-1<e.indexOf(c,b.wkid)?!0:!1}function I(a,b,c,d){if(a.featureSet&&0!==a.featureSet.features.length)if(H(c,b))d(a);else{var f=function(b){var c=[];e.forEach(a.featureSet.features,function(a,d){b[d]&&(a.geometry=b[d],c.push(a))},this);d(a)},l=function(b,c){console.error("error projecting featureSet ("+a.layerDefinition.name+"). Final try.");d(a)},p=function(d,e){console.error("error projecting featureSet ("+a.layerDefinition.name+
"). Try one more time.");m(k,a.featureSet.geometryType,b,c,h.hitch(this,f),h.hitch(this,l))};if(a.featureSet.features&&0<a.featureSet.features.length){var k=[];e.forEach(a.featureSet.features,function(b){if(b.geometry.toJson)k.push(b.geometry);else{var c=A.getGeometryType(a.featureSet.geometryType);k.push(new c(b.geometry))}});b.toJson||(b=new r(b));c.toJson||(c=new r(c));m(k,a.featureSet.geometryType,b,c,h.hitch(this,f),h.hitch(this,p))}else d(a)}}var F="lat latitude y ycenter latitude83 latdecdeg POINT-Y".split(" "),
G="lon lng long longitude x xcenter longitude83 longdecdeg POINT-X".split(" ");p={latFieldStrings:F,longFieldStrings:G,buildCSVFeatureCollection:function(a){var b=new x,c=function(a,c){c?b.errback(c):b.callback(a)},d={url:a.url,handleAs:"text",load:function(b){E(b,a,h.hitch(this,c))},error:function(a){b.errback(a);console.error("error: "+a)}};-1<a.url.indexOf("arcgis.com")&&(-1<a.url.indexOf("/content/items")&&-1<a.url.indexOf("/data"))&&(d.headers={"Content-Type":""});M(d,{usePost:!1});return b},
projectFeatureCollection:function(a,b,c){var d=new x;c||(c=new r({wkid:4326}));I(a,c,b,h.hitch(this,function(a){d.callback(a)}));return d},generateDefaultPopupInfo:function(a){var b={esriFieldTypeDouble:1,esriFieldTypeSingle:1},c={esriFieldTypeInteger:1,esriFieldTypeSmallInteger:1},d={esriFieldTypeDate:1},f=null;a=e.map(a.layerDefinition.fields,h.hitch(this,function(a){"NAME"===a.name.toUpperCase()&&(f=a.name);var e="esriFieldTypeOID"!==a.type&&"esriFieldTypeGlobalID"!==a.type&&"esriFieldTypeGeometry"!==
a.type,k=null;if(e){var g=a.name.toLowerCase();if(-1<",stretched value,fnode_,tnode_,lpoly_,rpoly_,poly_,subclass,subclass_,rings_ok,rings_nok,".indexOf(","+g+",")||-1<g.indexOf("area")||-1<g.indexOf("length")||-1<g.indexOf("shape")||-1<g.indexOf("perimeter")||-1<g.indexOf("objectid")||g.indexOf("_")===g.length-1||g.indexOf("_i")===g.length-2&&1<g.length)e=!1;a.type in c?k={places:0,digitSeparator:!0}:a.type in b?k={places:2,digitSeparator:!0}:a.type in d&&(k={dateFormat:"shortDateShortTime"})}return h.mixin({},
{fieldName:a.name,label:a.alias,isEditable:!0,tooltip:"",visible:e,format:k,stringFieldOption:"textbox"})}));return{title:f?"{"+f+"}":"",fieldInfos:a,description:null,showAttachments:!1,mediaInfos:[]}},_getSeparator:C,_isValidDate:D,_processCsvData:E,_projectGeometries:m,_sameSpatialReference:H,_projectFeatureSet:I};y("extend-esri")&&h.setObject("arcgis.csv",p,L);return p});