<?php

/**
 * Implements hook_menu().
 */
function construction_permits_menu() {
  $items = array();

  $items['admin/config/system/construction-permits'] = array(
    'title' => 'Construction Permits Configurations',
    'description' => 'Manage Construction Permits Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('construction_permits_admin'),
    'access arguments' => array('administer'),
    'file' => 'construction_permits.admin.inc',
  );
  $items['construction_permits/form_submission'] = array(
    'page callback' => 'construction_permits_form_submission',
    'access callback' => TRUE,
  );
  $items['construction_permits/cgp_results_pdf'] = array(
    'page callback' => 'cgp_pdf_generate',
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Implements hook_block_info().
 */
function construction_permits_block_info() {
  $blocks = array();
  $blocks['construction_permits'] = array(
    'info' => t('Construction General Permits Block'),
  );
  return $blocks;
}

/*
 * Generate pdf using wkhtmltopdf tool.
 * Example here: https://gist.github.com/davejamesmiller/1965886
 * */
function cgp_pdf_generate() {
  $html = theme('construction_permits_pdf');
  $descriptor_spec = array(
    0 => array('pipe', 'r'), // stdin
    1 => array('pipe', 'w'), // stdout
    2 => array('pipe', 'w'), // stderr
  );
  $current_srvr_name = variable_get('eportal_server_name');
  if (isset($current_srvr_name) && ($current_srvr_name == $_SERVER['SERVER_NAME'])) {
    $process = proc_open('wkhtmltopdf -q - -', $descriptor_spec, $pipes);
  } else {
    $process = proc_open('sites/all/libraries/wkhtmltox/bin/wkhtmltopdf -q - -', $descriptor_spec, $pipes);
  }

  // Send the HTML on stdin
  fwrite($pipes[0], $html);
  fclose($pipes[0]);
  // Read the outputs
  $pdf = stream_get_contents($pipes[1]);
  $errors = stream_get_contents($pipes[2]);
  // Close the process
  fclose($pipes[1]);
  $return_value = proc_close($process);
  // Output the results
  if ($errors) {
    watchdog('construction_permits', "wkhtmltopdf PDF Generation Failed! " . $errors, WATCHDOG_ERROR);
    return "PDF Generation Failed!!";
  } else {
    header('Content-Type: application/pdf');
    header('Cache-Control: public, must-revalidate, max-age=0'); // HTTP/1.1
    header('Pragma: public');
    header('Expires: Sat, 26 Jul 1997 05:00:00 GMT'); // Date in the past
    header('Last-Modified: ' . gmdate('D, d M Y H:i:s') . ' GMT');
    header('Content-Length: ' . strlen($pdf));
    echo $pdf;
  }
}

/*
 * Implementation of hook_user_logout
 * Remove used pdf generation variable for the logged in user and session when the user logs out.
 * */
function construction_permits_user_logout($account) {
  global $user;
  variable_del($user->name . '_cgp_pdf_resp_' . $user->ssid);
}


/**
 * Implements hook_theme().
 * @see http://www.devdungeon.com/content/using-tpl-template-files-custom-drupal-7-modules
 */
function construction_permits_theme() {
  return array(
    // Name to be called with theme(). theme('construction_permits')
    'construction_permits' => array(
      // Default variables
      'variables' => array(),
      // Which .tpl.php file to use my-cdx.tpl.php
      'template' => 'construction-permits',
      'path' => drupal_get_path('module', 'construction_permits') . '/templates'
    ),
    'construction_permits_modal' => array(
      // Default variables
      'variables' => array(),
      // Which .tpl.php file to use be-well-informed-modal.tpl.php
      'template' => 'construction-permits-modal',
      'path' => drupal_get_path('module', 'construction_permits') . '/templates'
    ),
    'construction_permits_pdf' => array(
      'variables' => array(),
      'template' => 'construction-permits-pdf',
      'path' => drupal_get_path('module', 'construction_permits') . '/templates'
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function construction_permits_block_view($delta = '') {
  $block = array();
  if ($delta == 'construction_permits') {
    //good idea to check user perms here
    if (user_access('access content')) {
      drupal_add_js(drupal_get_path('module', 'datatables') . '/dataTables/media/js/jquery.dataTables.js', [
        'scope' => 'footer',
        'preprocess' => TRUE,
        'group' => JS_LIBRARY,
        'type' => 'file',
        'cache' => TRUE,
        'requires_jquery' => TRUE
      ]);
      drupal_add_js(drupal_get_path('module', 'construction_permits') . '/js/parsley.js', [
        'scope' => 'footer',
        'preprocess' => TRUE,
        'group' => JS_LIBRARY,
        'type' => 'file',
        'cache' => TRUE,
        'requires_jquery' => TRUE
      ]);
      drupal_add_js(drupal_get_path('module', 'construction_permits') . '/js/construction_permits.js', [
        'scope' => 'footer',
        'preprocess' => TRUE,
        'group' => JS_DEFAULT,
        'type' => 'file',
        'cache' => TRUE,
        'requires_jquery' => TRUE
      ]);
      drupal_add_css(drupal_get_path('module', 'construction_permits') . '/css/construction_permits.css', [
        'preprocess' => TRUE,
        'group' => CSS_THEME
      ]);

      // Set Modal Template
      $cgp_modal_html = theme('construction_permits_modal');
      drupal_add_js(array("construction_permits" => ["cgp_modal" => $cgp_modal_html]), 'setting');

      $block['subject'] = t('Find a Construction General Permit');
      $block['content'] = theme('construction_permits');
      return $block;
    }
  }
  return $block;
}

/**
 * Take users POST input and handoff to sample data or BE WELL INFORMED service
 */
function construction_permits_form_submission() {

  $datatable_formatted_response = [];

  if (variable_get('cgp_form_endpoint_sample_data', false)) {
    $construction_permits_response = sample_construction_permits_form_response();
    $datatable_formatted_response['datatable'] = construction_permits_datatable_response($construction_permits_response);
    $datatable_formatted_response['error'] = FALSE;
  } else {
    if (!isset($_POST) || count($_POST) === 0) {
      drupal_json_output(array(
        'error' => TRUE,
        'message' => 'Failed to receive any data.'
      ));
      return;
    }
    // All temporary
    // Sample page at https://devngn.epacdxnode.net/oeca-cgp-web/action/secured/home/#!/home
    $endpoint = variable_get('cgp_form_endpoint');
    $headers = array('Content-Type' => 'application/json');
    $response = drupal_http_request($endpoint, [
      "headers" => $headers,
      "method" => "POST",
      'timeout' => "10",
      'data' => json_encode($_POST)
    ]);
    if ($response->code !== "200") {
      $datatable_formatted_response['error'] = TRUE;
    } else {
      $formatted_data = construction_permits_datatable_response($response->data);
      $datatable_formatted_response['datatable'] = $formatted_data;
      $datatable_formatted_response['error'] = FALSE;
    }
  }
  drupal_json_output($datatable_formatted_response);
}

/**
 * Take BE WELL INFORMED response and format for Result Details and Result Summary datatables
 * @param $be_well_response_json
 * @return array
 */
function construction_permits_datatable_response($cgp_reponse_json) {
  $datatable_result_summary_json = [];
  foreach($cgp_reponse_json as $cgp_result) {
    $dt_row = [];
    $dt_row[] = $cgp_result['tracking_number'];
    $dt_row[] = $cgp_result['owner'];
    $dt_row[] = $cgp_result['project_name'];
    $dt_row[] = $cgp_result['state'];
    $dt_row[] = $cgp_result['city'];
    $dt_row[] = $cgp_result['status'];
    $dt_row[] = $cgp_result['date_submitted'];
    $datatable_result_summary_json[] = $dt_row;
  }
  return $datatable_result_summary_json;
}

function sample_construction_permits_form_response() {
  $path = drupal_get_path('module', 'construction_permits') . '/sample_data/devngn.epacdxnode.net.json';
  $sample = file_get_contents($path);
  return json_decode($sample, true);
}

/**
 * Implements template_preprocess_hook for be-well-informed-modal.tpl.php.
 */
function template_preprocess_construction_permits_modal(&$variables, $hook) {

}

/**
 * Implements template_preprocess_hook for be-well-informed-pdf.tpl.php.
 */
function template_preprocess_construction_permits_pdf(&$variables, $hook) {

  global $user;
  $variables['response_json_data_pdf'] = variable_get($user->name . '_cgp_pdf_resp_' . $user->ssid);
}

