<?php

/**
 * @file
 * Contains eep_location_services.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function eep_location_services_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the eep_location_services module.
    case 'help.page.eep_location_services':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('location services that affect all of the other widgets') . '</p>';
      return $output;

    default:
  }
}
