<?php


/**
 * Implements hook_menu().
 */
function chemical_rules_menu() {
  $items = array();
  $items['chemical_rules/form_submission'] = array(
    'page callback' => 'chemical_rules_form_submission',
    'access callback' => TRUE,
  );
  return $items;
}


/**
 * Implements hook_block_info().
 */
function chemical_rules_block_info() {
  $blocks = array();
  $blocks['chemical_rules'] = array(
    'info' => t('Chemical Rules and Regulations Block'),
  );
  return $blocks;
}

/**
 * Implements hook_theme().
 * @see http://www.devdungeon.com/content/using-tpl-template-files-custom-drupal-7-modules
 */
function chemical_rules_theme() {
  return array(
    // Name to be called with theme(). theme('chemical_rules')
    'chemical_rules' => array(
      // Default variables
      'variables' => array(),
      // Which .tpl.php file to use chemical-rules.tpl.php
      'template' => 'chemical-rules',
      'path' => drupal_get_path('module', 'chemical_rules') . '/templates'
    ),
    'chemical_rules_modal' => array(
      // Default variables
      'variables' => array(),
      // Which .tpl.php file to use chemical-rules-modal.tpl.php
      'template' => 'chemical-rules-modal',
      'path' => drupal_get_path('module', 'chemical_rules') . '/templates'
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function chemical_rules_block_view($delta = '') {
  $block = array();
  if ($delta == 'chemical_rules') {
    //good idea to check user perms here
    if (user_access('access content')) {
      drupal_add_js(libraries_get_path('css-element-queries') . '/ElementQueries.min.js', [
        'scope' => 'footer',
        'preprocess' => TRUE,
        'group' => JS_LIBRARY,
        'type' => 'file',
        'cache' => TRUE,
        'requires_jquery' => TRUE
      ]);
      drupal_add_js(libraries_get_path('css-element-queries') . '/ResizeSensor.min.js', [
        'scope' => 'footer',
        'preprocess' => TRUE,
        'group' => JS_LIBRARY,
        'type' => 'file',
        'cache' => TRUE,
        'requires_jquery' => TRUE
      ]);
      drupal_add_js(drupal_get_path('module', 'chemical_rules') . '/js/chemical_rules.js', [
        'scope' => 'footer',
        'preprocess' => TRUE,
        'group' => JS_DEFAULT,
        'type' => 'file',
        'cache' => TRUE,
        'requires_jquery' => TRUE
      ]);
      //If installed in own installation, include jQuery Tabs JS
      //drupal_add_js("sites/all/libraries/jqueryui/ui/minified/jquery.ui.tabs.min.js", ['scope'=>'footer', 'preprocess'=>true, 'group'=>JS_THEME, 'type'=>'file', 'cache'=>true, 'requires_jquery'=>true]);
      
      drupal_add_css("sites/all/libraries/jqueryui/themes/base/minified/jquery.ui.tabs.min.css", [
        'scope'=>'footer', 
        'preprocess'=>true, 
        'group'=>CSS_DEFAULT
      ]);
      drupal_add_js(drupal_get_path('module', 'chemical_rules') . '/js/toc.min.js', [
        'scope' => 'footer',
        'preprocess' => TRUE,
        'group' => JS_DEFAULT,
        'type' => 'file',
        'cache' => TRUE,
        'requires_jquery' => TRUE
      ]);      
      drupal_add_css(drupal_get_path('module', 'chemical_rules') . '/css/chemical_rules.css', [
        'preprocess' => TRUE,
        'group' => CSS_THEME
      ]);
      // Set Form Modal Template
      $chemical_modal = theme('chemical_rules_modal');
      drupal_add_js(array("chemical_rules" => ["modal" => $chemical_modal]), 'setting');

      $block['subject'] = t('Chemical Laws &amp; Regulations');
      $block['content'] = theme('chemical_rules');
      return $block;
    }
  }
  return $block;
}

/**
 * Take users POST input and handoff to sample data or SRS / LRS / LOD service
 */
function chemical_rules_form_submission() {
  if (!isset($_POST) || count($_POST) === 0) {
    drupal_json_output(array(
      'error' => TRUE,
      'message' => 'Failed to receive any data.'
    ));
    return;
  }

  $datatable_formatted_response = array();
  module_load_include('inc', 'feature_toggle', 'includes/feature_toggle.api');
  if (feature_toggle_get_status('chemical_rules_sample_data')) {
    $chemical_rules_response = sample_chemical_rules_response();
    $datatable_formatted_response['data'] = chemical_rules_datatable_response($chemical_rules_response);
    $datatable_formatted_response['error'] = FALSE;
  }
  else {
    $endpoint = "http://nodewebdev.epacdxnode.net/DWIService/dwievaluation";
    $headers = array('Content-Type' => 'application/json');
    $response = drupal_http_request($endpoint, [
      "headers" => $headers,
      "method" => "POST",
      'timeout' => "10",
      'data' => json_encode($_POST)
    ]);
    if ($response->code !== "200") {
      $datatable_formatted_response['error'] = TRUE;
    }
    else {
      $formatted_data = chemical_rules_datatable_response($response->data);
      $datatable_formatted_response['data'] = $formatted_data;
      $datatable_formatted_response['error'] = FALSE;
    }
  }

  drupal_json_output($datatable_formatted_response);
}

function sample_chemical_rules_response() {

  $response = [
    'ResultEvaluations' =>
      [
        [
          'ContaminantFullName' => 'Arsenic',
          'Symbol' => 'As',
          'GuidelineColor' => 'font-red',
          'UserContaminatValue' => '0.01 mg/L',
          'MaximumContaminantLevel' => '0.01 mg/L',
          'GuidelineText' => 'The value entered is close to exceeding the drinking water standard',
          'InterpretationMessages' => '<span>Does my well water meet the drinking water standard for fluoride?</span> No, your water does not meet federal and state drinking water standards as it contains more than 4.0 mg/L of fluoride.',
          'HealthMessages' => '<span>Can consuming water containing fluoride affect my health?</span> Consuming water containing more than 4.0 mg/L of fluoride can cause bone disease, which can include pain and tenderness of the bones and irregular bone deposits that can cause arthritis and crippling when occurring at joints (skeletal fluorosis).

Consuming water containing more than 2.0 mg/L of fluoride can cause small ‘white spots’ on children’s teeth (mottled enamel), or in extreme cases, brown staining or pitting of teeth that are still developing below the gums (dental fluorosis).

To reduce your exposure to fluoride in your well water, treat the water that you use for drinking and cooking to a level less than 2.0 mg/L. If treatment is not feasible, children under nine years old should be provided with an alternative source of drinking water that contains less than 2.0 mg/L of fluoride.

Consuming water containing an optimal level of fluoride helps protect against tooth decay. The U.S. Department of Health and Human Services’ recommended optimal range for fluoride in drinking water is 0.6 - 0.8 mg/L. You should talk with your dentist and doctor about the level of fluoride in your water and how you can reduce your and your family’s total fluoride exposure. Click here for more information from the U.S. Centers for Disease Control and Prevention about private well water and fluoride.',
          'TreatmentMessages' => '<span>How can I reduce the level of fluoride in my water?</span> Install one of the following point-of-use (POU) water treatment systems at your kitchen sink to reduce the level of fluoride in the water that you consume:

An NSF/ANSI Standard 61 certified activated alumina filter system.

OR

An NSF/ANSI Standard 58 certified reverse osmosis (RO) system.

More information about treatment for fluoride can be found in NHDES’ Fact Sheet.',

        ],
      ]
  ];
  return json_encode($response);
}


/**
 * Implements template_preprocess_hook for chemical-rules-modal.tpl.php.
 */
function template_preprocess_chemical_rules_modal(&$variables, $hook) {


}
