<?php

/**
 * @file
 * Contains eep_generate_pdf.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 * @param $route_name
 * @param $route_match
 *
 * @return $output
 *
 */
function eep_generate_pdf_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.eep_generate_pdf':
      $output = '';
      $output .= '<h1>' . t('EEP Generate PDF Help Page') . '</h1>';
      return $output;
    default:
      return "";
  }
}

function pdf_generate_theme($existing, $type, $theme, $path) {
  return [
    'pdf_generate' => [
      'variables' => ['test_var' => NULL],
    ],
  ];
}
