<?php
/**
 * @file
 * other_items_of_interest_feature.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function other_items_of_interest_feature_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_source'.
  $field_bases['field_source'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_source',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'max_length' => 255,
      'profile2_private' => FALSE,
    ),
    'translatable' => 0,
    'type' => 'text',
  );

  // Exported field_base: 'field_source_url'.
  $field_bases['field_source_url'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_source_url',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'max_length' => 255,
      'profile2_private' => FALSE,
    ),
    'translatable' => 0,
    'type' => 'text',
  );

  // Exported field_base: 'field_topic'.
  $field_bases['field_topic'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_topic',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'All' => 'All',
        'Air' => 'Air',
        'Energy' => 'Energy',
        'Endangered Species' => 'Endangered Species',
        'Environmental Justice' => 'Environmental Justice',
        'Compliance & Enforcement' => 'Compliance and Enforcement',
        'Health Effects' => 'Health Effects',
        'Pollution Prevention & Control' => 'Pollution Prevention and Control',
        'Regulated Facilities' => 'Regulated Facilities',
        'Services for Citizens' => 'Services for Citizens',
        'Soils & Land' => 'Soils and Land',
        'Water' => 'Water',
      ),
      'allowed_values_function' => '',
      'profile2_private' => FALSE,
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  return $field_bases;
}
