<?php

/**
 * @file
 * Contains jwt_handler.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function jwt_handler_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the jwt_handler module.
    case 'help.page.jwt_handler':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Handles creation and decoding of JWT&#039;s') . '</p>';
      return $output;

    default:
  }
}
