# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://e-enterprise/eep/proxy/service/bwi?XDEBUG_SESSION_START=PHPSTORM
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
    "StateCode": "NH",
    "RoutineContaminants": {
        "As": {
            "Symbol": "As",
            "Name": "Arsenic",
            "Value": "4444",
            "Unit": "mg/L"
        },
        "Cl": {
            "Symbol": "Cl",
            "Name": "Chloride",
            "Value": "4444",
            "Unit": "mg/L"
        }
    }
}

###

GET http://e-enterprise/eep/proxy/service/bwi?XDEBUG_SESSION_START=PHPSTORM
Accept: */*
Cache-Control: no-cache

###

GET http://e-enterprise/eep/proxy/service/get_test?XDEBUG_SESSION_START=PHPSTORM
Accept: */*
Cache-Control: no-cache

###

# BWI Service Tests

POST /TestRest/bwievaluation HTTP/1.1
Host: dev.e-enterprise.gov
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: 49251968-d0b5-33f4-3dc7-fb01ebdc7f99

{
  "StateCode": "NH",
  "RoutineContaminants": {
    "As": {
      "Symbol": "As",
      "Name": "Arsenic",
      "Value": "4444",
      "Unit": "mg/L"
    },
    "Cl": {
      "Symbol": "Cl",
      "Name": "Chloride",
      "Value": "4444",
      "Unit": "mg/L"
    }
  }
}
