<?php
/**
 * @file
 * Code for the My Maps View feature.
 */

/**
 * Implements hook_theme_registry_alter().
 */
function interactive_maps_theme_registry_alter(&$theme_registry) {
  // Defined path to the current module.
  $module_path = drupal_get_path('module', 'interactive_maps');
  // Find all .tpl.php files in this module's folder recursively.
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
  // Iterate through all found template file objects.
  foreach ($template_file_objects as $key => $template_file_object) {
    // If the template has not already been overridden by a theme.
    if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
      // Alter the theme path and template elements.
      $theme_registry[$key]['theme path'] = $module_path;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
      $theme_registry[$key]['type'] = 'module';
    }
  }
}


/**
 * returns a map Dataset, formated as JSON.
 */
function map_dataset() {
  $agency_map_datasets = views_get_view_result("agency_map_list");
  $mapset = array();
  foreach ($agency_map_datasets as $dataset) {
    $temp_dataset = array();
    $temp_dataset['id'] = $dataset->field_field_id[0]['rendered']['#markup'];
    $temp_dataset['alias'] = $dataset->field_field_ee_agency_map_agency[0]['rendered']['#title'];
    $temp_dataset['contactemail'] = $dataset->field_field_ee_agency_map_email[0]['rendered']['#markup'];
    $temp_dataset['url'] = $dataset->field_field_ee_agency_map_url[0]['rendered']['#title'];
    $temp_dataset['orgid'] = $dataset->field_field_orgid[0]['rendered']['#markup'];
    array_push($mapset, $temp_dataset);
  }
  return $mapset;
}

