// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.11/esri/copyright.txt for details.
//>>built
define("esri/IdentityManagerBase","dojo/_base/declare dojo/_base/config dojo/_base/lang dojo/_base/array dojo/_base/Deferred dojo/_base/json dojo/_base/url dojo/sniff dojo/cookie dojo/io-query dojo/regexp ./kernel ./config ./lang ./ServerInfo ./urlUtils ./deferredUtils ./request ./Evented ./OAuthCredential ./arcgis/OAuthInfo".split(" "),function(I,x,r,f,J,A,y,B,K,Q,R,m,C,w,D,s,L,E,M,N,S){var z={},F=function(a){var b=(new y(a.owningSystemUrl)).host;a=(new y(a.server)).host;var c=/.+\.arcgis\.com$/i;
return c.test(b)&&c.test(a)},G=function(a,b){return!(!F(a)||!b||!f.some(b,function(b){return b.test(a.server)}))},v,H=I(M,{declaredClass:"esri.IdentityManagerBase",constructor:function(){this._portalConfig=r.getObject("esriGeowConfig");this.serverInfos=[];this.oAuthInfos=[];this.credentials=[];this._soReqs=[];this._xoReqs=[];this._portals=[];this._getOAuthHash()},defaultTokenValidity:60,tokenValidity:null,signInPage:null,useSignInPage:!0,normalizeWebTierAuth:!1,_busy:null,_oAuthHash:null,_gwTokenUrl:"/sharing/generateToken",
_agsRest:"/rest/services",_agsPortal:/\/sharing(\/|$)/i,_agsAdmin:/https?:\/\/[^\/]+\/[^\/]+\/admin\/?(\/.*)?$/i,_adminSvcs:/\/admin\/services(\/|$)/i,_agolSuffix:".arcgis.com",_gwDomains:[{regex:/https?:\/\/www\.arcgis\.com/i,tokenServiceUrl:"https://www.arcgis.com/sharing/generateToken"},{regex:/https?:\/\/dev\.arcgis\.com/i,tokenServiceUrl:"https://dev.arcgis.com/sharing/generateToken"},{regex:/https?:\/\/.*dev[^.]*\.arcgis\.com/i,tokenServiceUrl:"https://devext.arcgis.com/sharing/generateToken"},
{regex:/https?:\/\/.*qa[^.]*\.arcgis\.com/i,tokenServiceUrl:"https://qaext.arcgis.com/sharing/generateToken"},{regex:/https?:\/\/.*.arcgis\.com/i,tokenServiceUrl:"https://www.arcgis.com/sharing/generateToken"}],_legacyFed:[],_regexSDirUrl:/http.+\/rest\/services\/?/ig,_regexServerType:/(\/(MapServer|GeocodeServer|GPServer|GeometryServer|ImageServer|NAServer|FeatureServer|GeoDataServer|GlobeServer|MobileServer|GeoenrichmentServer)).*/ig,_gwUser:/http.+\/users\/([^\/]+)\/?.*/i,_gwItem:/http.+\/items\/([^\/]+)\/?.*/i,
_gwGroup:/http.+\/groups\/([^\/]+)\/?.*/i,_errorCodes:[499,498,403,401],_rePortalTokenSvc:/\/sharing(\/rest)?\/generatetoken/i,_publicUrls:[/\/arcgis\/tokens/i,/\/sharing(\/rest)?\/generatetoken/i,/\/rest\/info/i],registerServers:function(a){var b=this.serverInfos;b?(a=f.filter(a,function(a){return!this.findServerInfo(a.server)},this),this.serverInfos=b.concat(a)):this.serverInfos=a;f.forEach(a,function(a){a.owningSystemUrl&&this._portals.push(a.owningSystemUrl);if(a.hasPortal){this._portals.push(a.server);
var b=C.defaults.io.corsEnabledServers,e=this._getOrigin(a.tokenServiceUrl);s.canUseXhr(a.server)||b.push(a.server.replace(/^https?:\/\//i,""));s.canUseXhr(e)||b.push(e.replace(/^https?:\/\//i,""))}},this)},registerOAuthInfos:function(a){var b=this.oAuthInfos;b?(a=f.filter(a,function(a){return!this.findOAuthInfo(a.portalUrl)},this),this.oAuthInfos=b.concat(a)):this.oAuthInfos=a},registerToken:function(a){var b=this._sanitizeUrl(a.server),c=this.findServerInfo(b),d;c||(c=new D,c.server=this._getOrigin(b),
c.tokenServiceUrl=this._getTokenSvcUrl(b),c.hasPortal=!0,this.registerServers([c]));(d=this.findCredential(b,a.userId))?r.mixin(d,a):(d=new v({userId:a.userId,server:c.server,token:a.token,expires:a.expires,ssl:a.ssl,scope:this._isServerRsrc(b)?"server":"portal"}),d.resources=[b],this.credentials.push(d));d.onTokenChange(!1)},toJson:function(){return w.fixJson({serverInfos:f.map(this.serverInfos,function(a){return a.toJson()}),oAuthInfos:f.map(this.oAuthInfos,function(a){return a.toJson()}),credentials:f.map(this.credentials,
function(a){return a.toJson()})})},initialize:function(a){if(a){r.isString(a)&&(a=A.fromJson(a));var b=a.serverInfos,c=a.oAuthInfos;a=a.credentials;if(b){var d=[];f.forEach(b,function(a){a.server&&a.tokenServiceUrl&&d.push(a.declaredClass?a:new D(a))});d.length&&this.registerServers(d)}if(c){var e=[];f.forEach(c,function(a){a.appId&&e.push(a.declaredClass?a:new S(a))});e.length&&this.registerOAuthInfos(e)}a&&f.forEach(a,function(a){a.userId&&(a.server&&a.token&&a.expires&&a.expires>(new Date).getTime())&&
(a=a.declaredClass?a:new v(a),a.onTokenChange(),this.credentials.push(a))},this)}},findServerInfo:function(a){var b;a=this._sanitizeUrl(a);f.some(this.serverInfos,function(c){s.hasSameOrigin(c.server,a,!0)&&(b=c);return!!b});return b},findOAuthInfo:function(a){var b;a=this._sanitizeUrl(a);f.some(this.oAuthInfos,function(c){s.hasSameOrigin(c.portalUrl,a,!0)&&(b=c);return!!b});return b},findCredential:function(a,b){var c,d;a=this._sanitizeUrl(a);d=this._isServerRsrc(a)?"server":"portal";b?f.some(this.credentials,
function(e){s.hasSameOrigin(a,e.server,!0)&&(b===e.userId&&e.scope===d)&&(c=e);return!!c},this):f.some(this.credentials,function(b){s.hasSameOrigin(a,b.server,!0)&&(-1!==this._getIdenticalSvcIdx(a,b)&&b.scope===d)&&(c=b);return!!c},this);return c},getCredential:function(a,b){var c,d,e=!0;w.isDefined(b)&&(r.isObject(b)?(c=!!b.token,d=b.error,e=!1!==b.prompt):c=b);a=this._sanitizeUrl(a);var g=new J(L._dfdCanceller),f=this._isAdminResource(a),p=c&&this._doPortalSignIn(a)?this._getEsriAuthCookie():null;
c=c?this.findCredential(a):null;if(p||c)return e=Error("You are currently signed in as: '"+(p&&p.email||c&&c.userId)+"'. You do not have access to this resource: "+a),e.code="IdentityManagerBase.1",e.httpCode=d&&d.httpCode,e.messageCode=d?d.messageCode:null,e.subcode=d?d.subcode:null,e.details=d?d.details:null,e.log=x.isDebug,g.errback(e),g;if(d=this._findCredential(a,b))return g.callback(d),g;if(d=this.findServerInfo(a))!d.hasServer&&this._isServerRsrc(a)&&(d._restInfoDfd=this._getTokenSvcUrl(a,
!0),d.hasServer=!0);else{p=this._getTokenSvcUrl(a);if(!p)return e=Error("Unknown resource - could not find token service endpoint."),e.code="IdentityManagerBase.2",e.log=x.isDebug,g.errback(e),g;d=new D;d.server=this._getOrigin(a);r.isString(p)?(d.tokenServiceUrl=p,e&&!this._findOAuthInfo(a)&&(d._selfDfd=this._getPortalSelf(p.replace(this._rePortalTokenSvc,"/sharing/rest/portals/self"),a)),d.hasPortal=!0):(d._restInfoDfd=p,d.hasServer=!0);this.registerServers([d])}return this._enqueue(a,d,b,g,f)},
getResourceName:function(a){return this._isRESTService(a)?a.replace(this._regexSDirUrl,"").replace(this._regexServerType,"")||"":this._gwUser.test(a)&&a.replace(this._gwUser,"$1")||this._gwItem.test(a)&&a.replace(this._gwItem,"$1")||this._gwGroup.test(a)&&a.replace(this._gwGroup,"$1")||""},generateToken:function(a,b,c){var d,e,f,n,p,O,t=new y(window.location.href.toLowerCase()),u=this._getEsriAuthCookie(),l,P=a.webTierAuth&&!b;n=a.shortLivedTokenValidity;var q;b&&(q=m.id.tokenValidity||n||m.id.defaultTokenValidity,
q>n&&(q=n));c&&(d=c.isAdmin,e=c.serverUrl,f=c.token,O=c.ssl,a.customParameters=c.customParameters);if(d)n=a.adminTokenServiceUrl;else if(n=a.tokenServiceUrl,p=new y(n.toLowerCase()),u&&(l=(l=u.auth_tier)&&l.toLowerCase()),("web"===l||a.webTierAuth)&&c&&c.serverUrl&&!O&&"http"===t.scheme&&(s.hasSameOrigin(t.uri,n,!0)||"https"===p.scheme&&t.host===p.host&&"7080"===t.port&&"7443"===p.port))n=n.replace(/^https:/i,"http:").replace(/:7443/i,":7080");c=E(r.mixin({url:n,content:r.mixin({request:"getToken",
username:b&&b.username,password:b&&b.password,serverUrl:e,token:f,expiration:q,referer:d||this._rePortalTokenSvc.test(a.tokenServiceUrl)?window.location.host:null,client:d?"referer":null,f:"json"},a.customParameters),handleAs:"json",callbackParamName:P?"callback":void 0},c&&c.ioArgs),{usePost:!P,disableIdentityLookup:!0,useProxy:this._useProxy(a,c)});c.addCallback(function(c){if(!c||!c.token)return c=Error("Unable to generate token"),c.code="IdentityManagerBase.3",c.log=x.isDebug,c;var d=a.server;
z[d]||(z[d]={});b&&(z[d][b.username]=b.password);c.validity=q;return c});c.addErrback(function(a){});return c},isBusy:function(){return!!this._busy},checkSignInStatus:function(a){return this.getCredential(a,{prompt:!1})},setRedirectionHandler:function(a){this._redirectFunc=a},setProtocolErrorHandler:function(a){this._protocolFunc=a},signIn:function(){},oAuthSignIn:function(){},onCredentialCreate:function(){},onCredentialsDestroy:function(){},destroyCredentials:function(){if(this.credentials){var a=
this.credentials.slice();f.forEach(a,function(a){a.destroy()})}this.onCredentialsDestroy()},_getOAuthHash:function(){var a=window.location.hash;if(a){"#"===a.charAt(0)&&(a=a.substring(1));var a=Q.queryToObject(a),b=!1;a.access_token&&a.expires_in&&a.state&&a.hasOwnProperty("username")?(a.state=A.fromJson(a.state),this._oAuthHash=a,b=!0):a.error&&a.error_description&&(console.log("IdentityManager OAuth Error: ",a.error," - ",a.error_description),"access_denied"===a.error&&(b=!0));if(b&&(!B("ie")||
8<B("ie")))window.location.hash=""}},_findCredential:function(a,b){var c=-1,d,e,g,n,p=b&&b.token;d=b&&b.resource;var m=this._isServerRsrc(a)?"server":"portal",t=f.filter(this.credentials,function(b){return s.hasSameOrigin(b.server,a,!0)&&b.scope===m});a=d||a;if(t.length)if(1===t.length)if(d=t[0],g=(e=(n=this.findServerInfo(d.server))&&n.owningSystemUrl)&&this.findCredential(e,d.userId),c=this._getIdenticalSvcIdx(a,d),p)-1!==c&&(d.resources.splice(c,1),this._removeResource(a,g));else return-1===c&&
d.resources.push(a),this._addResource(a,g),d;else{var u,l;f.some(t,function(b){l=this._getIdenticalSvcIdx(a,b);return-1!==l?(u=b,g=(e=(n=this.findServerInfo(u.server))&&n.owningSystemUrl)&&this.findCredential(e,u.userId),c=l,!0):!1},this);if(p)u&&(u.resources.splice(c,1),this._removeResource(a,g));else if(u)return this._addResource(a,g),u}},_findOAuthInfo:function(a){var b=this.findOAuthInfo(a);b||f.some(this.oAuthInfos,function(c){this._isIdProvider(c.portalUrl,a)&&(b=c);return!!b},this);return b},
_addResource:function(a,b){b&&-1===this._getIdenticalSvcIdx(a,b)&&b.resources.push(a)},_removeResource:function(a,b){var c=-1;b&&(c=this._getIdenticalSvcIdx(a,b),-1<c&&b.resources.splice(c,1))},_useProxy:function(a,b){return b&&b.isAdmin&&!s.hasSameOrigin(a.adminTokenServiceUrl,window.location.href)||!this._isPortalDomain(a.tokenServiceUrl)&&10.1==a.currentVersion&&!s.hasSameOrigin(a.tokenServiceUrl,window.location.href)},_getOrigin:function(a){a=new y(a);return a.scheme+"://"+a.host+(w.isDefined(a.port)?
":"+a.port:"")},_sanitizeUrl:function(a){a=s.fixUrl(r.trim(a));var b=(C.defaults.io.proxyUrl||"").toLowerCase(),c=b?a.toLowerCase().indexOf(b+"?"):-1;-1!==c&&(a=a.substring(c+b.length+1));return s.urlToObject(a).path},_isRESTService:function(a){return-1<a.indexOf(this._agsRest)},_isAdminResource:function(a){return this._agsAdmin.test(a)||this._adminSvcs.test(a)},_isServerRsrc:function(a){return this._isRESTService(a)||this._isAdminResource(a)},_isIdenticalService:function(a,b){var c;if(this._isRESTService(a)&&
this._isRESTService(b)){var d=this._getSuffix(a).toLowerCase(),e=this._getSuffix(b).toLowerCase();c=d===e;c||(c=/(.*)\/(MapServer|FeatureServer).*/ig,c=d.replace(c,"$1")===e.replace(c,"$1"))}else this._isAdminResource(a)&&this._isAdminResource(b)?c=!0:!this._isServerRsrc(a)&&(!this._isServerRsrc(b)&&this._isPortalDomain(a))&&(c=!0);return c},_isPortalDomain:function(a){a=a.toLowerCase();var b=(new y(a)).authority,c=this._portalConfig,d=-1!==b.indexOf(this._agolSuffix);!d&&c&&(d=s.hasSameOrigin(c.restBaseUrl,
a,!0));if(!d){if(!this._arcgisUrl&&(c=r.getObject("esri.arcgis.utils.arcgisUrl")))this._arcgisUrl=(new y(c)).authority;this._arcgisUrl&&(d=this._arcgisUrl.toLowerCase()===b)}d||(d=f.some(this._portals,function(b){return s.hasSameOrigin(b,a,!0)}));return d=d||this._agsPortal.test(a)},_isIdProvider:function(a,b){var c=-1,d=-1;f.forEach(this._gwDomains,function(e,f){-1===c&&e.regex.test(a)&&(c=f);-1===d&&e.regex.test(b)&&(d=f)});var e=!1;if(-1<c&&-1<d)if(0===c||4===c){if(0===d||4===d)e=!0}else if(1===
c){if(1===d||2===d)e=!0}else 2===c?2===d&&(e=!0):3===c&&3===d&&(e=!0);if(!e){var g=this.findServerInfo(b),n=g&&g.owningSystemUrl;n&&(F(g)&&this._isPortalDomain(n)&&this._isIdProvider(a,n))&&(e=!0)}return e},_isPublic:function(a){a=this._sanitizeUrl(a);return f.some(this._publicUrls,function(b){return b.test(a)})},_getIdenticalSvcIdx:function(a,b){var c=-1;f.some(b.resources,function(b,e){return this._isIdenticalService(a,b)?(c=e,!0):!1},this);return c},_getSuffix:function(a){return a.replace(this._regexSDirUrl,
"").replace(this._regexServerType,"$1")},_getTokenSvcUrl:function(a){var b,c;if((b=this._isRESTService(a))||this._isAdminResource(a))return c=a.toLowerCase().indexOf(b?this._agsRest:"/admin/"),b=a.substring(0,c)+"/admin/generateToken",a=a.substring(0,c)+"/rest/info",c=E({url:a,content:{f:"json"},handleAs:"json",callbackParamName:"callback"}),c.adminUrl_=b,c;if(this._isPortalDomain(a)){var d="";f.some(this._gwDomains,function(b){b.regex.test(a)&&(d=b.tokenServiceUrl);return!!d});d||f.some(this._portals,
function(b){s.hasSameOrigin(b,a,!0)&&(d=b+this._gwTokenUrl);return!!d},this);d||(c=a.toLowerCase().indexOf("/sharing"),-1!==c&&(d=a.substring(0,c)+this._gwTokenUrl));d||(d=this._getOrigin(a)+this._gwTokenUrl);d&&(b=(new y(a)).port,/^http:\/\//i.test(a)&&"7080"===b&&(d=d.replace(/:7080/i,":7443")),d=d.replace(/http:/i,"https:"));return d}if(-1!==a.toLowerCase().indexOf("premium.arcgisonline.com"))return"https://premium.arcgisonline.com/server/tokens"},_getPortalSelf:function(a,b){"https:"===window.location.protocol?
a=a.replace(/^http:/i,"https:").replace(/:7080/i,":7443"):/^http:/i.test(b)&&(a=a.replace(/^https:/i,"http:").replace(/:7443/i,":7080"));return E({url:a,content:{f:"json"},handleAs:"json",callbackParamName:"callback"},{crossOrigin:!1,disableIdentityLookup:!0})},_hasPortalSession:function(){return!!this._getEsriAuthCookie()},_getEsriAuthCookie:function(){var a;if(K.isSupported()){var b=this._getAllCookies("esri_auth"),c;for(c=0;c<b.length;c++){var d=A.fromJson(b[c]);if(d.portalApp){a=d;break}}}return a},
_getAllCookies:function(a){var b=[],c=document.cookie.match(RegExp("(?:^|; )"+R.escapeString(a)+"\x3d([^;]*)","g"));if(c)for(a=0;a<c.length;a++){var d=c[a],e=d.indexOf("\x3d");-1<e&&(d=d.substring(e+1),b.push(decodeURIComponent(d)))}return b},_doPortalSignIn:function(a){if(K.isSupported()){var b=this._getEsriAuthCookie(),c=this._portalConfig,d=window.location.href,e=this.findServerInfo(a);if(this.useSignInPage&&(c||this._isPortalDomain(d)||b)&&(e?e.hasPortal||e.owningSystemUrl&&this._isPortalDomain(e.owningSystemUrl):
this._isPortalDomain(a))&&(this._isIdProvider(d,a)||c&&(s.hasSameOrigin(c.restBaseUrl,a,!0)||this._isIdProvider(c.restBaseUrl,a))||s.hasSameOrigin(d,a,!0)))return!0}return!1},_checkProtocol:function(a,b,c,d){var e=!0;d=d?b.adminTokenServiceUrl:b.tokenServiceUrl;if(0===r.trim(d).toLowerCase().indexOf("https:")&&0!==window.location.href.toLowerCase().indexOf("https:")&&(!C.defaults.io.useCors||!s.canUseXhr(d)&&!s.canUseXhr(s.getProxyUrl(!0).path)))e=this._protocolFunc?!!this._protocolFunc({resourceUrl:a,
serverInfo:b}):!1,e||(a=Error("Aborted the Sign-In process to avoid sending password over insecure connection."),a.code="IdentityManagerBase.4",a.log=x.isDebug,console.log(a.message),c(a));return e},_enqueue:function(a,b,c,d,e,f){d||(d=new J(L._dfdCanceller));d.resUrl_=a;d.sinfo_=b;d.options_=c;d.admin_=e;d.refresh_=f;this._busy?s.hasSameOrigin(a,this._busy.resUrl_,!0)?this._soReqs.push(d):this._xoReqs.push(d):this._doSignIn(d);return d},_doSignIn:function(a){this._busy=a;var b=this,c=function(c){var d=
a.options_&&a.options_.resource,e=a.resUrl_,q=a.refresh_,k=!1;-1===f.indexOf(b.credentials,c)&&(q&&-1!==f.indexOf(b.credentials,q)?(q.userId=c.userId,q.token=c.token,q.expires=c.expires,q.validity=c.validity,q.ssl=c.ssl,q.creationTime=c.creationTime,k=!0,c=q):b.credentials.push(c));c.resources||(c.resources=[]);c.resources.push(d||e);c.scope=b._isServerRsrc(e)?"server":"portal";c.onTokenChange();var d=b._soReqs,h={};b._soReqs=[];f.forEach(d,function(a){if(!this._isIdenticalService(e,a.resUrl_)){var b=
this._getSuffix(a.resUrl_);h[b]||(h[b]=!0,c.resources.push(a.resUrl_))}},b);a.callback(c);f.forEach(d,function(a){a.callback(c)});b._busy=a.resUrl_=a.sinfo_=a.refresh_=null;if(!k)b.onCredentialCreate({credential:c});b._soReqs.length&&b._doSignIn(b._soReqs.shift());b._xoReqs.length&&b._doSignIn(b._xoReqs.shift())},d=function(c){a.errback(c);b._busy=a.resUrl_=a.sinfo_=a.refresh_=null;b._soReqs.length&&b._doSignIn(b._soReqs.shift());b._xoReqs.length&&b._doSignIn(b._xoReqs.shift())},e=function(e,l,f,
q){var k=a.sinfo_,h=!a.options_||!1!==a.options_.prompt;b._doPortalSignIn(a.resUrl_)?(l=b._getEsriAuthCookie(),e=b._portalConfig,l?c(new v({userId:l.email,server:k.server,token:l.token,expires:null})):h?(h="",l=window.location.href,h=b.signInPage?b.signInPage:e?e.baseUrl+e.signin:b._isIdProvider(l,a.resUrl_)?b._getOrigin(l)+"/home/signin.html":k.tokenServiceUrl.replace(b._rePortalTokenSvc,"")+"/home/signin.html",h=h.replace(/http:/i,"https:"),e&&!1===e.useSSL&&(h=h.replace(/https:/i,"http:")),0===
l.toLowerCase().replace("https","http").indexOf(h.toLowerCase().replace("https","http"))?(k=Error("Cannot redirect to Sign-In page from within Sign-In page. URL of the resource that triggered this workflow: "+a.resUrl_),k.code="IdentityManagerBase.5",k.log=x.isDebug,d(k)):b._redirectFunc?b._redirectFunc({signInPage:h,returnUrlParamName:"returnUrl",returnUrl:l,resourceUrl:a.resUrl_,serverInfo:k}):window.location=h+"?returnUrl\x3d"+window.escape(l)):(k=Error("User is not signed in."),k.code="IdentityManagerBase.6",
k.log=x.isDebug,d(k))):e?c(new v({userId:e,server:k.server,token:f,expires:w.isDefined(q)?Number(q):null,ssl:!!l})):t?(e=t._oAuthCred,e||(l=new N(t,window.localStorage),f=new N(t,window.sessionStorage),l.isValid()&&f.isValid()?l.expires>f.expires?(e=l,f.destroy()):(e=f,l.destroy()):e=l.isValid()?l:f,t._oAuthCred=e),e.isValid()?c(new v({userId:e.userId,server:k.server,token:e.token,expires:e.expires,ssl:e.ssl,_oAuthCred:e})):b._oAuthHash&&b._oAuthHash.state.portalUrl===t.portalUrl?(h=b._oAuthHash,
k=new v({userId:h.username,server:k.server,token:h.access_token,expires:(new Date).getTime()+1E3*Number(h.expires_in),ssl:"true"===h.ssl,oAuthState:h.state,_oAuthCred:e}),e.storage=h.persist?window.localStorage:window.sessionStorage,e.token=k.token,e.expires=k.expires,e.userId=k.userId,e.ssl=k.ssl,e.save(),b._oAuthHash=null,c(k)):h?a._pendingDfd=b.oAuthSignIn(a.resUrl_,k,t,a.options_).addCallbacks(c,d):(k=Error("User is not signed in."),k.code="IdentityManagerBase.6",k.log=x.isDebug,d(k))):h?b._checkProtocol(a.resUrl_,
k,d,a.admin_)&&(h=a.options_,a.admin_&&(h=h||{},h.isAdmin=!0),a._pendingDfd=b.signIn(a.resUrl_,k,h).addCallbacks(c,d)):(k=Error("User is not signed in."),k.code="IdentityManagerBase.6",k.log=x.isDebug,d(k))},g=function(){var e=a.sinfo_,l=e.owningSystemUrl,g=a.options_,q,k,h;g&&(q=g.token,k=g.error);h=b._findCredential(l,{token:q,resource:a.resUrl_});!h&&F(e)&&f.some(b.credentials,function(a){this._isIdProvider(l,a.server)&&(h=a);return!!h},b);h?(g=b.findCredential(a.resUrl_,h.userId))?c(g):G(e,b._legacyFed)?
(g=h.toJson(),g.server=e.server,g.resources=null,c(new v(g))):(a._pendingDfd=b.generateToken(b.findServerInfo(h.server),null,{serverUrl:a.resUrl_,token:h.token,ssl:h.ssl})).addCallbacks(function(b){c(new v({userId:h.userId,server:e.server,token:b.token,expires:w.isDefined(b.expires)?Number(b.expires):null,ssl:!!b.ssl,isAdmin:a.admin_,validity:b.validity}))},d):(b._busy=null,q&&(a.options_.token=null),(a._pendingDfd=b.getCredential(l.replace(/\/?$/,"/sharing"),{resource:a.resUrl_,token:q,error:k})).addCallbacks(function(c){b._enqueue(a.resUrl_,
a.sinfo_,a.options_,a,a.admin_)},function(a){d(a)}))},n=a.sinfo_.owningSystemUrl,p=this._isServerRsrc(a.resUrl_),m=a.sinfo_._restInfoDfd,t=this._findOAuthInfo(a.resUrl_);m?m.addCallbacks(function(c){var d=a.sinfo_;d.adminTokenServiceUrl=d._restInfoDfd.adminUrl_;d._restInfoDfd=null;d.tokenServiceUrl=r.getObject("authInfo.tokenServicesUrl",!1,c)||r.getObject("authInfo.tokenServiceUrl",!1,c)||r.getObject("tokenServiceUrl",!1,c);d.shortLivedTokenValidity=r.getObject("authInfo.shortLivedTokenValidity",
!1,c);d.currentVersion=c.currentVersion;d.owningTenant=c.owningTenant;if(c=d.owningSystemUrl=c.owningSystemUrl)b._portals.push(c),!d.hasPortal&&s.hasSameOrigin(c,a.resUrl_,!0)&&(t||(d._selfDfd=b._getPortalSelf(c.replace(/\/?$/,"/sharing/rest/portals/self"),a.resUrl_)),d.hasPortal=!0);p&&c?g():e()},function(){a.sinfo_._restInfoDfd=null;var b=Error("Unknown resource - could not find token service endpoint.");b.code="IdentityManagerBase.2";b.log=x.isDebug;d(b)}):p&&n?g():a.sinfo_._selfDfd?(n=function(c){a.sinfo_._selfDfd=
null;var d=c&&c.user&&c.user.username,f=c&&c.allSSL;a.sinfo_.webTierAuth=!!d;d&&b.normalizeWebTierAuth?(a.sinfo_._tokenDfd=b.generateToken(a.sinfo_,null,{ssl:f}),c=function(b){a.sinfo_._tokenDfd=null;e(d,f,b&&b.token,b&&b.expires)},a.sinfo_._tokenDfd.then(c,c)):e(d,f)},a.sinfo_._selfDfd.then(n,n)):e()}});v=I(M,{declaredClass:"esri.Credential",tokenRefreshBuffer:2,constructor:function(a){r.mixin(this,a);this.resources=this.resources||[];w.isDefined(this.creationTime)||(this.creationTime=(new Date).getTime())},
_oAuthCred:null,refreshToken:function(){function a(){"portal"===b.scope&&f.forEach(m.id.credentials,function(a){var c=m.id.findServerInfo(a.server),d=c&&c.owningSystemUrl;if(a!==b&&a.userId===b.userId&&d&&"server"===a.scope&&(s.hasSameOrigin(b.server,d,!0)||m.id._isIdProvider(d,b.server)))G(c,m.id._legacyFed)?(a.token=b.token,a.expires=b.expires,a.creationTime=b.creationTime,a.validity=b.validity,a.onTokenChange()):a.refreshToken()})}var b=this,c=this.resources&&this.resources[0],d=m.id.findServerInfo(this.server),
e=d&&d.owningSystemUrl,g=!!e&&"server"===this.scope,n=g&&G(d,m.id._legacyFed),p=g&&m.id.findServerInfo(e),r,t=(r=d.webTierAuth)&&m.id.normalizeWebTierAuth,u=z[this.server],u=u&&u[this.userId],l={username:this.userId,password:u},v;if(!r||t)if(g&&!p&&f.some(m.id.serverInfos,function(a){m.id._isIdProvider(e,a.server)&&(p=a);return!!p}),r=p&&m.id.findCredential(p.server,this.userId),!g||r)if(n)r.refreshToken();else{if(g)v={serverUrl:c,token:r&&r.token,ssl:r&&r.ssl};else if(t)l=null,v={ssl:this.ssl};else if(u)this.isAdmin&&
(v={isAdmin:!0});else{var q;c&&(c=m.id._sanitizeUrl(c),this._enqueued=1,q=m.id._enqueue(c,d,null,null,this.isAdmin,this),q.addCallback(function(){b._enqueued=0;a()}).addErrback(function(){b._enqueued=0}));return q}return m.id.generateToken(g?p:d,g?null:l,v).addCallback(function(c){b.token=c.token;b.expires=w.isDefined(c.expires)?Number(c.expires):null;b.creationTime=(new Date).getTime();b.validity=c.validity;b.onTokenChange();a()}).addErrback(function(){})}},onTokenChange:function(a){clearTimeout(this._refreshTimer);
var b=this.server&&m.id.findServerInfo(this.server),c=(b=b&&b.owningSystemUrl)&&m.id.findServerInfo(b);!1!==a&&((!b||"portal"===this.scope||c&&c.webTierAuth&&!m.id.normalizeWebTierAuth)&&(w.isDefined(this.expires)||w.isDefined(this.validity)))&&this._startRefreshTimer()},onDestroy:function(){},destroy:function(){this.userId=this.server=this.token=this.expires=this.validity=this.resources=this.creationTime=null;this._oAuthCred&&(this._oAuthCred.destroy(),this._oAuthCred=null);var a=f.indexOf(m.id.credentials,
this);-1<a&&m.id.credentials.splice(a,1);this.onTokenChange();this.onDestroy()},toJson:function(){return this._toJson()},_toJson:function(){var a=w.fixJson({userId:this.userId,server:this.server,token:this.token,expires:this.expires,validity:this.validity,ssl:this.ssl,isAdmin:this.isAdmin,creationTime:this.creationTime,scope:this.scope}),b=this.resources;b&&0<b.length&&(a.resources=b);return a},_startRefreshTimer:function(){clearTimeout(this._refreshTimer);var a=6E4*this.tokenRefreshBuffer,b=(this.validity?
this.creationTime+6E4*this.validity:this.expires)-(new Date).getTime();0>b&&(b=0);this._refreshTimer=setTimeout(r.hitch(this,this.refreshToken),b>a?b-a:b)}});H.Credential=v;B("extend-esri")&&(m.IdentityManagerBase=H);return H});