// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.11/esri/copyright.txt for details.
//>>built
require({cache:{"dojo/data/util/filter":function(){define(["../../_base/lang"],function(k){var b={};k.setObject("dojo.data.util.filter",b);b.patternToRegExp=function(b,k){for(var g="^",c=null,a=0;a<b.length;a++)switch(c=b.charAt(a),c){case "\\":g+=c;a++;g+=b.charAt(a);break;case "*":g+=".*";break;case "?":g+=".";break;case "$":case "^":case "/":case "+":case ".":case "|":case "(":case ")":case "{":case "}":case "[":case "]":g+="\\";default:g+=c}g+="$";return k?RegExp(g,"mi"):RegExp(g,"m")};return b})},
"dojo/data/util/simpleFetch":function(){define(["../../_base/lang","../../_base/kernel","./sorter"],function(k,b,q){var n={};k.setObject("dojo.data.util.simpleFetch",n);n.errorHandler=function(g,c){c.onError&&c.onError.call(c.scope||b.global,g,c)};n.fetchHandler=function(g,c){var a=c.abort||null,p=!1,f=c.start?c.start:0,d=c.count&&Infinity!==c.count?f+c.count:g.length;c.abort=function(){p=!0;a&&a.call(c)};var e=c.scope||b.global;c.store||(c.store=this);c.onBegin&&c.onBegin.call(e,g.length,c);c.sort&&
g.sort(q.createSortFunction(c.sort,this));if(c.onItem)for(var l=f;l<g.length&&l<d;++l){var h=g[l];p||c.onItem.call(e,h,c)}c.onComplete&&!p&&(l=null,c.onItem||(l=g.slice(f,d)),c.onComplete.call(e,l,c))};n.fetch=function(b){b=b||{};b.store||(b.store=this);this._fetchItems(b,k.hitch(this,"fetchHandler"),k.hitch(this,"errorHandler"));return b};return n})},"dojo/data/util/sorter":function(){define(["../../_base/lang"],function(k){var b={};k.setObject("dojo.data.util.sorter",b);b.basicComparator=function(b,
k){var g=-1;null===b&&(b=void 0);null===k&&(k=void 0);if(b==k)g=0;else if(b>k||null==b)g=1;return g};b.createSortFunction=function(k,n){function g(a,d,b,e){return function(p,f){var l=e.getValue(p,a),c=e.getValue(f,a);return d*b(l,c)}}for(var c=[],a,p=n.comparatorMap,f=b.basicComparator,d=0;d<k.length;d++){a=k[d];var e=a.attribute;if(e){a=a.descending?-1:1;var l=f;p&&("string"!==typeof e&&"toString"in e&&(e=e.toString()),l=p[e]||f);c.push(g(e,a,l,n))}}return function(a,d){for(var b=0;b<c.length;){var e=
c[b++](a,d);if(0!==e)return e}return 0}};return b})},"dojox/data/CsvStore":function(){define("dojo/_base/lang dojo/_base/declare dojo/_base/xhr dojo/_base/kernel dojo/data/util/filter dojo/data/util/simpleFetch".split(" "),function(k,b,q,n,g,c){b=b("dojox.data.CsvStore",null,{constructor:function(a){this._attributes=[];this._attributeIndexes={};this._dataArray=[];this._arrayOfAllItems=[];this._loadFinished=!1;a.url&&(this.url=a.url);this._csvData=a.data;a.label?this.label=a.label:""===this.label&&
(this.label=void 0);this._storeProp="_csvStore";this._idProp="_csvId";this._features={"dojo.data.api.Read":!0,"dojo.data.api.Identity":!0};this._loadInProgress=!1;this._queuedFetches=[];this.identifier=a.identifier;""===this.identifier?delete this.identifier:this._idMap={};"separator"in a&&(this.separator=a.separator);"urlPreventCache"in a&&(this.urlPreventCache=a.urlPreventCache?!0:!1)},url:"",label:"",identifier:"",separator:",",urlPreventCache:!1,_assertIsItem:function(a){if(!this.isItem(a))throw Error(this.declaredClass+
": a function was passed an item argument that was not an item");},_getIndex:function(a){a=this.getIdentity(a);this.identifier&&(a=this._idMap[a]);return a},getValue:function(a,b,f){this._assertIsItem(a);var d=f;if("string"===typeof b)b=this._attributeIndexes[b],null!=b&&(d=this._dataArray[this._getIndex(a)][b]||f);else throw Error(this.declaredClass+": a function was passed an attribute argument that was not a string");return d},getValues:function(a,b){var f=this.getValue(a,b);return f?[f]:[]},getAttributes:function(a){this._assertIsItem(a);
var b=[];a=this._dataArray[this._getIndex(a)];for(var f=0;f<a.length;f++)""!==a[f]&&b.push(this._attributes[f]);return b},hasAttribute:function(a,b){this._assertIsItem(a);if("string"===typeof b){var f=this._attributeIndexes[b],d=this._dataArray[this._getIndex(a)];return"undefined"!==typeof f&&f<d.length&&""!==d[f]}throw Error(this.declaredClass+": a function was passed an attribute argument that was not a string");},containsValue:function(a,b,f){var d=void 0;"string"===typeof f&&(d=g.patternToRegExp(f,
!1));return this._containsValue(a,b,f,d)},_containsValue:function(a,b,f,d){a=this.getValues(a,b);for(b=0;b<a.length;++b){var e=a[b];if("string"===typeof e&&d)return null!==e.match(d);if(f===e)return!0}return!1},isItem:function(a){if(a&&a[this._storeProp]===this)if(a=a[this._idProp],this.identifier){if(this._dataArray[this._idMap[a]])return!0}else if(0<=a&&a<this._dataArray.length)return!0;return!1},isItemLoaded:function(a){return this.isItem(a)},loadItem:function(a){},getFeatures:function(){return this._features},
getLabel:function(a){if(this.label&&this.isItem(a))return this.getValue(a,this.label)},getLabelAttributes:function(a){return this.label?[this.label]:null},_fetchItems:function(a,b,f){var d=this,e=function(a,e){var f=null;if(a.query){var c,l,f=[],h=a.queryOptions?a.queryOptions.ignoreCase:!1,s={};for(c in a.query)l=a.query[c],"string"===typeof l&&(s[c]=g.patternToRegExp(l,h));for(h=0;h<e.length;++h){var B=!0,C=e[h];for(c in a.query)l=a.query[c],d._containsValue(C,c,l,s[c])||(B=!1);B&&f.push(C)}}else f=
e.slice(0,e.length);b(f,a)};if(this._loadFinished)e(a,this._arrayOfAllItems);else if(""!==this.url)if(this._loadInProgress)this._queuedFetches.push({args:a,filter:e});else{this._loadInProgress=!0;var l=q.get({url:d.url,handleAs:"text",preventCache:d.urlPreventCache});l.addCallback(function(b){try{d._processData(b),e(a,d._arrayOfAllItems),d._handleQueuedFetches()}catch(c){f(c,a)}});l.addErrback(function(b){d._loadInProgress=!1;if(f)f(b,a);else throw b;});var c=null;a.abort&&(c=a.abort);a.abort=function(){l&&
-1===l.fired&&l.cancel();c&&c.call(a)}}else if(this._csvData)try{this._processData(this._csvData),this._csvData=null,e(a,this._arrayOfAllItems)}catch(k){f(k,a)}else{var n=Error(this.declaredClass+": No CSV source data was provided as either URL or String data input.");if(f)f(n,a);else throw n;}},close:function(a){},_getArrayOfArraysFromCsvFileContents:function(a){if(k.isString(a)){var b=RegExp("^\\s+","g"),f=RegExp("\\s+$","g"),d=RegExp('""',"g"),e=[],c=this._splitLines(a);for(a=0;a<c.length;++a){var h=
c[a];if(0<h.length){for(var h=h.split(this.separator),g=0;g<h.length;){var n=h[g].replace(b,""),m=n.replace(f,""),q=m.charAt(0),r=m.charAt(m.length-1),t=m.charAt(m.length-2),w=m.charAt(m.length-3);if(2===m.length&&'""'==m)h[g]="";else if('"'==q&&('"'!=r||'"'==r&&'"'==t&&'"'!=w)){if(g+1===h.length)return;h[g]=n+this.separator+h[g+1];h.splice(g+1,1)}else'"'==q&&'"'==r&&(m=m.slice(1,m.length-1),m=m.replace(d,'"')),h[g]=m,g+=1}e.push(h)}}this._attributes=e.shift();for(a=0;a<this._attributes.length;a++)this._attributeIndexes[this._attributes[a]]=
a;this._dataArray=e}},_splitLines:function(a){var b=[],f,d="",e=!1;for(f=0;f<a.length;f++){var c=a.charAt(f);switch(c){case '"':e=!e;d+=c;break;case "\r":e?d+=c:(b.push(d),d="",f<a.length-1&&"\n"==a.charAt(f+1)&&f++);break;case "\n":e?d+=c:(b.push(d),d="");break;default:d+=c}}""!==d&&b.push(d);return b},_processData:function(a){this._getArrayOfArraysFromCsvFileContents(a);this._arrayOfAllItems=[];if(this.identifier&&void 0===this._attributeIndexes[this.identifier])throw Error(this.declaredClass+": Identity specified is not a column header in the data set.");
for(a=0;a<this._dataArray.length;a++){var b=a;this.identifier&&(b=this._dataArray[a][this._attributeIndexes[this.identifier]],this._idMap[b]=a);this._arrayOfAllItems.push(this._createItemFromIdentity(b))}this._loadFinished=!0;this._loadInProgress=!1},_createItemFromIdentity:function(a){var b={};b[this._storeProp]=this;b[this._idProp]=a;return b},getIdentity:function(a){return this.isItem(a)?a[this._idProp]:null},fetchItemByIdentity:function(a){var b,c=a.scope?a.scope:n.global;if(this._loadFinished)b=
this._createItemFromIdentity(a.identity),this.isItem(b)||(b=null),a.onItem&&a.onItem.call(c,b);else{var d=this;if(""!==this.url)this._loadInProgress?this._queuedFetches.push({args:a}):(this._loadInProgress=!0,b=q.get({url:d.url,handleAs:"text"}),b.addCallback(function(b){try{d._processData(b);var e=d._createItemFromIdentity(a.identity);d.isItem(e)||(e=null);a.onItem&&a.onItem.call(c,e);d._handleQueuedFetches()}catch(g){a.onError&&a.onError.call(c,g)}}),b.addErrback(function(b){this._loadInProgress=
!1;a.onError&&a.onError.call(c,b)}));else if(this._csvData)try{d._processData(d._csvData),d._csvData=null,b=d._createItemFromIdentity(a.identity),d.isItem(b)||(b=null),a.onItem&&a.onItem.call(c,b)}catch(e){a.onError&&a.onError.call(c,e)}}},getIdentityAttributes:function(a){return this.identifier?[this.identifier]:null},_handleQueuedFetches:function(){if(0<this._queuedFetches.length){for(var a=0;a<this._queuedFetches.length;a++){var b=this._queuedFetches[a],c=b.filter,d=b.args;c?c(d,this._arrayOfAllItems):
this.fetchItemByIdentity(b.args)}this._queuedFetches=[]}}});k.extend(b,c);return b})},"esri/arcgis/csv":function(){define("dojo/_base/lang dojo/_base/array dojo/_base/Deferred dojo/sniff dojo/number dojox/data/CsvStore ../kernel ../config ../request ../SpatialReference ../geometry/Geometry ../geometry/jsonUtils ../geometry/webMercatorUtils".split(" "),function(k,b,q,n,g,c,a,p,f,d,e,l,h){function y(a){var d=0,e="";b.forEach([","," ",";","|","\t"],function(b){var c=a.split(b).length;c>d&&(d=c,e=b)});
return e}function z(a,b){if(!a||"[object Date]"!==Object.prototype.toString.call(a)||isNaN(a.getTime()))return!1;var d=!0;if(n("chrome")&&/\d+\W*$/.test(b)){var e=b.match(/[a-zA-Z]{2,}/);if(e){for(var d=!1,c=0,f=e.length,g=/^((jan(uary)?)|(feb(ruary)?)|(mar(ch)?)|(apr(il)?)|(may)|(jun(e)?)|(jul(y)?)|(aug(ust)?)|(sep(tember)?)|(oct(ober)?)|(nov(ember)?)|(dec(ember)?)|(am)|(pm)|(gmt)|(utc))$/i;!d&&c<=f&&!(d=!g.test(e[c]));)c++;d=!d}}return d}function m(a,d,e){var f=a.indexOf("\n"),f=k.trim(a.substr(0,
f)),l=d.columnDelimiter;l||(l=y(f));var h=new c({data:a,separator:l});h.fetch({onComplete:function(a,c){var f=0,s={layerDefinition:d.layerDefinition,featureSet:{features:[],geometryType:"esriGeometryPoint"}},l=s.layerDefinition.objectIdField;!l&&!b.some(s.layerDefinition.fields,function(a){return"esriFieldTypeOID"==a.type?(l=a.name,!0):!1})&&(s.layerDefinition.fields.push({name:"__OBJECTID",alias:"__OBJECTID",type:"esriFieldTypeOID",editable:!1,domain:null}),l="__OBJECTID");var k,n,v=h._attributes,
D=[],m=[];b.forEach(s.layerDefinition.fields,function(a,b){"esriFieldTypeDate"===a.type?D.push(a.name):("esriFieldTypeDouble"===a.type||"esriFieldTypeInteger"===a.type)&&m.push(a.name)});d.locationInfo&&"coordinates"===d.locationInfo.locationType?(k=d.locationInfo.latitudeFieldName,n=d.locationInfo.longitudeFieldName):b.forEach(v,function(a){var d;d=b.indexOf(w,a.toLowerCase());-1!==d&&(k=a);d=b.indexOf(A,a.toLowerCase());-1!==d&&(n=a)},this);if(!k||!n)setTimeout(function(){console.error("File does not seem to contain fields with point coordinates.")},
1),e&&e(null,Error("File does not seem to contain fields with point coordinates."));else{-1===b.indexOf(m,k)&&m.push(k);-1===b.indexOf(m,n)&&m.push(n);var v=0,q=a.length;for(v;v<q;v++){var p=a[v],r=h.getAttributes(p),u={};b.forEach(r,function(a,d){if(a){var e=a;0===a.length&&b.forEach(s.layerDefinition.fields,function(b,d){b.name==="attribute_"+(d-1)&&(a="attribute_"+(d-1))});if(-1<b.indexOf(D,a)){var e=h.getValue(p,e),c=new Date(e);u[a]=z(c,e)?c.getTime():null}else if(-1<b.indexOf(m,a)){c=g.parse(h.getValue(p,
e));if((a==k||a==n)&&(isNaN(c)||181<Math.abs(c)))c=parseFloat(h.getValue(p,e));isNaN(c)?u[a]=null:u[a]=c}else u[a]=h.getValue(p,e)}});u[l]=f;f++;var r=u[k],t=u[n];null==t||(null==r||isNaN(r)||isNaN(t))||s.featureSet.features.push({geometry:{x:t,y:r,spatialReference:{wkid:4326}},attributes:u})}s.layerDefinition.name="csv";e&&e(s)}},onError:function(a){console.error("Error fetching items from CSV store: ",a);e&&e(null,a)}});return!0}function x(a,d,e,c,f,g){0===a.length&&f(null);var n=l.getGeometryType(d),
m=[];b.forEach(a,function(a){a=new n(a);a.spatialReference=e;m.push(a)},this);d=[102113,102100,3857];e.wkid&&4326===e.wkid&&c.wkid&&-1<b.indexOf(d,c.wkid)?(b.forEach(m,function(a){a.xmin?(a.xmin=Math.max(a.xmin,-180),a.xmax=Math.min(a.xmax,180),a.ymin=Math.max(a.ymin,-89.99),a.ymax=Math.min(a.ymax,89.99)):a.rings?b.forEach(a.rings,function(a){b.forEach(a,function(a){a[0]=Math.min(Math.max(a[0],-180),180);a[1]=Math.min(Math.max(a[1],-89.99),89.99)},this)},this):a.paths?b.forEach(a.paths,function(a){b.forEach(a,
function(a){a[0]=Math.min(Math.max(a[0],-180),180);a[1]=Math.min(Math.max(a[1],-89.99),89.99)},this)},this):a.x&&(a.x=Math.min(Math.max(a.x,-180),180),a.y=Math.min(Math.max(a.y,-89.99),89.99))},this),a=[],b.forEach(m,function(b){b=h.geographicToWebMercator(b);102100!==c.wkid&&(b.spatialReference=c);a.push(b.toJson())},this),f(a)):null!==e.wkid&&-1<b.indexOf(d,e.wkid)&&null!==c.wkid&&4326===c.wkid?(a=[],b.forEach(m,function(b){a.push(h.webMercatorToGeographic(b).toJson())},this),f(a)):(d=function(d,
e){d&&d.length===a.length?(a=[],b.forEach(d,function(b){b&&(b.rings&&0<b.rings.length&&0<b.rings[0].length&&0<b.rings[0][0].length&&!isNaN(b.rings[0][0][0])&&!isNaN(b.rings[0][0][1])||b.paths&&0<b.paths.length&&0<b.paths[0].length&&0<b.paths[0][0].length&&!isNaN(b.paths[0][0][0])&&!isNaN(b.paths[0][0][1])||b.xmin&&!isNaN(b.xmin)&&b.ymin&&!isNaN(b.ymin)||b.x&&!isNaN(b.x)&&b.y&&!isNaN(b.y))?a.push(b.toJson()):a.push(null)},this),f(a)):g(d,e)},p.defaults.geometryService?p.defaults.geometryService.project(m,
c,k.hitch(this,d),g):f(null))}function r(a,d){var e=[102113,102100,3857];return a&&d&&a.wkid===d.wkid&&a.wkt===d.wkt||a&&d&&a.wkid&&d.wkid&&-1<b.indexOf(e,a.wkid)&&-1<b.indexOf(e,d.wkid)?!0:!1}function t(a,e,c,f){if(a.featureSet&&0!==a.featureSet.features.length)if(r(c,e))f(a);else{var g=function(d){var e=[];b.forEach(a.featureSet.features,function(a,b){d[b]&&(a.geometry=d[b],e.push(a))},this);f(a)},h=function(b,d){console.error("error projecting featureSet ("+a.layerDefinition.name+"). Final try.");
f(a)},n=function(b,d){console.error("error projecting featureSet ("+a.layerDefinition.name+"). Try one more time.");x(m,a.featureSet.geometryType,e,c,k.hitch(this,g),k.hitch(this,h))};if(a.featureSet.features&&0<a.featureSet.features.length){var m=[];b.forEach(a.featureSet.features,function(b){if(b.geometry.toJson)m.push(b.geometry);else{var d=l.getGeometryType(a.featureSet.geometryType);m.push(new d(b.geometry))}});e.toJson||(e=new d(e));c.toJson||(c=new d(c));x(m,a.featureSet.geometryType,e,c,k.hitch(this,
g),k.hitch(this,n))}else f(a)}}var w="lat latitude y ycenter latitude83 latdecdeg POINT-Y".split(" "),A="lon lng long longitude x xcenter longitude83 longdecdeg POINT-X".split(" ");e={latFieldStrings:w,longFieldStrings:A,buildCSVFeatureCollection:function(a){var b=new q,d=function(a,d){d?b.errback(d):b.callback(a)},e={url:a.url,handleAs:"text",load:function(b){m(b,a,k.hitch(this,d))},error:function(a){b.errback(a);console.error("error: "+a)}};-1<a.url.indexOf("arcgis.com")&&(-1<a.url.indexOf("/content/items")&&
-1<a.url.indexOf("/data"))&&(e.headers={"Content-Type":""});f(e,{usePost:!1});return b},projectFeatureCollection:function(a,b,e){var c=new q;e||(e=new d({wkid:4326}));t(a,e,b,k.hitch(this,function(a){c.callback(a)}));return c},generateDefaultPopupInfo:function(a){var d={esriFieldTypeDouble:1,esriFieldTypeSingle:1},e={esriFieldTypeInteger:1,esriFieldTypeSmallInteger:1},c={esriFieldTypeDate:1},f=null;a=b.map(a.layerDefinition.fields,k.hitch(this,function(a){"NAME"===a.name.toUpperCase()&&(f=a.name);
var b="esriFieldTypeOID"!==a.type&&"esriFieldTypeGlobalID"!==a.type&&"esriFieldTypeGeometry"!==a.type,g=null;if(b){var h=a.name.toLowerCase();if(-1<",stretched value,fnode_,tnode_,lpoly_,rpoly_,poly_,subclass,subclass_,rings_ok,rings_nok,".indexOf(","+h+",")||-1<h.indexOf("area")||-1<h.indexOf("length")||-1<h.indexOf("shape")||-1<h.indexOf("perimeter")||-1<h.indexOf("objectid")||h.indexOf("_")===h.length-1||h.indexOf("_i")===h.length-2&&1<h.length)b=!1;a.type in e?g={places:0,digitSeparator:!0}:a.type in
d?g={places:2,digitSeparator:!0}:a.type in c&&(g={dateFormat:"shortDateShortTime"})}return k.mixin({},{fieldName:a.name,label:a.alias,isEditable:!0,tooltip:"",visible:b,format:g,stringFieldOption:"textbox"})}));return{title:f?"{"+f+"}":"",fieldInfos:a,description:null,showAttachments:!1,mediaInfos:[]}},_getSeparator:y,_isValidDate:z,_processCsvData:m,_projectGeometries:x,_sameSpatialReference:r,_projectFeatureSet:t};n("extend-esri")&&k.setObject("arcgis.csv",e,a);return e})},"*noref":1}});
define("esri/layers/CSVLayer","dojo/_base/array dojo/_base/declare dojo/_base/lang dojo/has ../kernel ../arcgis/csv ./FeatureLayer ../geometry/Extent ../tasks/FeatureSet".split(" "),function(k,b,q,n,g,c,a,p,f){b=b(a,{declaredClass:"esri.layers.CSVLayer",_preventInit:!0,_fieldTypeMap:{Date:"esriFieldTypeDate",Number:"esriFieldTypeDouble",String:"esriFieldTypeString"},constructor:function(a,b){this.url=a;b=q.mixin(b,{outFields:["*"]});this.columnDelimiter=b.columnDelimiter;this.latitudeFieldName=b.latitudeFieldName;
this.longitudeFieldName=b.longitudeFieldName;var c=b.layerDefinition;c||(c={fields:b.fields||[],geometryType:"esriGeometryPoint",copyrightText:b.copyright},b.fields&&k.forEach(b.fields,q.hitch(this,function(a){a.type=this._fieldTypeMap[a.type||"String"];a.alias||(a.alias=a.name)})));this._buildCsvFcParam={url:this.url,columnDelimiter:this.columnDelimiter,layerDefinition:c};this.latitudeFieldName&&this.longitudeFieldName&&(this._buildCsvFcParam.locationInfo={locationType:"coordinates",latitudeFieldName:this.latitudeFieldName,
longitudeFieldName:this.longitudeFieldName});this._projectFeatures=q.hitch(this,this._projectFeatures);this._addFeatures=q.hitch(this,this._addFeatures);this._initCSVLayer(b)},refresh:function(){this._fireUpdateStart();this.applyEdits(null,null,this.graphics);this._loadFeatures()},_setMap:function(a){var b=this.inherited(arguments);this._fireUpdateStart();this._projectFeatures(this._csvFC).then(this._addFeatures).otherwise(this._errorHandler);this._csvFC=null;return b},_initCSVLayer:function(a){var b=
this;c.buildCSVFeatureCollection(this._buildCsvFcParam).then(function(c){b._csvFC=c;var f=c.layerDefinition;f.extent=b._getFCExtent(c);b._initFeatureLayer({layerDefinition:f},a)}).otherwise(this._errorHandler)},_loadFeatures:function(){c.buildCSVFeatureCollection(this._buildCsvFcParam).then(this._projectFeatures).then(this._addFeatures).otherwise(this._errorHandler)},_projectFeatures:function(a){return c.projectFeatureCollection(a,this._map.spatialReference)},_addFeatures:function(a){a=new f(a.featureSet);
this.applyEdits(a.features,null,null);this._fireUpdateEnd()},_getFCExtent:function(a){var b;if(a&&a.featureSet&&a.featureSet.features){a=a.featureSet.features;var c=a.length;if(1<c){var f=a[0].geometry;b=new p(f.x,f.y,f.x,f.y);for(c-=1;0<c;c--)f=a[c].geometry,b.xmin=Math.min(b.xmin,f.x),b.ymin=Math.min(b.ymin,f.y),b.xmax=Math.max(b.xmax,f.x),b.ymax=Math.max(b.ymax,f.y);0>=b.getWidth()&&0>=b.getHeight()&&(b=null)}}return b}});n("extend-esri")&&q.setObject("layers.CSVLayer",b,g);return b});