// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.11/esri/copyright.txt for details.
//>>built
define("esri/layers/HeatmapManager","dojo/_base/declare dojo/_base/lang dojo/on dojo/aspect dojo/_base/array require ../kernel ../sniff ../geometry/Point ./MapImageLayer ./MapImage ./FeatureLayer ../renderers/HeatmapRenderer ../tasks/query".split(" "),function(f,n,E,p,w,q,r,s,x,y,z,A,B,C){function D(){}f=f(null,{declaredClass:"esri.layers.HeatmapManager",heatmapRenderer:null,sourceLayer:null,imageLayer:null,useTiles:!0,useWorker:!1,map:null,constructor:function(a){var b=a.renderer;this.sourceLayer=
a;this.heatmapRenderer=b;this._hndls=[]},initialize:function(a){this.map=a;this.sourceLayer.setDrawMode(!1);var b=this,c=this.imageLayer=new y({className:"heatmapImgLyr"});!this.heatmapRenderer&&(this.sourceLayer&&this.sourceLayer.renderer)&&(this.heatmapRenderer=this.sourceLayer.renderer);this.recalculateHeatmap=this.recalculateHeatmap.bind(this);this._removeRenderer=this._removeRenderer.bind(this);this._handleRendererChange=this._handleRendererChange.bind(this);this._scRenderHandle=this.sourceLayer.on("renderer-change",
this._handleRendererChange);a.addLayer(c);q(["../workers/heatmapCalculator"],function(a){b._calculator=new a(n.mixin({width:b.map.width,height:b.map.height},b._getOptions()));b._setupRenderer()})},destroy:function(){this._removeHandlers();this._scRenderHandle.remove();this.map.removeLayer(this.imageLayer);this.sourceLayer.setRenderer(null);this.sourceLayer=this.imageLayer=this.map=this.heatmapRenderer=this._hndls=this._scRenderHandle=null},_handleRendererChange:function(a){var b=a.renderer,c=b instanceof
B;this.heatmapRenderer?c?this.heatmapRenderer=b:this._removeRenderer(a):c&&(this.heatmapRenderer=b,this._setupRenderer())},_setupRenderer:function(){var a=this._hndls,b=this.sourceLayer,c=this.map;b._originalDraw=b._draw;b._draw=D;var g=this;a.push(b.on("update-end",function(a){g.recalculateHeatmap()}));a.push(b.on("suspend",function(a){g.imageLayer.suspend()}));a.push(b.on("resume",function(a){g.imageLayer.resume()}));a.push(p.after(b,"redraw",this.recalculateHeatmap));a.push(c.on("layer-remove",
function(a){a.layer==g.sourceLayer&&c.removeLayer(g.imageLayer)}));b.mode!==A.MODE_ONDEMAND&&a.push(c.on("resize, zoom-end, pan-end",function(a){setTimeout(g.recalculateHeatmap,16)}));b.graphics&&b.graphics.length&&this.recalculateHeatmap()},_removeRenderer:function(a){a=a.target;a._draw=a._originalDraw;delete a._originalDraw;a.setDrawMode(!0);this.heatmapRenderer=null;this._removeHandlers();this._hndls=[]},recalculateHeatmap:function(){this._calculator?this._doMainCalculation():this._calculatorClient&&
this._doWorkerCalculation()},_doWorkerCalculation:function(){},_doMainCalculation:function(){var a=this.sourceLayer,b=this.imageLayer,c=this.map,g=this.heatmapRenderer,f=this.map.extent,t=this.map.width,u=this.map.height,p=this._calculator,q=this,k=function(e){e=e.features;var k=[],l=e.length,r=0,d,m=c.toScreen(new x(0,0)),s=m.x,m=m.y,v=c.getResolution(),h=0;c.extent._parts&&(h=w.map(c.extent._parts,function(b){return Math.abs(a._intersects(c,b.extent)[0])}),h.sort(function(a,b){return b-a}),h=h[0]);
for(;l--;)d=e[l],d.geometry&&(d={x:Math.abs(Math.ceil(d.geometry.x/v+s)),y:Math.abs(Math.floor(d.geometry.y/v-m)),attributes:d.attributes},d.x>c.width&&(d.x-=h),0>d.x&&(d.x+=h),k[r++]=d);e=p.calculateImageData(n.mixin({screenPoints:k,mapinfo:{extent:[f.xmin,f.ymin,f.xmax,f.ymax],resolution:c.getResolution()},width:t,height:u},q._getOptions()));e=g.getSymbol({geometry:c.extent,attributes:{size:[t,u],imageData:e}});e=new z({extent:c.extent,href:e.url});b.addImage(e);setTimeout(function(){var a=b._mapImages.slice(0,
-1),c=a.length;if(1E3<c)a=b._mapImages[c],b.removeAllImages(),b.addImage(a);else for(;c--&&a[c];)b.removeImage(a[c])},250)},l={geometry:c.extent,timeExtent:c.timeExtent,spatialRelationship:C.SPATIAL_REL_INTERSECTS};null!=a._canDoClientSideQuery(l)?a.queryFeatures(l,k):k({features:a.graphics})},_removeHandlers:function(){for(var a=this._hndls.length;a--;)this._hndls[a].remove()},_getOptions:function(){var a=this.heatmapRenderer;return{blurRadius:a.blurRadius,gradient:a.gradient,maxPixelIntensity:a.maxPixelIntensity,
minPixelIntensity:a.minPixelIntensity,field:a.field}}});s("extend-esri")&&n.setObject("layers.HeatmapManager",f,r);return f});