// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.11/esri/copyright.txt for details.
//>>built
require({cache:{"esri/tasks/Task":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/json dojo/has ../kernel ../deferredUtils ../urlUtils ../Evented".split(" "),function(k,n,f,B,H,G,K,F){k=k(F,{declaredClass:"esri.tasks._Task",_eventMap:{error:["error"],complete:["result"]},constructor:function(f,v){f&&n.isString(f)&&(this._url=K.urlToObject(this.url=f));v&&v.requestOptions&&(this.requestOptions=v.requestOptions);this.normalization=!0;this._errorHandler=n.hitch(this,this._errorHandler);
this.registerConnectEvents()},_useSSL:function(){var f=this._url,v=/^http:/i;this.url&&(this.url=this.url.replace(v,"https:"));f&&f.path&&(f.path=f.path.replace(v,"https:"))},_encode:function(k,v,J){var D,t,L={},z,u;for(z in k)if("declaredClass"!==z&&(D=k[z],t=typeof D,null!==D&&void 0!==D&&"function"!==t))if(n.isArray(D)){L[z]=[];u=D.length;for(t=0;t<u;t++)L[z][t]=this._encode(D[t])}else"object"===t?D.toJson&&(t=D.toJson(J&&J[z]),"esri.tasks.FeatureSet"===D.declaredClass&&t.spatialReference&&(t.sr=
t.spatialReference,delete t.spatialReference),L[z]=v?t:f.toJson(t)):L[z]=D;return L},_successHandler:function(f,v,n,k){v&&this[v].apply(this,f);n&&n.apply(null,f);k&&G._resDfd(k,f)},_errorHandler:function(f,n,k){this.onError(f);n&&n(f);k&&k.errback(f)},setNormalization:function(f){this.normalization=f},onError:function(){}});B("extend-esri")&&(H.Task=k);return k})},"esri/tasks/QueryTask":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/Deferred dojo/_base/json dojo/has ../kernel ../request ../deferredUtils ../geometry/Extent ../geometry/normalizeUtils ./Task ./FeatureSet".split(" "),
function(k,n,f,B,H,G,K,F,I,v,J,D,t){k=k(D,{declaredClass:"esri.tasks.QueryTask",_eventMap:{complete:["featureSet"],"execute-for-count-complete":["count"],"execute-for-ids-complete":["objectIds"],"execute-relationship-query-complete":["featureSets"]},constructor:function(f,k){this._handler=n.hitch(this,this._handler);this._relationshipQueryHandler=n.hitch(this,this._relationshipQueryHandler);this._executeForIdsHandler=n.hitch(this,this._executeForIdsHandler);this._countHandler=n.hitch(this,this._countHandler);
this._extentHandler=n.hitch(this,this._extentHandler);this.source=k&&k.source;this.gdbVersion=k&&k.gdbVersion;this.registerConnectEvents()},__msigns:[{n:"execute",c:4,a:[{i:0,p:["geometry"]}],e:2},{n:"executeForIds",c:3,a:[{i:0,p:["geometry"]}],e:2},{n:"executeForCount",c:3,a:[{i:0,p:["geometry"]}],e:2},{n:"executeForExtent",c:3,a:[{i:0,p:["geometry"]}],e:2}],onComplete:function(){},onExecuteRelationshipQueryComplete:function(){},onExecuteForIdsComplete:function(){},onExecuteForCountComplete:function(){},
onExecuteForExtentComplete:function(){},execute:function(f,k,u,b,g){var p=g.assembly;f=this._encode(n.mixin({},this._url.query,{f:"json"},f.toJson(p&&p[0])));var e=this._handler,c=this._errorHandler;this.source&&(p={source:this.source.toJson()},f.layer=H.toJson(p));this.gdbVersion&&(f.gdbVersion=this.gdbVersion);return F({url:this._url.path+"/query",content:f,callbackParamName:"callback",load:function(a,c){e(a,c,k,u,g.dfd)},error:function(a){c(a,u,g.dfd)},callbackSuffix:b},this.requestOptions)},executeRelationshipQuery:function(f,
k,u){f=this._encode(n.mixin({},this._url.query,{f:"json"},f.toJson()));var b=this._relationshipQueryHandler,g=this._errorHandler;this.gdbVersion&&(f.gdbVersion=this.gdbVersion);var p=new B(I._dfdCanceller);p._pendingDfd=F({url:this._url.path+"/queryRelatedRecords",content:f,callbackParamName:"callback",load:function(e,c){b(e,c,k,u,p)},error:function(e){g(e,u,p)}},this.requestOptions);return p},executeForIds:function(f,k,u,b){var g=b.assembly;f=this._encode(n.mixin({},this._url.query,{f:"json",returnIdsOnly:!0},
f.toJson(g&&g[0])));var p=this._executeForIdsHandler,e=this._errorHandler;this.source&&(g={source:this.source.toJson()},f.layer=H.toJson(g));this.gdbVersion&&(f.gdbVersion=this.gdbVersion);return F({url:this._url.path+"/query",content:f,callbackParamName:"callback",load:function(c,a){p(c,a,k,u,b.dfd)},error:function(c){e(c,u,b.dfd)}},this.requestOptions)},executeForCount:function(f,k,u,b){var g=b.assembly;f=this._encode(n.mixin({},this._url.query,{f:"json",returnIdsOnly:!0,returnCountOnly:!0},f.toJson(g&&
g[0])));var p=this._countHandler,e=this._errorHandler;this.source&&(g={source:this.source.toJson()},f.layer=H.toJson(g));this.gdbVersion&&(f.gdbVersion=this.gdbVersion);return F({url:this._url.path+"/query",content:f,callbackParamName:"callback",load:function(c,a){p(c,a,k,u,b.dfd)},error:function(c){e(c,u,b.dfd)}},this.requestOptions)},executeForExtent:function(f,k,u,b){var g=b.assembly;f=this._encode(n.mixin({},this._url.query,{f:"json",returnExtentOnly:!0,returnCountOnly:!0},f.toJson(g&&g[0])));
var p=this._extentHandler,e=this._errorHandler;this.source&&(g={source:this.source.toJson()},f.layer=H.toJson(g));this.gdbVersion&&(f.gdbVersion=this.gdbVersion);return F({url:this._url.path+"/query",content:f,callbackParamName:"callback",load:function(c,a){p(c,a,k,u,b.dfd)},error:function(c){e(c,u,b.dfd)}},this.requestOptions)},_handler:function(f,k,n,b,g){try{var p=new t(f);this._successHandler([p],"onComplete",n,g)}catch(e){this._errorHandler(e,b,g)}},_relationshipQueryHandler:function(k,n,u,b,
g){try{var p=k.geometryType,e=k.spatialReference,c={};f.forEach(k.relatedRecordGroups,function(a){var d={};d.geometryType=p;d.spatialReference=e;d.features=a.relatedRecords;d=new t(d);if(null!=a.objectId)c[a.objectId]=d;else for(var l in a)a.hasOwnProperty(l)&&"relatedRecords"!==l&&(c[a[l]]=d)});this._successHandler([c],"onExecuteRelationshipQueryComplete",u,g)}catch(a){this._errorHandler(a,b,g)}},_executeForIdsHandler:function(f,k,n,b,g){try{this._successHandler([f.objectIds],"onExecuteForIdsComplete",
n,g)}catch(p){this._errorHandler(p,b,g)}},_countHandler:function(f,k,n,b,g){try{var p,e=f.features,c=f.objectIds;if(c)p=c.length;else{if(e)throw Error("Unable to perform query. Please check your parameters.");p=f.count}this._successHandler([p],"onExecuteForCountComplete",n,g)}catch(a){this._errorHandler(a,b,g)}},_extentHandler:function(f,k,n,b,g){try{f.extent&&(f.extent=new v(f.extent)),this._successHandler([f],"onExecuteForExtentComplete",n,g)}catch(p){this._errorHandler(p,b,g)}}});J._createWrappers(k);
G("extend-esri")&&n.setObject("tasks.QueryTask",k,K);return k})},"esri/tasks/StatisticDefinition":function(){define(["dojo/_base/declare","dojo/_base/lang","dojo/has","../kernel"],function(k,n,f,B){k=k(null,{declaredClass:"esri.tasks.StatisticDefinition",toJson:function(){return{statisticType:this.statisticType,onStatisticField:this.onStatisticField,outStatisticFieldName:this.outStatisticFieldName,maxPointCount:this.maxPointCount,maxRecordCount:this.maxRecordCount,maxVertexCount:this.maxVertexCount}}});
f("extend-esri")&&n.setObject("tasks.StatisticDefinition",k,B);return k})},"esri/layers/labelLayerUtils/StaticLabelClass":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/connect dojo/has dojox/gfx/_base ../../kernel ../../lang ../../SpatialReference ../GraphicsLayer ../LabelClass ../../renderers/SimpleRenderer ../../geometry/Geometry ../../geometry/Extent ../../geometry/Point ../../geometry/Polyline ../../geometry/Polygon ../../symbols/TextSymbol ../../symbols/ShieldLabelSymbol ../../symbols/SimpleLineSymbol".split(" "),
function(k,n,f,B,H,G,K,F,I,v,J,D,t,L,z,u,b,g,p){k=k(I,{declaredClass:"esri.layers.labelLayerUtils.StaticLabel",constructor:function(){this._preparedLabels=[];this._placedLabels=[];this._extent=null;this._ymax=this._ymin=this._xmax=this._xmin=0;this._scale=1;this._LINE_STEP_CONST=1.5;this._POLYGON_X_STEP_CONST=1;this._POLYGON_Y_STEP_CONST=0.75},setMap:function(e,c){this._labelLayer=c;this._map=e;this._xmin=e.extent.xmin;this._xmax=e.extent.xmax;this._ymin=e.extent.ymin;this._ymax=e.extent.ymax;this._scale=
(this._xmax-this._xmin)/e.width},_process:function(e){var c,a,m,d,l,q,h,r;this._preparedLabels=e;this._placedLabels=[];for(e=this._preparedLabels.length-1;0<=e;e--){c=this._preparedLabels[e];d=c.labelWidth;l=c.labelHeight;h=(q=c.options)&&void 0!==q.lineLabelPlacement?q.lineLabelPlacement:"PlaceAtCenter";r=q&&void 0!==q.lineLabelPosition?q.lineLabelPosition:"Above";a=q&&void 0!==q.labelRotation?q.labelRotation:!0;m=c.angle*(Math.PI/180);var C=[];if("point"===c.geometry.type)this._generatePointPositions(c.geometry.x,
c.geometry.y,c.text,m,d,l,c.symbolWidth,c.symbolHeight,q,C);else if("multipoint"===c.geometry.type)for(a=0;a<c.geometry.points.length;a++)this._generatePointPositions(c.geometry.points[a][0],c.geometry.points[a][1],c.text,m,d,l,c.symbolWidth,c.symbolHeight,q,C);else if("polyline"===c.geometry.type)"PlaceAtStart"===h?this._generateLinePositionsPlaceAtStart(c.geometry,c.text,d,l,2*c.symbolHeight+l,h,r,a,C):"PlaceAtEnd"===h?this._generateLinePositionsPlaceAtEnd(c.geometry,c.text,d,l,2*c.symbolHeight+
l,h,r,a,C):this._generateLinePositionsPlaceAtCenter(c.geometry,c.text,d,l,2*c.symbolHeight+l,h,r,a,C);else if("polygon"===c.geometry.type)for(a=0;a<c.geometry.rings.length;a++)q=c.geometry.rings[a],u.prototype.isClockwise(q)&&this._generatePolygonPositionsForManyLabels(q,c.geometry.spatialReference,c.text,m,d,l,C);for(a=0;a<C.length;a++)q=C[a].x,h=C[a].y,void 0!==C[a].angle&&(m=C[a].angle),this._findPlace(c,c.text,q,h,m,d,l)}return this._placedLabels},_generatePointPositions:function(e,c,a,m,d,l,
q,h,r,C){a=r&&r.pointPriorities?r.pointPriorities:"AboveRight";d=(q+d)*this._scale;l=(h+l)*this._scale;switch(a.toLowerCase()){case "aboveleft":e-=d;c+=l;break;case "abovecenter":c+=l;break;case "aboveright":e+=d;c+=l;break;case "centerleft":e-=d;break;case "centercenter":break;case "centerright":e+=d;break;case "belowleft":e-=d;c-=l;break;case "belowcenter":c-=l;break;case "belowright":e+=d;c-=l;break;default:return}C.push({x:e,y:c})},_generateLinePositionsPlaceAtStart:function(e,c,a,m,d,l,q,h,r){l=
a*this._scale;var C=this._LINE_STEP_CONST*Math.min(this._map.width,this._map.height)*this._scale,M,b,g,f,p,k,s,w;for(M=0;M<e.paths.length;M++){var n=e.paths[M],E=l,A=0;for(b=0;b<n.length-1;b++)g=n[b][0],f=n[b][1],p=n[b+1][0],k=n[b+1][1],s=p-g,w=k-f,s=Math.sqrt(s*s+w*w),A+s>E?(A=this._generatePositionsOnLine(e.spatialReference,E,C,A,g,f,p,k,c,a,m,d,q,h,r),E=C):A+=s}},_generateLinePositionsPlaceAtEnd:function(e,c,a,m,d,l,q,h,r){l=a*this._scale;var C=this._LINE_STEP_CONST*Math.min(this._map.width,this._map.height)*
this._scale,b,g,f,p,k,x,s,n;for(b=0;b<e.paths.length;b++){var y=e.paths[b],E=l,A=0;for(g=y.length-2;0<=g;g--)f=y[g+1][0],p=y[g+1][1],k=y[g][0],x=y[g][1],s=k-f,n=x-p,s=Math.sqrt(s*s+n*n),A+s>E?(A=this._generatePositionsOnLine(e.spatialReference,E,C,A,f,p,k,x,c,a,m,d,q,h,r),E=C):A+=s}},_generateLinePositionsPlaceAtCenter:function(e,c,a,m,d,l,q,h,r){l=this._LINE_STEP_CONST*Math.min(this._map.width,this._map.height)*this._scale;var C,b,g,f,p,k,n,s,w;for(C=0;C<e.paths.length;C++){var y=e.paths[C];if(!(2>
y.length)){var E=0;for(b=0;b<y.length-1;b++)f=y[b][0],p=y[b][1],k=y[b+1][0],n=y[b+1][1],s=k-f,w=n-p,E+=Math.sqrt(s*s+w*w);var A=0;for(b=0;b<y.length-1;b++){f=y[b][0];p=y[b][1];k=y[b+1][0];n=y[b+1][1];s=k-f;w=n-p;s=Math.sqrt(s*s+w*w);if(A+s>E/2)break;A+=s}b==y.length-1&&b--;f=y[b][0];p=y[b][1];k=y[b+1][0];n=y[b+1][1];s=k-f;w=n-p;A=E/2-A;w=Math.atan2(w,s);s=f+A*Math.cos(w);w=p+A*Math.sin(w);f=this._angleAndShifts(f,p,k,n,d,q,h);r.push({x:s+f.shiftX,y:w+f.shiftY,angle:f.angle});var E=s,t=w,A=0;for(g=
b;g<y.length-1;g++)g==b?(f=E,p=t):(f=y[g][0],p=y[g][1]),k=y[g+1][0],n=y[g+1][1],s=k-f,w=n-p,s=Math.sqrt(s*s+w*w),A=A+s>l?this._generatePositionsOnLine(e.spatialReference,l,l,A,f,p,k,n,c,a,m,d,q,h,r):A+s;A=0;for(g=b;0<=g;g--)g==b?(f=E,p=t):(f=y[g+1][0],p=y[g+1][1]),k=y[g][0],n=y[g][1],s=k-f,w=n-p,s=Math.sqrt(s*s+w*w),A=A+s>l?this._generatePositionsOnLine(e.spatialReference,l,l,A,f,p,k,n,c,a,m,d,q,h,r):A+s}}},_generatePositionsOnLine:function(e,c,a,m,d,l,q,h,r,b,g,f,p,k,n){r=Math.atan2(h-l,q-d);b=d;
g=l;var x=b,s=g;do if(m=c-m,b+=m*Math.cos(r),g+=m*Math.sin(r),this._belongs(b,g,d,l,q,h))m=this._angleAndShifts(d,l,q,h,f,p,k),c=b+m.shiftX,s=g+m.shiftY,this._labelLayer._isWithinScreenArea(new t(c,s,c,s,e))&&n.push({x:c,y:s,angle:m.angle}),x=b,s=g,m=0,c=a;else return e=q-x,h-=s,Math.sqrt(e*e+h*h);while(1)},_belongs:function(e,c,a,m,d,l){if(d==a&&l==m)return!1;if(d>a){if(e>d||e<a)return!1}else if(e<d||e>a)return!1;if(l>m){if(c>l||c<m)return!1}else if(c<l||c>m)return!1;return!0},_angleAndShifts:function(e,
c,a,m,d,l,q){for(e=Math.atan2(m-c,a-e);e>Math.PI/2;)e-=Math.PI;for(;e<-(Math.PI/2);)e+=Math.PI;m=Math.sin(e);var h=Math.cos(e);a=c=0;"Above"==l&&(c=d*m*this._scale,a=d*h*this._scale);"Below"==l&&(c=-d*m*this._scale,a=-d*h*this._scale);d=[];d.angle=q?-e:0;d.shiftX=-c;d.shiftY=a;return d},_generatePolygonPositionsForManyLabels:function(e,c,a,m,d,l,q){m=this._calcRingExtent(e);if(0.75*(m.xmax-m.xmin)>this._map.width*this._scale||0.75*(m.ymax-m.ymin)>this._map.height*this._scale){var h=this._findCentroidForRing(e);
l=this._map.width*this._scale<m.xmax-m.xmin?this._POLYGON_X_STEP_CONST*this._map.width*this._scale:this._POLYGON_X_STEP_CONST*(m.xmax-m.xmin);d=this._map.height*this._scale<m.ymax-m.ymin?this._POLYGON_Y_STEP_CONST*this._map.height*this._scale:this._POLYGON_Y_STEP_CONST*(m.ymax-m.ymin);var r=h[0]-Math.round((h[0]-m.xmin)/l)*l,b=h[1]-Math.round((h[1]-m.ymin)/d)*d,g,h=!0;for(g=b;g<m.ymax;g+=d)if(h=!h,!(g<this._ymin||g>this._ymax))for(b=r+(h?0:l/2);b<m.xmax;b+=l)this._labelLayer._isWithinScreenArea(new t(b,
g,b,g,c))&&this._isPointWithinRing(a,e,b,g)&&q.push({x:b,y:g})}else{h=this._findCentroidForRing(e);for(m=0;10>m;m++)if(d=h[0],r=h[1]+(m%2?-1:1)*Math.floor(m/2)*l*this._scale,this._labelLayer._isWithinScreenArea(new t(d,r,d,r,c))&&this._isPointWithinRing(a,e,d,r)){q.push({x:d,y:r});break}}},_calcRingExtent:function(e){var c,a;a=new t;for(c=0;c<e.length-1;c++){var m=e[c][0],d=e[c][1];if(void 0===a.xmin||m<a.xmin)a.xmin=m;if(void 0===a.ymin||d<a.ymin)a.ymin=d;if(void 0===a.xmax||m>a.xmax)a.xmax=m;if(void 0===
a.ymax||d>a.ymax)a.ymax=d}return a},_isPointWithinPolygon:function(e,c,a,m){var d;for(d=0;d<c.rings.length;d++)if(this._isPointWithinRing(e,c.rings[d],a,m))return!0;return!1},_isPointWithinRing:function(e,c,a,m){var d,l,q,h,r=[],b=c.length;for(e=0;e<b-1;e++)if(d=c[e][0],l=c[e][1],q=c[e+1][0],h=c[e+1][1],!(d==q&&l==h)){if(l==h)if(m==l)r.push(d);else continue;d==q?(l<h&&(m>=l&&m<h)&&r.push(d),l>h&&(m<=l&&m>h)&&r.push(d)):(l=(q-d)/(h-l)*(m-l)+d,d<q&&(l>=d&&l<q)&&r.push(l),d>q&&(l<=d&&l>q)&&r.push(l))}r.sort(function(a,
d){return a-d});for(e=0;e<r.length-1;e++)if(d=r[e],q=r[e+1],a>=d&&a<q)if(e%2)break;else return!0;return!1},_findCentroidForRing:function(e){for(var c=e.length,a=[0,0],m=0,d=e[0][0],l=e[0][1],q=1;q<c-1;q++){var h=e[q][0],r=e[q][1],b=e[q+1][0],g=e[q+1][1],f=(h-d)*(g-l)-(b-d)*(r-l);a[0]+=f*(d+h+b);a[1]+=f*(l+r+g);m+=f}a[0]/=3*m;a[1]/=3*m;return a},_findCentroidForFeature:function(e){for(var c=0,a=[0,0],m=0;m<e.rings.length;m++)for(var d=e.rings[m],l=d.length,q=d[0][0],h=d[0][1],r=1;r<l-1;r++){var b=
d[r][0],g=d[r][1],f=d[r+1][0],p=d[r+1][1],k=(b-q)*(p-h)-(f-q)*(g-h);a[0]+=k*(q+b+f);a[1]+=k*(h+g+p);c+=k}a[0]/=3*c;a[1]/=3*c;return a},_findPlace:function(e,c,a,m,d,l,q){if(isNaN(a)||isNaN(m))return!1;for(var h=0;h<this._placedLabels.length;h++){var r=this._placedLabels[h].angle,b=this._placedLabels[h].width*this._scale,g=this._placedLabels[h].height*this._scale,f=this._placedLabels[h].x-a,p=this._placedLabels[h].y-m;if(0===d&&0===r){if(this._findPlace2(-l*this._scale,-q*this._scale,l*this._scale,
q*this._scale,f-b,p-g,f+b,p+g))return!1}else{var k=new t(-l*this._scale,-q*this._scale,l*this._scale,q*this._scale,null),n=0,x=1;0!==d&&(n=Math.sin(d),x=Math.cos(d));var s=f*x-p*n,f=f*n+p*x,r=r-d,n=Math.sin(r),x=Math.cos(r),w=-b*x- -g*n,p=-b*n+-g*x,r=+b*x- -g*n,y=+b*n+-g*x,b=s+w,g=f-p,n=s+r,x=f-y,w=s-w,p=f+p,s=s-r,f=f+y,r=new u;r.addRing([[b,g],[n,x],[w,p],[s,f],[b,g]]);if(k.intersects(r))return!1}}for(;d>Math.PI/2;)d-=Math.PI;for(;d<-(Math.PI/2);)d+=Math.PI;h={};h.layer=e;h.text=c;h.angle=d;h.x=
a;h.y=m;h.width=l;h.height=q;this._placedLabels.push(h);return!0},_findPlace2:function(e,c,a,m,d,l,q,h){return(e>=d&&e<=q||a>=d&&a<=q||e<=d&&a>=q)&&(c>=l&&c<=h||m>=l&&m<=h||c<=l&&m>=h)?!0:!1}});B("extend-esri")&&n.setObject("layers.labelLayerUtils.StaticLabel",k,G);return k})},"esri/layers/labelLayerUtils/DynamicLabelClass":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/connect dojo/has dojox/gfx/_base ../../kernel ../../lang ../../SpatialReference ../GraphicsLayer ../LabelClass ../../renderers/SimpleRenderer ../../geometry/Geometry ../../geometry/Extent ../../geometry/Point ../../geometry/Polyline ../../geometry/Polygon ../../symbols/TextSymbol ../../symbols/ShieldLabelSymbol ../../symbols/SimpleLineSymbol".split(" "),
function(k,n,f,B,H,G,K,F,I,v,J,D,t,L,z,u,b,g,p){k=k(I,{declaredClass:"esri.layers.labelLayerUtils.DynamicLabelClass",constructor:function(){this._preparedLabels=[];this._placedLabels=[];this._extent=null;this._y1=this._x1=this._y0=this._x0=this._ymax=this._ymin=this._xmax=this._xmin=0;this._scale=1},setMap:function(e,c){this._labelLayer=c;this._xmin=e.extent.xmin;this._xmax=e.extent.xmax;this._ymin=e.extent.ymin;this._ymax=e.extent.ymax;this._scale=(this._xmax-this._xmin)/e.width},_process:function(e){this._preparedLabels=
e;this._placedLabels=[];var c;for(e=this._preparedLabels.length-1;0<=e;e--){var a=this._preparedLabels[e],m=Math.min(a.labelWidth,a.labelHeight),d=a.labelWidth+0*m,m=a.labelHeight+0*m,l=(c=a.options)&&void 0!==c.lineLabelPlacement?c.lineLabelPlacement:"PlaceAtCenter",q=c&&void 0!==c.lineLabelPosition?c.lineLabelPosition:"Above",h=c&&void 0!==c.pointPriorities?c.pointPriorities:"AboveRight",b=[2,2,1,3,0,2,3,3,2];"AboveLeft"==h?b=[1,2,2,2,0,3,2,3,3]:"AboveCenter"==h?b=[2,1,2,2,0,2,3,3,3]:"AboveRight"==
h?b=[2,2,1,3,0,2,3,3,2]:"CenterLeft"==h?b=[2,2,3,1,0,3,2,2,3]:"CenterCenter"==h?b=[0,0,0,0,1,0,0,0,0]:"CenterRight"==h?b=[3,2,2,3,0,1,3,2,2]:"BelowLeft"==h?b=[2,3,3,2,0,3,1,2,2]:"BelowCenter"==h?b=[3,3,3,2,0,2,2,1,2]:"BelowRight"==h&&(b=[3,3,2,3,0,2,2,2,1]);var g=c&&void 0!==c.labelRotation?c.labelRotation:!0,h=a.angle*(Math.PI/180);c=c&&void 0!==c.howManyLabels?c.howManyLabels:"OneLabel";if("point"==a.geometry.type)this._generatePointPositions(a,a.geometry.x,a.geometry.y,a.text,h,d,m,a.symbolWidth,
a.symbolHeight,b);else if("multipoint"==a.geometry.type){l=a.geometry;for(q=0;q<l.points.length;q++)this._generatePointPositions(a,l.points[q][0],l.points[q][1],a.text,h,d,m,a.symbolWidth,a.symbolHeight,b)}else"polyline"==a.geometry.type?this._generateLinePositions(a,a.geometry,a.text,d,m,2*a.symbolHeight+m,l,q,g):"polygon"==a.geometry.type&&this._generatePolygonPositions(a,c,a.geometry,a.text,h,d,m)}return this._placedLabels},_generatePointPositions:function(e,c,a,m,d,l,q,h,b,g){h=(h+l)*this._scale;
b=(b+q)*this._scale;var f,p;for(f=1;3>=f;f++)for(p=1;9>=p;p++)if(g[p-1]==f)switch(p){case 1:if(this._findPlace(e,m,c-h,a+b,d,l,q))return;break;case 2:if(this._findPlace(e,m,c,a+b,d,l,q))return;break;case 3:if(this._findPlace(e,m,c+h,a+b,d,l,q))return;break;case 4:if(this._findPlace(e,m,c-h,a,d,l,q))return;break;case 5:if(this._findPlace(e,m,c,a,d,l,q))return;break;case 6:if(this._findPlace(e,m,c+h,a,d,l,q))return;break;case 7:if(this._findPlace(e,m,c-h,a-b,d,l,q))return;break;case 8:if(this._findPlace(e,
m,c,a-b,d,l,q))return;break;case 9:if(this._findPlace(e,m,c+h,a-b,d,l,q))return}},_generateLinePositions:function(e,c,a,m,d,l,b,h,g){var f=m*this._scale*m*this._scale,p,k,n;for(p=0;p<c.paths.length;p++){var t=c.paths[p],v=t.length,x=Math.floor((v-1)/2),s=0!==(v-1)%2?1:-1;"PlaceAtStart"==b&&(x=0,s=1);"PlaceAtEnd"==b&&(x=v-2,s=-1);for(;0<=x&&x<v-1;){for(k=x;k<v;k++){var w=t[x][0],y=t[x][1],E=t[k][0]-w,A=t[k][1]-y;if(E*E+A*A>f){for(var u=Math.atan2(A,E);u>Math.PI/2;)u-=Math.PI;for(;u<-(Math.PI/2);)u+=
Math.PI;var D=Math.sin(u),z=Math.cos(u),B=0,F=0;"Above"==h&&(B=l*D*this._scale,F=l*z*this._scale);"Below"==h&&(B=-l*D*this._scale,F=-l*z*this._scale);if(1==k-x){if(this._clipLine(w,y,t[k][0],t[k][1])&&(w=this._x1-this._x0,n=this._y1-this._y0,w*w+n*n>f&&(k=Math.atan2(n,w),E=m/2+2*d,y=E*this._scale*Math.cos(k),E=E*this._scale*Math.sin(k),"PlaceAtStart"==b?(w=this._x0+y,n=this._y0+E):"PlaceAtEnd"==b?(w=this._x1-y,n=this._y1-E):(w=this._x0+w/2,n=this._y0+n/2),this._findPlace(e,a,w-B,n+F,g?-k:0,m,d))))return}else{var G=
0;for(n=x;n<=k;n++)G=Math.max(G,Math.abs((t[n][1]-y)*z-(t[n][0]-w)*D));if(G<d&&this._findPlace(e,a,w+E/2-B,y+A/2+F,g?-u:0,m,d))return}break}}x+=s}}},_generatePolygonPositions:function(e,c,a,m,d,l,b){var h;if("ManyLabels"==c)for(c=0;c<a.rings.length;c++)h=a.rings[c],u.prototype.isClockwise(h)&&(h=this._findCentroid(h,this._xmin,this._ymin,this._xmax,this._ymax),this._findPlace(e,m,h[0],h[1],d,l,b));else{h=this._findCentroidForFeature(a,this._xmin,this._ymin,this._xmax,this._ymax);var g=h[1],f=0;for(c=
0;10>c;c++){f+=b/4;h=this._findCentroidForFeature(a,this._xmin,g+(f-b/4),this._xmax,g+(f+b/4));if(this._findPlace(e,m,h[0],h[1],d,l,b))break;h=this._findCentroidForFeature(a,this._xmin,g-(f+b/4),this._xmax,g-(f-b/4));if(this._findPlace(e,m,h[0],h[1],d,l,b))break}}},_findCentroid:function(e,c,a,m,d){var l=e.length,b=[0,0],h=0,g=e[0][0],f=e[0][1];g>m&&(g=m);g<c&&(g=c);f>d&&(f=d);f<a&&(f=a);for(var p=1;p<l-1;p++){var k=e[p][0],n=e[p][1],t=e[p+1][0],u=e[p+1][1];k>m&&(k=m);k<c&&(k=c);n>d&&(n=d);n<a&&(n=
a);t>m&&(t=m);t<c&&(t=c);u>d&&(u=d);u<a&&(u=a);var x=(k-g)*(u-f)-(t-g)*(n-f);b[0]+=x*(g+k+t);b[1]+=x*(f+n+u);h+=x}b[0]/=3*h;b[1]/=3*h;if(isNaN(b[0])||isNaN(b[1]))return b;a=[];this._fillBuffer(e,a,b);b[0]=this._sortBuffer(a,b[0],c,m);return b},_findCentroidForFeature:function(e,c,a,m,d){for(var l,b=0,h=[0,0],g=0;g<e.rings.length;g++){var f=e.rings[g],p=f.length,k=f[0][0],n=f[0][1];k>m&&(k=m);k<c&&(k=c);n>d&&(n=d);n<a&&(n=a);for(l=1;l<p-1;l++){var t=f[l][0],u=f[l][1],x=f[l+1][0],s=f[l+1][1];t>m&&(t=
m);t<c&&(t=c);u>d&&(u=d);u<a&&(u=a);x>m&&(x=m);x<c&&(x=c);s>d&&(s=d);s<a&&(s=a);var w=(t-k)*(s-n)-(x-k)*(u-n);h[0]+=w*(k+t+x);h[1]+=w*(n+u+s);b+=w}}h[0]/=3*b;h[1]/=3*b;if(isNaN(h[0])||isNaN(h[1]))return h;a=[];for(l=0;l<e.rings.length;l++)this._fillBuffer(e.rings[l],a,h);h[0]=this._sortBuffer(a,h[0],c,m);return h},_fillBuffer:function(e,c,a){for(var m=e.length-1,d=e[0][1]>=e[m][1]?1:-1,l=0;l<=m;l++){var b=l,h=l+1;l==m&&(h=0);var g=e[b][0],b=e[b][1],f=e[h][0],h=e[h][1],p=h>=b?1:-1;if(b<=a[1]&&a[1]<=
h||h<=a[1]&&a[1]<=b)a[1]!=b&&a[1]!=h?(c.push((a[1]-b)*(f-g)/(h-b)+g),d=p):a[1]==b&&a[1]!=h?(d!=p&&c.push(g),d=p):a[1]!=b&&a[1]==h?(c.push(f),d=p):a[1]==b&&a[1]==h&&(1==d&&c.push(g),c.push(f),d=p)}},_sortBuffer:function(e,c,a,m){var d=e.length;e.sort();if(0<d){for(var l=0,b=c=0;b<d-1;b+=2){var h=Math.abs(e[b+1]-e[b]);!(e[b]<=a&&e[b+1]<=a)&&(!(e[b]>=m&&e[b+1]>=m)&&h>l)&&(l=h,c=b)}d=e[c];e=e[c+1];d>m&&(d=m);d<a&&(d=a);e>m&&(e=m);e<a&&(e=a);c=(d+e)/2}return c},_findPlace:function(b,c,a,m,d,l,g){if(isNaN(a)||
isNaN(m))return!1;for(var h=0;h<this._placedLabels.length;h++){var f=this._placedLabels[h].angle,p=this._placedLabels[h].width*this._scale,k=this._placedLabels[h].height*this._scale,n=this._placedLabels[h].x-a,v=this._placedLabels[h].y-m;if(0===d&&0===f){if(this._findPlace2(-l*this._scale,-g*this._scale,l*this._scale,g*this._scale,n-p,v-k,n+p,v+k))return!1}else{var D=new t(-l*this._scale,-g*this._scale,l*this._scale,g*this._scale,null),z=0,x=1;0!==d&&(z=Math.sin(d),x=Math.cos(d));var s=n*x-v*z,n=
n*z+v*x,f=f-d,z=Math.sin(f),x=Math.cos(f),w=-p*x- -k*z,v=-p*z+-k*x,f=+p*x- -k*z,y=+p*z+-k*x,p=s+w,k=n-v,z=s+f,x=n-y,w=s-w,v=n+v,s=s-f,n=n+y,f=new u;f.addRing([[p,k],[z,x],[w,v],[s,n],[p,k]]);if(D.intersects(f))return!1}}for(;d>Math.PI/2;)d-=Math.PI;for(;d<-(Math.PI/2);)d+=Math.PI;h={};h.layer=b;h.text=c;h.angle=d;h.x=a;h.y=m;h.width=l;h.height=g;this._placedLabels.push(h);return!0},_findPlace2:function(b,c,a,m,d,l,g,h){return(b>=d&&b<=g||a>=d&&a<=g||b<=d&&a>=g)&&(c>=l&&c<=h||m>=l&&m<=h||c<=l&&m>=
h)?!0:!1},_clipLine:function(b,c,a,m){for(var d=this._code(b,c),l=this._code(a,m);0!==d||0!==l;){if(0!==(d&l))return!1;var g=a-b,h=m-c;0!==d?(b<this._xmin?(c+=h*(this._xmin-b)/g,b=this._xmin):b>this._xmax?(c+=h*(this._xmax-b)/g,b=this._xmax):c<this._ymin?(b+=g*(this._ymin-c)/h,c=this._ymin):c>this._ymax&&(b+=g*(this._ymax-c)/h,c=this._ymax),d=this._code(b,c)):(a<this._xmin?(m+=h*(this._xmin-a)/g,a=this._xmin):a>this._xmax?(m+=h*(this._xmax-a)/g,a=this._xmax):m<this._ymin?(a+=g*(this._ymin-m)/h,m=
this._ymin):m>this._ymax&&(a+=g*(this._ymax-m)/h,m=this._ymax),l=this._code(a,m))}this._x0=b;this._y0=c;this._x1=a;this._y1=m;return!0},_code:function(b,c){return(b<this._xmin?1:0)<<3|(b>this._xmax?1:0)<<2|(c<this._ymin?1:0)<<1|(c>this._ymax?1:0)}});B("extend-esri")&&n.setObject("layers.labelLayerUtils.DynamicLabelClass",k,G);return k})},"esri/tasks/FeatureSet":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/has ../kernel ../lang ../graphic ../SpatialReference ../graphicsUtils ../geometry/jsonUtils ../symbols/jsonUtils".split(" "),
function(k,n,f,B,H,G,K,F,I,v,J){k=k(null,{declaredClass:"esri.tasks.FeatureSet",constructor:function(k){if(k){n.mixin(this,k);var t=this.features,B=k.spatialReference,z=v.getGeometryType(k.geometryType),B=this.spatialReference=new F(B);this.geometryType=k.geometryType;k.fields&&(this.fields=k.fields);f.forEach(t,function(f,b){var g=f.geometry&&f.geometry.spatialReference;t[b]=new K(z&&f.geometry?new z(f.geometry):null,f.symbol&&J.fromJson(f.symbol),f.attributes);t[b].geometry&&!g&&t[b].geometry.setSpatialReference(B)})}else this.features=
[]},displayFieldName:null,geometryType:null,spatialReference:null,fieldAliases:null,toJson:function(f){var k={};this.displayFieldName&&(k.displayFieldName=this.displayFieldName);this.fields&&(k.fields=this.fields);this.spatialReference?k.spatialReference=this.spatialReference.toJson():this.features[0]&&this.features[0].geometry&&(k.spatialReference=this.features[0].geometry.spatialReference.toJson());this.features[0]&&(this.features[0].geometry&&(k.geometryType=v.getJsonType(this.features[0].geometry)),
k.features=I._encodeGraphics(this.features,f));k.exceededTransferLimit=this.exceededTransferLimit;return G.fixJson(k)}});B("extend-esri")&&n.setObject("tasks.FeatureSet",k,H);return k})},"esri/PopupInfo":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/json dojo/i18n dojo/has dojo/Deferred dojo/sniff dojo/promise/all ./lang ./kernel ./request ./tasks/query ./tasks/QueryTask ./tasks/StatisticDefinition dojo/i18n!dojo/cldr/nls/number".split(" "),function(k,n,f,B,H,G,
K,F,I,v,J,D,t,L,z,u){k=k(null,{declaredClass:"esri.PopupInfo",initialize:function(b,g){if(b){n.mixin(this,g);this.info=b;this.title=this.getTitle;this.content=this.getContent;var p=this._fieldLabels={},e=this._fieldsMap={};b.fieldInfos&&f.forEach(b.fieldInfos,function(b){p[b.fieldName]=b.label;e[b.fieldName]=b});this._relatedFieldPrefix="relationships/";this.titleHasRelatedFields=!!(b.title&&-1!==b.title.indexOf("{"+this._relatedFieldPrefix))}},toJson:function(){return B.fromJson(B.toJson(this.info))},
getTitle:function(){},getContent:function(){},getComponents:function(b){var g=this.info,p=new K,e,c;g.fieldInfos&&(c=f.filter(g.fieldInfos,function(a){return-1!==a.fieldName.indexOf(this._relatedFieldPrefix)},this));c&&0<c.length&&(e=this._getRelatedRecords({graphic:b,fieldsInfo:c}));e?e.always(n.hitch(this,function(){p.resolve(this._getPopupValues(b))})):p.resolve(this._getPopupValues(b));return p.promise},_getPopupValues:function(b,g){var p=this.info,e=b.getLayer(),c=n.clone(b.attributes)||{},a=
n.clone(c),m=p.fieldInfos,d="",l="",k,h,r,C,t,u=e&&e._getDateOpts&&e._getDateOpts().properties,z={dateFormat:{properties:u,formatter:"DateFormat"+this._insertOffset(this._dateFormats.shortDateShortTime)}};if(this._relatedInfo)for(C in this._relatedInfo)if(this._relatedInfo.hasOwnProperty(C)){var B=this._relatedInfo[C],D=this._relatedLayersInfo[C];B&&(f.forEach(B.relatedFeatures,function(d){for(t in d.attributes)if(d.attributes.hasOwnProperty(t)&&"esriRelCardinalityOneToOne"===D.relation.cardinality){var b=
this._toRelatedFieldName([D.relation.id,t]);c[b]=a[b]=d.attributes[t]}},this),f.forEach(B.relatedStatsFeatures,function(d){for(t in d.attributes)if(d.attributes.hasOwnProperty(t)){var b=this._toRelatedFieldName([D.relation.id,t]);c[b]=a[b]=d.attributes[t]}},this))}m&&f.forEach(m,function(d){h=d.fieldName;a[h]=this._formatValue(a[h],h,z);u&&(d.format&&d.format.dateFormat)&&(d=f.indexOf(u,h),-1<d&&u.splice(d,1))},this);if(e){C=e.types;var x=(B=e.typeIdField)&&c[B];for(h in c)if(c.hasOwnProperty(h)&&
-1===h.indexOf(this._relatedFieldPrefix)&&(r=c[h],v.isDefined(r))){var s=this._getDomainName(e,C,x,h,r);v.isDefined(s)?a[h]=s:h===B&&(s=this._getTypeName(e,r),v.isDefined(s)&&(a[h]=s))}}p.title&&(d=this._processFieldsInLinks(this._fixTokens(p.title),c),d=n.trim(v.substitute(a,d,z)||""));if(g)return{title:d};p.description&&(l=this._processFieldsInLinks(this._fixTokens(p.description),c),l=n.trim(v.substitute(a,l,z)||""));m&&(k=[],f.forEach(m,function(d){(h=d.fieldName)&&d.visible&&k.push([d.label||
h,v.substitute(a,"${"+h+"}",z)||""])}));var w,y;p.mediaInfos&&(w=[],f.forEach(p.mediaInfos,function(d){y=0;r=d.value;switch(d.type){case "image":var b=r.sourceURL,b=b&&n.trim(v.substitute(c,this._fixTokens(b)));y=!!b;break;case "piechart":case "linechart":case "columnchart":case "barchart":y=f.some(r.fields,function(a){return v.isDefined(c[a])||-1!==a.indexOf(this._relatedFieldPrefix)&&this._relatedInfo},this);break;default:return}if(y){d=n.clone(d);r=d.value;var b=d.title?this._processFieldsInLinks(this._fixTokens(d.title),
c):"",l=d.caption?this._processFieldsInLinks(this._fixTokens(d.caption),c):"";d.title=b?n.trim(v.substitute(a,b,z)||""):"";d.caption=l?n.trim(v.substitute(a,l,z)||""):"";if("image"===d.type)r.sourceURL=v.substitute(c,this._fixTokens(r.sourceURL)),r.linkURL&&(r.linkURL=n.trim(v.substitute(c,this._fixTokens(r.linkURL))||""));else{var m,h;f.forEach(r.fields,function(a,d){if(-1!==a.indexOf(this._relatedFieldPrefix))h=this._getRelatedChartInfos(a,r,c,z),h instanceof Array?r.fields=h:r.fields[d]=h;else{var b=
c[a],b=void 0===b?null:b;m=c[r.normalizeField]||0;b&&m&&(b/=m);r.fields[d]={y:b,tooltip:(this._fieldLabels[a]||a)+":\x3cbr/\x3e"+this._formatValue(b,a,z,!!m)}}},this)}w.push(d)}},this));return{title:d,description:l,fields:k&&k.length?k:null,mediaInfos:w&&w.length?w:null,formatted:a,editSummary:e&&e.getEditSummary?e.getEditSummary(b):""}},_getRelatedChartInfos:function(b,g,p,e){var c,a,m,d,l,k;c=[];k=this._fromRelatedFieldName(b);l=k[0];a=this._relatedInfo[l];l=this._relatedLayersInfo[l];a&&f.forEach(a.relatedFeatures,
function(a){a=a.attributes;var l,f;for(f in a)if(a.hasOwnProperty(f)&&f===k[1]){l={};d=a[f];g.normalizeField&&(m=-1!==g.normalizeField.indexOf(this._relatedFieldPrefix)?a[this._fromRelatedFieldName(g.normalizeField)[1]]:p[g.normalizeField]);d&&m&&(d/=m);if(g.tooltipField)if(-1!==g.tooltipField.indexOf(this._relatedFieldPrefix)){var n=this._fromRelatedFieldName(g.tooltipField)[1];l.tooltip=a[n]+":\x3cbr/\x3e"+this._formatValue(d,a[n],e,!!m)}else l.tooltip=(this._fieldLabels[b]||b)+":\x3cbr/\x3e"+this._formatValue(d,
g.tooltipField,e,!!m);else l.tooltip=d;l.y=d;c.push(l)}},this);return"esriRelCardinalityOneToMany"===l.relation.cardinality||"esriRelCardinalityManyToMany"===l.relation.cardinality?c:c[0]},getAttachments:function(b){var g=b.getLayer();b=b.attributes;if(this.info.showAttachments&&(g&&g.hasAttachments&&g.objectIdField)&&(b=b&&b[g.objectIdField]))return g.queryAttachmentInfos(b)},_dateFormats:{shortDate:"(datePattern: 'M/d/y', selector: 'date')",shortDateLE:"(datePattern: 'd/M/y', selector: 'date')",
longMonthDayYear:"(datePattern: 'MMMM d, y', selector: 'date')",dayShortMonthYear:"(datePattern: 'd MMM y', selector: 'date')",longDate:"(datePattern: 'EEEE, MMMM d, y', selector: 'date')",shortDateShortTime:"(datePattern: 'M/d/y', timePattern: 'h:mm a', selector: 'date and time')",shortDateLEShortTime:"(datePattern: 'd/M/y', timePattern: 'h:mm a', selector: 'date and time')",shortDateShortTime24:"(datePattern: 'M/d/y', timePattern: 'H:mm', selector: 'date and time')",shortDateLEShortTime24:"(datePattern: 'd/M/y', timePattern: 'H:mm', selector: 'date and time')",
shortDateLongTime:"(datePattern: 'M/d/y', timePattern: 'h:mm:ss a', selector: 'date and time')",shortDateLELongTime:"(datePattern: 'd/M/y', timePattern: 'h:mm:ss a', selector: 'date and time')",shortDateLongTime24:"(datePattern: 'M/d/y', timePattern: 'H:mm:ss', selector: 'date and time')",shortDateLELongTime24:"(datePattern: 'd/M/y', timePattern: 'H:mm:ss', selector: 'date and time')",longMonthYear:"(datePattern: 'MMMM y', selector: 'date')",shortMonthYear:"(datePattern: 'MMM y', selector: 'date')",
year:"(datePattern: 'y', selector: 'date')"},_reHref:/href\s*=\s*\"[^\"]+\"/ig,_fixTokens:function(b){return b.replace(/(\{[^\{\r\n]+\})/g,"$$$1")},_processFieldsInLinks:function(b,g){return b&&b.replace(this._reHref,function(b){return b=v.substitute(g,b)})},_formatValue:function(b,g,k,e){var c=this._fieldsMap[g],a=c&&c.format;g="number"===typeof b&&-1===f.indexOf(k.dateFormat.properties,g)&&(!a||!a.dateFormat);if(!v.isDefined(b)||!c||!v.isDefined(a))return g?this._forceLTR(b):b;var m="",d=[],c=a.hasOwnProperty("places")||
a.hasOwnProperty("digitSeparator"),l=a.hasOwnProperty("digitSeparator")?a.digitSeparator:!0;if(c)m="NumberFormat",d.push("places: "+(v.isDefined(a.places)&&(!e||0<a.places)?Number(a.places):"Infinity")),d.length&&(m+="("+d.join(",")+")");else if(a.dateFormat)m="DateFormat"+this._insertOffset(this._dateFormats[a.dateFormat]||this._dateFormats.shortDateShortTime);else return g?this._forceLTR(b):b;b=v.substitute({myKey:b},"${myKey:"+m+"}",k)||"";c&&!l&&u.group&&(b=b.replace(RegExp("\\"+u.group,"g"),
""));return g?this._forceLTR(b):b},_forceLTR:function(b){var g=F("ie");return g&&10>=g?b:"\x3cspan class\x3d'esriNumericValue'\x3e"+b+"\x3c/span\x3e"},_insertOffset:function(b){b&&(b=v.isDefined(this.utcOffset)?b.replace(/\)\s*$/,", utcOffset:"+this.utcOffset+")"):b);return b},_getDomainName:function(b,g,k,e,c){var a,m;g&&v.isDefined(k)&&f.some(g,function(d){if(d.id==k){if((a=d.domains&&d.domains[e])&&"inherited"===a.type)a=this._getLayerDomain(b,e),m=!0;return!0}return!1},this);!m&&!a&&(a=this._getLayerDomain(b,
e));if(a&&a.codedValues){var d;f.some(a.codedValues,function(a){return a.code==c?(d=a.name,!0):!1});return d}},_getLayerDomain:function(b,g){var k=b.fields;if(k){var e;f.some(k,function(b){return b.name===g?(e=b.domain,!0):!1});return e}},_getTypeName:function(b,g){var k=b.types;if(k){var e;f.some(k,function(b){return b.id==g?(e=b.name,!0):!1});return e}},_getRelatedRecords:function(b){var g=b.graphic,f=new K,e;this._relatedLayersInfo?this._queryRelatedLayers(g).then(n.hitch(this,function(b){this._setRelatedRecords(g,
b);f.resolve(b)}),n.hitch(this,this._handlerErrorResponse,f)):this._getRelatedLayersInfo(b).then(n.hitch(this,function(b){for(e in b)b.hasOwnProperty(e)&&b[e]&&(this._relatedLayersInfo[e].relatedLayerInfo=b[e]);this._queryRelatedLayers(g).then(n.hitch(this,function(a){this._setRelatedRecords(g,a);f.resolve(a)}),n.hitch(this,this._handlerErrorResponse,f))}),n.hitch(this,this._handlerErrorResponse,f));return f.promise},_getRelatedLayersInfo:function(b){var g=b.fieldsInfo,k,e,c={};k=b.graphic.getLayer();
this._relatedLayersInfo||(this._relatedLayersInfo={});f.forEach(g,function(a){var b,d,l,c;b=this._fromRelatedFieldName(a.fieldName);d=b[0];b=b[1];d&&(this._relatedLayersInfo[d]||(f.some(k.relationships,function(a){if(a.id==d)return c=a,!0}),c&&(this._relatedLayersInfo[d]={relation:c,relatedFields:[],outStatistics:[]})),this._relatedLayersInfo[d]&&(this._relatedLayersInfo[d].relatedFields.push(b),a.statisticType&&(l=new z,l.statisticType=a.statisticType,l.onStatisticField=b,l.outStatisticFieldName=
b,this._relatedLayersInfo[d].outStatistics.push(l))))},this);for(e in this._relatedLayersInfo)this._relatedLayersInfo.hasOwnProperty(e)&&this._relatedLayersInfo[e]&&(b=this._relatedLayersInfo[e].relation,b=k.url.replace(/[0-9]+$/,b.relatedTableId),this._relatedLayersInfo[e].relatedLayerUrl=b,c[e]=D({url:b,content:{f:"json"},callbackParamName:"callback"}));return I(c)},_queryRelatedLayers:function(b){var g={},f;for(f in this._relatedLayersInfo)this._relatedLayersInfo.hasOwnProperty(f)&&(g[f]=this._queryRelatedLayer({graphic:b,
relatedInfo:this._relatedLayersInfo[f]}));return I(g)},_queryRelatedLayer:function(b){var g,k,e,c,a,m,d,l,n,h;g=b.graphic;k=g.getLayer().url.match(/[0-9]+$/g)[0];l=b.relatedInfo;d=l.relatedLayerInfo;n=l.relatedLayerUrl;h=l.relation;f.some(d.relationships,function(a){if(a.relatedTableId===parseInt(k,10))return e=a,!0},this);e&&(b=new t,f.some(d.fields,function(d){if(d.name===e.keyField)return a=-1!==f.indexOf(["esriFieldTypeSmallInteger","esriFieldTypeInteger","esriFieldTypeSingle","esriFieldTypeDouble"],
d.type)?"number":"string",!0}),c="string"===a?e.keyField+"\x3d'"+g.attributes[h.keyField]+"'":e.keyField+"\x3d"+g.attributes[h.keyField],b.where=c,b.outFields=l.relatedFields,l.outStatistics&&(0<l.outStatistics.length&&d.supportsStatistics)&&(m=new t,m.where=b.where,m.outFields=b.outFields,m.outStatistics=l.outStatistics),g=new L(n),c=[],c.push(g.execute(b)),m&&c.push(g.execute(m)));return I(c)},_setRelatedRecords:function(b,f){this._relatedInfo=[];for(var k in f)if(f.hasOwnProperty(k)&&f[k]){var e=
f[k];this._relatedInfo[k]={};this._relatedInfo[k].relatedFeatures=e[0].features;v.isDefined(e[1])&&(this._relatedInfo[k].relatedStatsFeatures=e[1].features)}},_handlerErrorResponse:function(b,f){b.reject(f)},_fromRelatedFieldName:function(b){var f=[];-1!==b.indexOf(this._relatedFieldPrefix)&&(b=b.split("/"),f=b.slice(1));return f},_toRelatedFieldName:function(b){var f="";b&&0<b.length&&(f=this._relatedFieldPrefix+b[0]+"/"+b[1]);return f}});G("extend-esri")&&(J.PopupInfo=J.PopupInfoTemplate=k);return k})},
"*noref":1}});
define("esri/layers/LabelLayer","require dojo/_base/declare dojo/_base/lang dojo/number dojo/_base/array dojo/_base/connect dojo/has dojox/gfx/_base ../kernel ../lang ../graphic ../PopupInfo ./labelLayerUtils/DynamicLabelClass ./labelLayerUtils/StaticLabelClass ../symbols/TextSymbol ../symbols/ShieldLabelSymbol ../geometry/Extent ../geometry/Point ./GraphicsLayer ./LabelClass ../renderers/SimpleRenderer".split(" "),function(k,n,f,B,H,G,K,F,I,v,J,D,t,L,z,u,b,g,p,e,c){k=n(p,{declaredClass:"esri.layers.LabelLayer",constructor:function(a){this.id=
"labels";this.featureLayers=[];this._featureLayerInfos=[];this._preparedLabels=[];this._engineType="STATIC";this._mapEventHandlers=[];a&&(a.id&&(this.id=a.id),a.mode&&(this._engineType="DYNAMIC"===a.mode.toUpperCase()?"DYNAMIC":"STATIC"))},_setMap:function(a){var b=this.inherited(arguments);this._map&&this._mapEventHandlers.push(this._map.on("extent-change",f.hitch(this,"refresh")));this.refresh();return b},_unsetMap:function(){var a;for(a=0;a<this._mapEventHandlers.length;a++)G.disconnect(this._mapEventHandlers[a]);
this.refresh();this.inherited(arguments)},setAlgorithmType:function(a){this._engineType=a&&"DYNAMIC"===a.toUpperCase()?"DYNAMIC":"STATIC";this.refresh()},addFeatureLayer:function(a,b,d,l){if(!this.getFeatureLayer(a.layerId)){var c=[];c.push(a.on("update-end",f.hitch(this,"refresh")));c.push(a.on("suspend",f.hitch(this,"refresh")));c.push(a.on("resume",f.hitch(this,"refresh")));c.push(a.on("edits-complete",f.hitch(this,"refresh")));c.push(a.on("labeling-info-change",f.hitch(this,"refresh")));c.push(a.on("time-extent-change",
f.hitch(this,"refresh")));c.push(a.on("show-labels-change",f.hitch(this,"refresh")));this._featureLayerInfos.push({FeatureLayer:a,LabelExpressionInfo:d,LabelingOptions:l,LabelRenderer:b,EventHandlers:c});this.featureLayers.push(a);this.refresh()}},getFeatureLayer:function(a){var b,d;for(b=0;b<this.featureLayers.length;b++)if(d=this.featureLayers[b],void 0!==d&&d.id==a)return d;return null},removeFeatureLayer:function(a){var b;a=this.getFeatureLayer(a);if(void 0!==a&&(b=H.indexOf(this.featureLayers,
a),-1<b)){this.featureLayers.splice(b,1);for(a=0;a<this._featureLayerInfos[b].EventHandlers.length;a++)G.disconnect(this._featureLayerInfos[b].EventHandlers[a]);this._featureLayerInfos.splice(b,1);this.refresh()}},removeAllFeatureLayers:function(){var a;for(a=0;a<this.featureLayers.length;a++){for(var b=0;b<this._featureLayerInfos[a].EventHandlers.length;b++)G.disconnect(this._featureLayerInfos[a].EventHandlers[b]);this.featureLayers=[];this._featureLayerInfos=[]}this.refresh()},getFeatureLayers:function(){return this.featureLayers},
getFeatureLayerInfo:function(a){var b,d;for(b=0;b<this.featureLayers.length;b++)if(d=this.featureLayers[b],void 0!==d&&d.id==a)return this._featureLayerInfos[b];return null},refresh:function(a){var b,d,l,f,h,g=[],k="DYNAMIC"===this._engineType?new t:new L;if(this._map){k.setMap(this._map,this);this._preparedLabels=[];for(a=0;a<this.featureLayers.length;a++)if(d=this.featureLayers[a],d.visible&&d.showLabels&&d.visibleAtMapScale&&!d._suspended)if(b=this._featureLayerInfos[a],b.LabelRenderer){if(g=d.labelingInfo)if(h=
g[0])f=this._getLabelExpression(h),this._convertOptions(h);l=b.LabelRenderer;b.LabelExpressionInfo&&(f=b.LabelExpressionInfo);h=this._convertOptions(null);b.LabelingOptions&&(void 0!==b.LabelingOptions.lineLabelPlacement&&(h.lineLabelPlacement=b.LabelingOptions.lineLabelPlacement),void 0!==b.LabelingOptions.lineLabelPosition&&(h.lineLabelPosition=b.LabelingOptions.lineLabelPosition),void 0!==b.LabelingOptions.labelRotation&&(h.labelRotation=b.LabelingOptions.labelRotation));l instanceof e&&(f=this._getLabelExpression(l),
l=new c(l.symbol),h=this._convertOptions(l));this._addLabels(d,l,f,h)}else if(g=d.labelingInfo)for(b=g.length-1;0<=b;b--)if(h=g[b])l=new e(h instanceof e?h.toJson():h),f=this._getLabelExpression(h),h=this._convertOptions(h),this._addLabels(d,l,f,h);f=k._process(this._preparedLabels);this.clear();this.drawLabels(this._map,f)}},drawLabels:function(a,b){this._scale=(a.extent.xmax-a.extent.xmin)/a.width;var d;for(d=0;d<b.length;d++){var l=b[d],c=l.x,h=l.y,f=l.text,e=l.angle,k=l.layer.labelSymbol;"polyline"==
l.layer.geometry.type&&l.layer.options.labelRotation?k.setAngle(e*(180/Math.PI)):k.setAngle(0);k.setText(f);l=c;k instanceof z&&(c=k.getHeight(),e=Math.sin(e),l-=0.25*c*this._scale*e,h-=0.33*c*this._scale);e=new J(new g(l,h,a.extent.spatialReference));e.setSymbol(k);this.add(e)}},_addLabels:function(a,b,d,l){var c,e,f,g;if(this._isWithinScaleRange(b.minScale,b.maxScale)&&d&&""!==d)for(c=0;c<a.graphics.length;c++)e=a.graphics[c],!1!==e.visible&&(f=e.geometry,this._isWhere(b.where,e.attributes)&&this._isWithinScreenArea(f)&&
(g=this._buildLabelText(d,e.attributes,a.fields,l),this._addLabel(g,b,a.renderer,e,l,f)))},_isWithinScreenArea:function(a){a="point"===a.type?new b(a.x,a.y,a.x,a.y,a.spatialReference):a.getExtent();a=this._intersects(this._map,a);return null===a||0===a.length?!1:!0},_isWithinScaleRange:function(a,b){var d=this._map.getScale();return 0<a&&d>=a||0<b&&d<=b?!1:!0},_isWhere:function(a,b){try{if(!a)return!0;if(a){var d=a.split(" ");if(3===d.length)return this._sqlEquation(b[d[0].substr(1,d[0].length-2)],
d[1],d[2]);if(7===d.length){var c=this._sqlEquation(b[d[0].substr(1,d[0].length-2)],d[1],d[2]),e=d[3],f=this._sqlEquation(b[d[4].substr(1,d[4].length-2)],d[5],d[6]);switch(e){case "AND":return c&&f;case "OR":return c||f}}}return!1}catch(g){console.log("Error.: can't parse \x3d "+a)}},_sqlEquation:function(a,b,d){switch(b){case "\x3d":return a==d?!0:!1;case "\x3c\x3e":return a!=d?!0:!1;case "\x3e":return a>d?!0:!1;case "\x3e\x3d":return a>=d?!0:!1;case "\x3c":return a<d?!0:!1;case "\x3c\x3d":return a<=
d?!0:!1}return!1},_addLabel:function(a,b,d,c,e,h){var g,k,n,p;if(a&&""!==f.trim(a)&&b){g=b.getSymbol(c);g instanceof z?(g=new z(g.toJson()),g.setVerticalAlignment("baseline"),g.setHorizontalAlignment("center")):g=g instanceof u?new u(g.toJson()):new z;g.setText(a);b.symbol=g;if(k=this._getProportionalSize(b.sizeInfo,c.attributes))g instanceof z?g.setSize(k):g instanceof u&&(g.setWidth(k),g.setHeight(k));n=k=0;if(d)if(p=d.getSize(c),d=d.getSymbol(c),0!==p)n=k=p;else if(d)if("simplemarkersymbol"==d.type)n=
k=d.size;else if("picturemarkersymbol"==d.type)k=d.width,n=d.height;else if("simplelinesymbol"==d.type||"cartographiclinesymbol"==d.type)k=d.width;d={};d.graphic=c;d.options=e;d.geometry=h;d.labelRenderer=b;d.labelSymbol=g;d.labelWidth=g.getWidth()/2;d.labelHeight=g.getHeight()/2;d.symbolWidth=F.normalizedLength(k)/2;d.symbolHeight=F.normalizedLength(n)/2;d.text=a;d.angle=g.angle;this._preparedLabels.push(d)}},_buildLabelText:function(a,b,d,c){return a.replace(/{[^}]*}/g,function(a){var e,g=a;for(e=
0;e<d.length;e++)if("{"+d[e].name+"}"==a){var g=b[d[e].name],k=d[e].domain;if(k&&f.isObject(k)){if("codedValue"==k.type)for(a=0;a<k.codedValues.length;a++)k.codedValues[a].code==g&&(g=k.codedValues[a].name);else"range"==k.type&&(k.minValue<=g&&g<=k.maxValue)&&(g=k.name);break}k=d[e].type;if("esriFieldTypeDate"==k)(k="DateFormat"+D.prototype._dateFormats[c&&c.dateFormat||"shortDate"])&&(g=v.substitute({myKey:g},"${myKey:"+k+"}"));else if("esriFieldTypeInteger"==k||"esriFieldTypeSmallInteger"==k||"esriFieldTypeLong"==
k||"esriFieldTypeDouble"==k)c&&(c.numberFormat&&c.numberFormat.digitSeparator&&c.numberFormat.places)&&(g=B.format(g,{places:c.numberFormat.places}))}return g})},_getLabelExpression:function(a){return a.labelExpressionInfo?a.labelExpressionInfo.value:this._validSyntax(a.labelExpression)?this._convertLabelExpression(a.labelExpression):""},_validSyntax:function(a){return/^(\s*\[[^\]]+\]\s*)+$/i.test(a)},_convertLabelExpression:function(a){return a.replace(RegExp("\\[","g"),"{").replace(RegExp("\\]",
"g"),"}")},_getProportionalSize:function(a,b){if(!a)return null;var d=v.substitute(b,"${"+a.field+"}",{first:!0});return!a.minSize||!a.maxSize||!a.minDataValue||!a.maxDataValue||!d||0>=a.maxDataValue-a.minDataValue?null:(a.maxSize-a.minSize)/(a.maxDataValue-a.minDataValue)*(d-a.minDataValue)+a.minSize},_convertOptions:function(a){var b="shortDate",d=null,c="",e=!0;a&&(b=a.dateFormat,d=a.numberFormat,c=a.labelPlacement);if("always-horizontal"==c||"esriServerPolygonPlacementAlwaysHorizontal"==c)e=!1;
return{dateFormat:b,numberFormat:d,pointPriorities:"above-center"==c||"esriServerPointLabelPlacementAboveCenter"==c?"AboveCenter":"above-left"==c||"esriServerPointLabelPlacementAboveLeft"==c?"AboveLeft":"above-right"==c||"esriServerPointLabelPlacementAboveRight"==c?"AboveRight":"below-center"==c||"esriServerPointLabelPlacementBelowCenter"==c?"BelowCenter":"below-left"==c||"esriServerPointLabelPlacementBelowLeft"==c?"BelowLeft":"below-right"==c||"esriServerPointLabelPlacementBelowRight"==c?"BelowRight":
"center-center"==c||"esriServerPointLabelPlacementCenterCenter"==c?"CenterCenter":"center-left"==c||"esriServerPointLabelPlacementCenterLeft"==c?"CenterLeft":"center-right"==c||"esriServerPointLabelPlacementCenterRight"==c?"CenterRight":"AboveRight",lineLabelPlacement:"above-start"==c||"below-start"==c||"center-start"==c?"PlaceAtStart":"above-end"==c||"below-end"==c||"center-end"==c?"PlaceAtEnd":"PlaceAtCenter",lineLabelPosition:"above-after"==c||"esriServerLinePlacementAboveAfter"==c||"above-along"==
c||"esriServerLinePlacementAboveAlong"==c||"above-before"==c||"esriServerLinePlacementAboveBefore"==c||"above-start"==c||"esriServerLinePlacementAboveStart"==c||"above-end"==c||"esriServerLinePlacementAboveEnd"==c?"Above":"below-after"==c||"esriServerLinePlacementBelowAfter"==c||"below-along"==c||"esriServerLinePlacementBelowAlong"==c||"below-before"==c||"esriServerLinePlacementBelowBefore"==c||"below-start"==c||"esriServerLinePlacementBelowStart"==c||"below-end"==c||"esriServerLinePlacementBelowEnd"==
c?"Below":"center-after"==c||"esriServerLinePlacementCenterAfter"==c||"center-along"==c||"esriServerLinePlacementCenterAlong"==c||"center-before"==c||"esriServerLinePlacementCenterBefore"==c||"center-start"==c||"esriServerLinePlacementCenterStart"==c||"center-end"==c||"esriServerLinePlacementCenterEnd"==c?"OnLine":"Above",labelRotation:e,howManyLabels:"OneLabel"}}});K("extend-esri")&&f.setObject("layers.LabelLayer",k,I);return k});