// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.11/esri/copyright.txt for details.
//>>built
require({cache:{"esri/layers/StreamTrackManager":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/has ../kernel ../graphic ../geometry/Polyline ./GraphicsLayer ./TrackManager".split(" "),function(d,v,k,s,t,x,y,A,z){d=d([z],{declaredClass:"esri.layers._StreamTrackManager",constructor:function(k){this.inherited(arguments)},initialize:function(k){this.inherited(arguments)},addFeatures:function(d,n){function p(a,c){var b,e,l,w;m[a]||(m[a]=[]);b=m[a];0<h&&(c.length>h&&c.splice(0,
c.length-h),l=c.length+b.length,l>h&&(e=b.splice(0,l-h)));l=c.length;for(w=0;w<l;w+=1)b.push(c[w]);return{deletes:e,adds:c}}var m,f,r,h,q={},g={},u;if(n)return this.inherited(arguments),q;m=this.trackMap;f=this.layer;r=f._trackIdField;h=f.maximumTrackPoints||0;k.forEach(d,function(a){var c=a.attributes[r];a.visible&&(g[c]||(g[c]=[]),g[c].push(a))});for(u in g)g.hasOwnProperty(u)&&(f=p(u,g[u]),q[u]=f);return q},removeFeatures:function(d){var n=[],p=this.layer.objectIdField,m=this.layer._trackIdField;
d&&(k.forEach(d,function(f){var d,h,q,g;h=f.attributes[m];d=f.attributes[p];if(q=this.trackMap[h])for(f=0;f<q.length;f+=1)if(g=q[f],g.attributes[p]===d){this.trackMap[h].splice(f,1);-1===k.indexOf(h)&&n.push(h);break}},this),0<d.length&&this.refreshTracks(n))},drawTracks:function(d){function n(g){var d=f[g],a=d&&1<d.length,c,b,e;if((e=p.trackLineMap[g])&&!a)m.remove(e),delete p.trackLineMap[g],e=null;if(!a)return!1;a=[];for(c=d.length-1;0<=c;c-=1)(b=d[c].geometry)&&a.push([b.x,b.y]);d={};d[h]=g;1<
a.length&&(e?(g=e.geometry,g.removePath(0),g.addPath(a),e.setGeometry(g)):(e=new x(new y({paths:[a],spatialReference:r}),null,d),m.add(e),p.trackLineMap[g]=e))}var p=this,m=this.container,f,r,h,q;if(m)if(f=this.trackMap,r=this.map.spatialReference,h=this.layer._trackIdField,d)k.forEach(d,function(d){n(d)});else for(q in f)f.hasOwnProperty(q)&&n(q)},refreshTracks:function(d){function n(d){var f,g;d=p[d]||[];f=d.length;for(g=0;g<f;g++)m._repaint(d[g],null,!0)}var p=this.trackMap,m=this.layer,f=m._getRenderer(),
r;this.drawTracks(d);if(f&&f.latestObservationRenderer)if(d)k.forEach(d,function(d){n(d)});else for(r in p)p.hasOwnProperty(r)&&n(r)},destroy:function(){this.inherited(arguments);this.trackLineMap=null}});s("extend-esri")&&v.setObject("layers._StreamTrackManager",d,t);return d})},"esri/layers/PurgeOptions":function(){define(["dojo/_base/declare","dojo/_base/lang","dojo/Stateful","dojo/has","../kernel"],function(d,v,k,s,t){d=d([k],{declaredClass:"esri.layers.PurgeOptions",constructor:function(d,k){this.parent=
d;for(var s in k)this[s]=k[s]},_displayCountSetter:function(d){this.displayCount=d;this.parent.refresh()}});s("extend-esri")&&v.setObject("layers.PurgeOptions",d,t);return d})},"*noref":1}});
define("esri/layers/StreamLayer","dojo/_base/declare dojo/_base/connect dojo/_base/array dojo/_base/Color dojo/_base/lang dojo/has dojo/on ../kernel ../request ../graphic ./FeatureLayer ./StreamMode ./StreamTrackManager ../geometry/jsonUtils ../symbols/SimpleFillSymbol ../symbols/SimpleLineSymbol ../symbols/SimpleMarkerSymbol ../renderers/SimpleRenderer ./PurgeOptions".split(" "),function(d,v,k,s,t,x,y,A,z,B,n,p,m,f,r,h,q,g,u){d=d([n],{declaredClass:"esri.layers.StreamLayer",constructor:function(a,
c){c=c||{};if(!c.mode||c.mode===n.MODE_STREAM)this._isStream=!0,this.mode=n.MODE_STREAM,this._mode=new p(this);this.purgeOptions=new u(this,c.purgeOptions||{});this._reconnectAttempts=0;this.maxReconnectAttempts=3;this.socket=null;this._keepLatestQueried=!1;this._keepLatestUrl=null;this._relatedQueried=!1;this._joinField=this._relatedUrl=null;this._attemptReconnect=t.hitch(this,this._attemptReconnect);this._purge=t.hitch(this,this._purge)},_initLayer:function(a,c){this.inherited(arguments);if(a){var b;
if(a.layerDefinition)this.purgeOptions=new u(this,this._params.purgeOptions||{}),this.socketUrl=this._params.socketUrl||a.layerDefinition.socketUrl||void 0;else{if(this._params.socketUrl)this.socketUrl=this._params.socketUrl;else{var e=this._getWebsocketConnectionInfo(a),l=e.urls;l&&l.length?(this._socketUrls=l,this.socketUrl=l[0],this.socketDirection="broadcast"===this._params.socketDirection?"broadcast":"subscribe",this.socketUrl+="/"+this.socketDirection,this._websocketToken=e.token,l.length>this.maxReconnectAttempts&&
(this.maxReconnectAttempts=l.length)):(this.socketUrl=void 0,e="No web socket urls were retrieved from the Stream Service. Layer will not attempt to connect.","https:"===location.protocol&&(e+=" An insecure web socket connection cannot be made from a secure web page."),this.onError(Error(e)))}if(this._params.filter)try{this._filter=b=this._makeFilter(this._params.filter)}catch(d){this.onError(Error("Error trying to create filter object: "+d+". Layer will not have filter applied")),this._filter=null}if(this._params.geometryDefinition||
this._outFields||this._defnExpr){b=b||{};b.geometry=this._params.geometryDefinition;b.outFields=this._outFields;b.where=this._defnExpr;try{this._filter=b=this._makeFilter(b)}catch(f){this.onError(Error("Error trying to create filter object: "+f+". Layer will not have filter applied")),this._filter=null}}}this.maximumTrackPoints=this._params.maximumTrackPoints&&0<this._params.maximumTrackPoints?this._params.maximumTrackPoints:0;(this._params.refreshRate||0===this._params.refreshRate)&&this._mode&&
this._mode._setRefreshRate&&this._mode._setRefreshRate(this._params.refreshRate);this._keepLatestUrl=a.keepLatestArchive?a.keepLatestArchive.featuresUrl:null;a.relatedFeatures&&(a.relatedFeatures.featuresUrl&&a.relatedFeatures.joinField)&&(this._relatedUrl=a.relatedFeatures.featuresUrl,this.objectIdField=this._joinField=a.relatedFeatures.joinField);this.objectIdField||this._makeObjectIdField();this._map&&(this.socketUrl&&!this._connected)&&this.connect()}},_setMap:function(a){var c=this.inherited(arguments),
b=this._getRenderer();if(this.timeInfo&&(this._trackIdField||b&&(b.latestObservationRenderer||b.trackRenderer)))this._trackManager=new m(this),this._trackManager.initialize(a);this.socketUrl&&(!this._connected&&this._map)&&this.connect();return c},_unsetMap:function(a,c){k.forEach(this._connects,v.disconnect);this._connected&&this.disconnect();this.inherited(arguments);this._map=null},add:function(a){this.inherited(arguments)},clear:function(){try{this._mode&&this._mode._clearDrawBuffer&&this._mode._clearDrawBuffer(),
this._trackManager&&this._trackManager.clearTracks()}catch(a){}this.inherited(arguments)},setDefinitionExpression:function(a){this.setFilter({where:a})},getDefinitionExpression:function(){var a;this._filter&&(a=this._filter.where);return a},destroy:function(){this.disconnect();this.inherited(arguments)},onResume:function(a){this.inherited(arguments)},setGeometryDefinition:function(a){this.setFilter({geometry:a})},getGeometryDefinition:function(){var a;this._filter&&(a=this._filter.geometry);return a},
connect:function(a){var c=this,b,e=[],l=this._filter,d,f,g=this.socketUrl,h;try{if(!this._connected){if(this._relatedUrl&&!this._relatedQueried&&this._mode._fetchArchive)return b=this.on("update-end",function(){c._relatedQueried=!0;b.remove();b=null;c.connect()}),this._mode._fetchArchive(this._relatedUrl),!1;if(this._keepLatestUrl&&!this._keepLatestQueried&&this._mode._fetchArchive)return b=this.on("update-end",function(){c._keepLatestQueried=!0;b.remove();b=null;c.connect()}),this._mode._fetchArchive(this._keepLatestUrl),
!1;this._websocketToken&&e.push("token\x3d"+this._websocketToken);this._map&&this._map.spatialReference&&this.spatialReference&&this._map.spatialReference.wkid!==this.spatialReference.wkid&&e.push("outSR\x3d"+this._map.spatialReference.wkid);if(l)for(f in l)null!==l[f]&&(d="geometry"===f?JSON.stringify(l[f]):l[f],e.push(f+"\x3d"+d));0<e.length&&(g+="?"+e.join("\x26"));return h=this._createConnection(g,a)}}catch(k){console.log("Error connecting to data stream: ",k),a&&a(k,!1),this.onConnectionError({error:k})}},
disconnect:function(a){this._reconnecting=this._connected=!1;this.socket.close();this.onDisconnect({willReconnect:!1,message:"Connection closed from client"});a&&a(null,!0)},setFilter:function(a){var c,b;if(this._collection)return this.onError("Filter can only be set when the source of the layer is a Stream Service"),!1;try{if(void 0!==a.outFields)return b=Error("Outfields property cannot be changed after layer is created"),this.onFilterChange({filter:this.getFilter(),error:b}),!1;c=this._makeFilter(a)}catch(e){return b=
Error(e),this.onFilterChange({filter:this.getFilter(),error:b}),!1}if(this.socket)a={filter:c},this.socket.send(JSON.stringify(a));else y.once(this,"connect",function(a){this.setFilter(c)});return!0},getFilter:function(){var a=this._filter,c={},b=["geometry","outFields","where"];a&&k.forEach(b,function(b){var l=a[b];l&&("geometry"===b?l=f.fromJson(l):"outFields"===b&&(l=l.split(",")),c[b]=l)});return c},setMaximumTrackPoints:function(a){if(!a&&0!==a)return!1;this.maximumTrackPoints=a;this._mode.propertyChangeHandler(3)},
onMessage:function(){},onConnect:function(){},onDisconnect:function(){},onFilterChange:function(){},onAttemptReconnect:function(){},onConnectionError:function(){},_createConnection:function(a,c){var b=this,e=new WebSocket(a);e.onopen=function(){b.socket=e;b._connected=!0;b._reconnecting=!1;b._reconnectAttempts=0;b._bind();b.onConnect();c&&c(null,!0)};e.onclose=function(a){var c,e=!0,d=b._connected,f=null;if(b._connected||b._reconnecting||!b.socket){if(a.code)if(c="Connection failed: ",4400===a.code)c+=
a.reason||"Invalid url parameters. Check filter properties.",e=!1;else if(4404===a.code)c+="Service not found",e=!1;else if(4401===a.code||4403===a.code)c+="Not authorized",e=!1;e&&(b._reconnectAttempts+=1,b._reconnectAttempts>b.maxReconnectAttempts&&(c="Maximum reconnect attempts exceeded",e=!1));b._connected=!1;d&&(c&&(f=Error(c)),b.onDisconnect({error:f,willReconnect:e}));e?b._attemptReconnect():b.socket=null}else b.socket=null,b._connected=!1};e.onerror=function(a){console.log("Socket error")};
return e},_purge:function(){var a,c=[],b;if(this.purgeOptions.displayCount&&this.graphics.length>this.purgeOptions.displayCount)for(a=0;a<this.graphics.length-this.purgeOptions.displayCount;a++)b=this.graphics[a],c.push(b);0<c.length&&(this._mode._removeFeatures(c),this._trackManager&&this._trackManager.removeFeatures(c))},_bind:function(){var a=this;this.socket.onmessage=function(c){a._onMessage(JSON.parse(c.data))}},_onMessage:function(a){var c=this;this.onMessage(a);var b={create:function(a){c._create(a)},
update:function(a){c._update(a)},"delete":function(a){c._delete(a)}};if(a.type)b[a.type](a.feature);else a.hasOwnProperty("filter")?c._handleFilterMessage(a):this._create(a)},_create:function(a){function c(a){if(!b._featureHasOID(a,e)){if(!a.geometry)return!1;a.attributes=a.attributes||{};a.attributes[e]=b._nextId++}a=a.declaredClass?a:new B(a);b._mode.drawFeature(a)}var b=this,e=b.objectIdField;a.length?a.forEach(function(a){a&&c(a)}):a&&c(a)},_delete:function(a){var c=this,b=a[c.objectIdField]||
a.attributes[c.objectIdField],e=!1;this.graphics.forEach(function(a){a.attributes[c.objectIdField]==b&&(e=a)});e&&this.remove(e)},_update:function(a){var c=this,b=!1;this.graphics.forEach(function(e){e.attributes[c.objectIdField]==a.attributes[c.objectIdField]&&(b=e)});b&&(a.attributes&&b.setAttributes(a.attributes),a.geometry&&b.setGeometry(f.fromJson(a.geometry)))},_makeFilter:function(a){var c,b=null;a=a||{};if(void 0!==a.geometry)if(b=b||{},null===a.geometry)b.geometry=null;else{c="string"===
typeof a.geometry?f.fromJson(JSON.parse(a.geometry)):a.geometry.declaredClass?a.geometry:f.fromJson(a.geometry);if(!c||"point"===c.type)throw"Query object contains invalid geometry";"extent"!==c.type&&(c=c.getExtent());if(!c||0===c.getHeight()&&0===c.getWidth())throw"Invalid filter geometry: Extent cannot have a height and width of 0";b.spatialRel="esriSpatialRelIntersects";b.geometryType="esriGeometryEnvelope";b.geometry=c.toJson()}void 0!==a.where&&(b=b||{},b.where=a.where);if(void 0!==a.outFields&&
(b=b||{},a="string"===typeof a.outFields?"*"===a.outFields?null:a.outFields.replace(/,\s+/g,",").split(","):null===a.outFields?null:a.outFields,a=this._makeOutFields(a))){if(a.errors&&0<a.errors.length)throw"Invalid filter outFields. "+a.errors.join(",");b.outFields=a.fields?a.fields.join(","):null}return b},_makeOutFields:function(a){var c=this,b=[],e=[],d={fields:null};if(!a||0===a.length)return d;k.forEach(a,function(a){if("*"===a)return d;var f=c._getField(a,!0);f?b.push(f.name):e.push("Field named "+
a+" not found in schema.")});a=c._getOutFields();k.forEach(a,function(a){c._getField(a)&&-1===k.indexOf(b,a)&&b.push(a)});d.fields=b;d.errors=e;return d},_handleFilterMessage:function(a){a.error?(a=Error(a.error.join(",")),this.onFilterChange({filter:this.getFilter(),error:a})):(a=a.filter,a.geometry&&"string"===typeof a.geometry&&(a.geometry=JSON.parse(a.geometry)),this._filter=a,this.onFilterChange({filter:this.getFilter()}))},_getWebsocketConnectionInfo:function(a){var c={urls:[]},b,e=[],d=[],
f,g,h;a.streamUrls&&k.forEach(a.streamUrls,function(a){"ws"===a.transport&&(b=a.urls,c.token=a.token)});if(!b)return c;k.forEach(b,function(a){0===a.lastIndexOf("wss",0)?d.push(a):e.push(a)});a="https:"===location.protocol||0<d.length?d:e;if(1<a.length)for(f=0;f<a.length-1;f++)g=f+Math.floor(Math.random()*(a.length-f)),h=a[g],a[g]=a[f],a[f]=h;c.urls=a;return c},_attemptReconnect:function(){var a=this;a._connected=!1;if(!a._socketUrls)return!1;if(!a._collection&&!a._reconnecting&&a.socket&&a.credential)return a._reconnecting=
!0,a._getServiceConnectionMetadata(a._attemptReconnect),!1;a._reconnecting=!0;a.socket=null;if(a._reconnectAttempts>a.maxReconnectAttempts)return a._reconnecting=!1;a.socketUrl=a._socketUrls[a._reconnectAttempts>a._socketUrls.length-1?a._reconnectAttempts%a._socketUrls.length:a._reconnectAttempts];a.socketUrl+="/"+a.socketDirection;setTimeout(function(){a.onAttemptReconnect({count:a._reconnectAttempts,url:a.socketUrl});a.connect()},1E3)},_getServiceConnectionMetadata:function(a){var c=this,b=c._url.path;
a="function"===typeof a?a:null;z({url:b,content:t.mixin({f:"json"},this._url.query),callbackParamName:"callback"}).then(function(b){b=c._getWebsocketConnectionInfo(b);c._websocketToken=b.token;a&&a()},function(a){c.onError(Error(a))})},_setDefaultRenderer:function(){var a=this.geometryType,c=new s([5,112,176,0.8]),b=new s([255,255,255]),b=new h(h.STYLE_SOLID,b,1),d;if("esriGeometryPoint"===a||"esriGeometryMultipoint"===a)d=new q(q.STYLE_CIRCLE,10,b,c);else if("esriGeometryPolyline"===a)d=new h(h.STYLE_SOLID,
c,2);else if("esriGeometryPolygon"===a||"esriGeometryEnvelope"===a)c=new s([5,112,176,0.2]),b=new s([5,112,176,0.8]),b=new h(h.STYLE_SOLID,b,1),d=new r(r.STYLE_SOLID,b,c);d&&this.setRenderer(new g(d))},_makeObjectIdField:function(){var a=1,c,b,d=[];if(!this.objectIdField){c=this.fields.length;for(b=0;b<c;b++)d.push(this.fields[b].name.toLowerCase());for(;-1!==k.indexOf(d,"objectid_"+a);)a+=1;this.objectIdField="objectid_"+a}},_featureHasOID:function(a,c){return a.attributes&&(a.attributes[c]||0===
a.attributes[c])}});x("extend-esri")&&t.setObject("layers.StreamLayer",d,A);return d});