// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.11/esri/copyright.txt for details.
//>>built
define("esri/PopupManager","./geometry/Extent ./geometry/ScreenPoint ./kernel ./layerUtils ./tasks/query dijit/registry dojo/_base/array dojo/_base/declare dojo/_base/Deferred dojo/_base/lang dojo/has dojo/on dojo/promise/all dojo/Stateful require".split(" "),function(E,x,F,D,G,H,f,r,v,w,I,J,K,L,M){var y;r=r(L,{declaredClass:"esri.PopupManager",enabled:!1,map:null,_mapClickHandle:null,_featureLayersCache:{},constructor:function(a){this._mapClickHandler=w.hitch(this,this._mapClickHandler)},setMap:function(a){if(this.map)if(a!==
this.map)this.unsetMap();else return;this.map=a;this._setupClickHandler()},unsetMap:function(){this.map&&(this.map=null);this._mapClickHandle&&(this._mapClickHandle.remove(),this._mapClickHandle=null)},getMapLayer:function(a){var b;if(a&&(b=a.getLayer()))if(a=b.id,this._featureLayersCache[a]){var c=a.lastIndexOf("_");-1<c&&(a=a.substring(0,c),b=this.map.getLayer(a))}return b},_enabledSetter:function(a){this.enabled=a;this._setupClickHandler()},_setupClickHandler:function(){this._mapClickHandle&&(this._mapClickHandle.remove(),
this._mapClickHandle=null);this.enabled&&this.map&&(this._mapClickHandle=this.map.on("click",this._mapClickHandler))},_mapClickHandler:function(a){var b=this.map.infoWindow,c=a.graphic;b&&this.map.loaded&&(b.clearFeatures&&b.setFeatures?this._showPopup(a):c&&c.getInfoTemplate()&&this._showInfoWindow(c,a.mapPoint))},_showPopup:function(a){var b=this.map,c=b.infoWindow,e=this,g=[],s=[b.graphics].concat(f.map(b.graphicsLayerIds,b.getLayer,b));f.forEach(s,function(a){a&&(a.loaded&&a.infoTemplate&&!a.suspended)&&
g.push(a)});var n=[];f.forEach(b.layerIds,function(a){(a=b.getLayer(a))&&(a.loaded&&!a.suspended)&&("esri.layers.ArcGISImageServiceLayer"===a.declaredClass&&a.infoTemplate?g.push(a):("esri.layers.ArcGISDynamicMapServiceLayer"===a.declaredClass||"esri.layers.ArcGISTiledMapServiceLayer"===a.declaredClass)&&a.infoTemplates&&n.push(a))});this._getSubLayerFeatureLayers(n).then(function(l){g=g.concat(l);l=null;a.graphic&&a.graphic.getInfoTemplate()&&(l=a.graphic);if(g.length||l){var k=e._calculateClickTolerance(g),
s=a.screenPoint,d=b.toMap(new x(s.x-k,s.y+k)),k=b.toMap(new x(s.x+k,s.y-k)),t=new E(d.x,d.y,k.x,k.y,b.spatialReference),m=new G,p=!!l,n=!0,d=f.map(g,function(c){var d;m.timeExtent=c.useMapTime?b.timeExtent:null;if("esri.layers.ArcGISImageServiceLayer"===c.declaredClass)m.geometry=a.mapPoint,n=!1,d=c.queryVisibleRasters(m,{rasterAttributeTableFieldPrefix:"Raster.",returnDomainValues:!0}),d.addCallback(function(){var a=c.getVisibleRasters();p=p||0<a.length;return a});else if(e._featureLayersCache[c.id]||
"function"===typeof c.queryFeatures&&(0===c.currentMode||1===c.currentMode))m.geometry=t,d=c.queryFeatures(m),d.addCallback(function(a){a=a.features;p=p||0<a.length;return a});else{d=new v;var g=f.filter(c.graphics,function(a){return a&&t.intersects(a.geometry)});p=p||0<g.length;d.resolve(g)}return d});l&&(k=new v,k.resolve([l]),d.unshift(k));!f.some(d,function(a){return!a.isFulfilled()})&&!p?(c.hide(),c.clearFeatures()):(c.setFeatures(d),c.show(a.mapPoint,{closestFirst:n}))}})},_getSubLayerFeatureLayers:function(a,
b){var c=b||new v,e=[],g=a.length,s=Math.floor(this.map.extent.getWidth()/this.map.width),n=this.map.getScale(),l=!1,k=this,r=0;a:for(;r<g;r++){var d=a[r],t=d.dynamicLayerInfos||d.layerInfos;if(t){var m=null;if(d._params&&(d._params.layers||d._params.dynamicLayers))m=d.visibleLayers;for(var m=D._getVisibleLayers(t,m),p=D._getLayersForScale(n,t),x=t.length,A=0;A<x;A++){var z=t[A],q=z.id,u=d.infoTemplates[q];if(!z.subLayerIds&&u&&u.infoTemplate&&-1<f.indexOf(m,q)&&-1<f.indexOf(p,q)){if(!y){l=!0;break a}var B=
d.id+"_"+q,h=this._featureLayersCache[B];if(!h||!h.loadError)h||((h=u.layerUrl)||(h=z.source?this._getLayerUrl(d.url,"/dynamicLayer"):this._getLayerUrl(d.url,q)),h=new y(h,{id:B,drawMode:!1,mode:y.MODE_SELECTION,outFields:this._getOutFields(u.infoTemplate),resourceInfo:u.resourceInfo,source:z.source}),this._featureLayersCache[B]=h),h.setDefinitionExpression(d.layerDefinitions&&d.layerDefinitions[q]),h.setGDBVersion(d.gdbVersion),h.setInfoTemplate(u.infoTemplate),h.setMaxAllowableOffset(s),h.setUseMapTime(!!d.useMapTime),
d.layerDrawingOptions&&(d.layerDrawingOptions[q]&&d.layerDrawingOptions[q].renderer)&&h.setRenderer(d.layerDrawingOptions[q].renderer),e.push(h)}}}}if(l){var w=new v;M(["./layers/FeatureLayer"],function(a){y=a;w.resolve()});w.then(function(){k._getSubLayerFeatureLayers(a,c)})}else{var C=[];f.forEach(e,function(a){if(!a.loaded){var c=new v;J.once(a,"load, error",function(){c.resolve()});C.push(c.promise)}});C.length?K(C).then(function(){e=f.filter(e,function(a){return!a.loadError&&a.isVisibleAtScale(n)});
c.resolve(e)}):(e=f.filter(e,function(a){return a.isVisibleAtScale(n)}),c.resolve(e))}return c.promise},_getLayerUrl:function(a,b){var c=a.indexOf("?");return-1===c?a+"/"+b:a.substring(0,c)+"/"+b+a.substring(c)},_getOutFields:function(a){var b;a.info&&"esri.dijit.PopupTemplate"===a.declaredClass?(b=[],f.forEach(a.info.fieldInfos,function(a){var e=a.fieldName&&a.fieldName.toLowerCase();e&&("shape"!==e&&0!==e.indexOf("relationships/"))&&b.push(a.fieldName)})):b=["*"];return b},_calculateClickTolerance:function(a){var b=
6;f.forEach(a,function(a){if(a=a.renderer)"esri.renderer.SimpleRenderer"===a.declaredClass?((a=a.symbol)&&a.xoffset&&(b=Math.max(b,Math.abs(a.xoffset))),a&&a.yoffset&&(b=Math.max(b,Math.abs(a.yoffset)))):("esri.renderer.UniqueValueRenderer"===a.declaredClass||"esri.renderer.ClassBreaksRenderer"===a.declaredClass)&&f.forEach(a.infos,function(a){(a=a.symbol)&&a.xoffset&&(b=Math.max(b,Math.abs(a.xoffset)));a&&a.yoffset&&(b=Math.max(b,Math.abs(a.yoffset)))})});return b},_showInfoWindow:function(a,b){var c=
this.map.infoWindow,e=a.geometry,e=e&&"point"===e.type?e:b,g=a.getContent();c.setTitle(a.getTitle());if(g&&w.isString(g.id)){var f=H.byId(g.id);f&&(f.set&&/_PopupRenderer/.test(f.declaredClass))&&f.set("showTitle",!1)}c.setContent(g);c.show(e)}});I("extend-esri")&&(F.PopupManager=r);return r});