<?php

/**
 * @file
 * Contains eep_core.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/** e
 * Implements hook_help().
 */
function eep_core_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the eep_core module.
    case 'help.page.eep_core':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides the core functionality and utility functions for E-Enterprise Portal in a centralized module.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter().
 */
function eep_core_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id === 'user_form') {
    $current_user = \Drupal::currentUser();
    if ($current_user->id() !== '1') {
      $form['field_cdx_user_id']['#access'] = false;
      $form['account']['#access'] = false;
    }
  }
}