<?php
/**
 * Implements hook_menu().
 **/


/**
 * Implements hook_theme_registry_alter().
 */
function other_items_of_interest_theme_registry_alter(&$theme_registry)
{
    // Defined path to the current module.
    $module_path = drupal_get_path('module', 'other_items_of_interest');
    // Find all .tpl.php files in this module's folder recursively.
    $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
    // Iterate through all found template file objects.
    foreach ($template_file_objects as $key => $template_file_object) {
        // If the template has not already been overridden by a theme.
        if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
            // Alter the theme path and template elements.
            $theme_registry[$key]['theme path'] = $module_path;
            $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
            $theme_registry[$key]['type'] = 'module';
        }
    }
}

function generateAreasOfInterestTable($data) {
    echo "<table id='other-areas-of-interest-table'>" .
        "<thead><tr><th>State</th><th>Online Service</th></tr></thead>" .
    "<tbody>";
    foreach ($data as $state => $state_data) {
        foreach ($state_data as $homepage => $site_data) {
            foreach ($site_data['online_services'] as $service => $service_url) {
                echo "<tr><td>$state</td>" .
                    // "<td><a href='" .  $site_data["url"] . "'>$homepage</a></td>" .
                    "<td><a href='" . $service_url . "'>$service</a></td></tr>";
            }
        }
    }
    echo "</tbody> </table>";

}