/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

//>>built
define("dojo/cldr/nls/lt/gregorian",{"dateFormatItem-Ehm":"E h:mm a","days-standAlone-short":"Sk Pr An Tr Kt Pn \u0160t".split(" "),"months-format-narrow":"SVKBGBLRRSLG".split(""),"field-second-relative+0":"dabar","quarters-standAlone-narrow":["1","2","3","4"],"field-weekday":"Savait\u0117s diena","dateFormatItem-yQQQ":"QQQ y","dateFormatItem-yMEd":"E, M/d/y","field-wed-relative+0":"\u0161is tre\u010diadienis","field-wed-relative+1":"kitas tre\u010diadienis","dateFormatItem-GyMMMEd":"E, MMM d, y G",
"dateFormatItem-MMMEd":"E, MMM d",eraNarrow:["pr. Kr.","m. e.","Po Kr. g.","M\u016bs\u0173 era"],"field-tue-relative+-1":"paskutinis antradienis","days-format-short":"Sk Pr An Tr Kt Pn \u0160t".split(" "),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateFormat-long":"y MMMM, d","field-fri-relative+-1":"paskutinis penktadienis","field-wed-relative+-1":"paskutinis tre\u010diadienis","months-format-wide":"sausio vasario kovo baland\u017eio gegu\u017e\u0117s bir\u017eelio liepos rugpj\u016b\u010dio rugs\u0117jo spalio lapkri\u010dio gruod\u017eio".split(" "),
"dateTimeFormat-medium":"{1}, {0}","dayPeriods-format-wide-pm":"PM","dateFormat-full":"EEEE, MMMM d, y","field-thu-relative+-1":"paskutinis ketvirtadienis","dateFormatItem-Md":"M/d","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dayPeriods-format-wide-noon":"noon","dateFormatItem-yMd":"M/d/y","field-era":"Era","dateFormatItem-yM":"M/y","months-standAlone-wide":"sausio vasario kovo baland\u017eio gegu\u017e\u0117s bir\u017eelio liepos rugpj\u016b\u010dio rugs\u0117jo spalio lapkri\u010dio gruod\u017eio".split(" "),
"timeFormat-short":"HH:mm","quarters-format-wide":["1-as ketvirtis","2-as ketvirtis","3-ias ketvirtis","4-as ketvirtis"],"dateFormatItem-yQQQQ":"QQQQ y","timeFormat-long":"h:mm:ss a z","field-year":"Metai","dateFormatItem-yMMM":"MMM y","dateTimeFormats-appendItem-Era":"{0} {1}","field-hour":"Valanda","months-format-abbr":"Sau Vas Kov Bal Geg Bir Lie Rgp Rgs Spl Lap Grd".split(" "),"field-sat-relative+0":"\u0161is \u0161e\u0161tadienis","field-sat-relative+1":"kitas \u0161e\u0161tadienis","timeFormat-full":"h:mm:ss a zzzz",
"dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"\u0161iandien","field-thu-relative+0":"\u0161is ketvirtadienis","field-day-relative+1":"rytoj","field-thu-relative+1":"kitas ketvirtadienis","dateFormatItem-GyMMMd":"MMM d, y G","dateFormatItem-H":"HH","months-standAlone-abbr":"Sau Vas Kov Bal Geg Bir Lie Rgp Rgs Spl Lap Grd".split(" "),"quarters-format-abbr":["K1","K2","K3","K4"],"quarters-standAlone-wide":["1-as ketvirtis","2-as ketvirtis","3-ias ketvirtis","4-as ketvirtis"],
"dateFormatItem-Gy":"y G","dateFormatItem-M":"L","days-standAlone-wide":"Sekmadienis Pirmadienis Antradienis Tre\u010diadienis Ketvirtadienis Penktadienis \u0160e\u0161tadienis".split(" "),"timeFormat-medium":"HH:mm:ss","field-sun-relative+0":"\u0161is sekmadienis","dateFormatItem-Hm":"HH:mm","field-sun-relative+1":"kitas sekmadienis",eraAbbr:["Pr. Kr. g.","Pr. m. e.","Po Kr. g.","M\u016bs\u0173 era"],"field-minute":"Minut\u0117","field-dayperiod":"AM/PM","dateFormatItem-d":"d","dateFormatItem-ms":"mm:ss",
"field-day-relative+-1":"vakar","dateFormatItem-h":"H a","dateTimeFormat-long":"{1} {0}","dayPeriods-format-narrow-am":"a","dateFormatItem-MMMd":"MMM d","dateFormatItem-MEd":"E, M/d","dateTimeFormat-full":"{1} {0}","field-fri-relative+0":"\u0161is penktadienis","field-fri-relative+1":"kitas penktadienis","field-day":"Diena","days-format-wide":"Sekmadienis Pirmadienis Antradienis Tre\u010diadienis Ketvirtadienis Penktadienis \u0160e\u0161tadienis".split(" "),"field-zone":"Laiko juosta","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})",
"dateFormatItem-y":"y","months-standAlone-narrow":"SVKBGBLRRSLG".split(""),"field-year-relative+-1":"pra\u0117j\u0119 metai","field-month-relative+-1":"pra\u0117j\u0119s m\u0117nuo","dateFormatItem-hm":"HH:mm","dateTimeFormats-appendItem-Year":"{0} {1}","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","days-format-abbr":"Sek Pir Ant Tr\u010d Ket Pen \u0160e\u0161".split(" "),"dateFormatItem-yMMMd":"MMM d, y",eraNames:["pr. Kr.","prie\u0161 m\u016bs\u0173 er\u0105","po Kr.","m\u016bs\u0173 era"],
"days-standAlone-narrow":"SPATKP\u0160".split(""),"dateFormatItem-MMM":"LLL","field-month":"M\u0117nuo","field-tue-relative+0":"\u0161is antradienis","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","field-tue-relative+1":"kitas antradienis","dayPeriods-format-wide-am":"AM","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormatItem-EHm":"E HH:mm","field-mon-relative+0":"\u0161is pirmadienis","field-mon-relative+1":"kitas pirmadienis",
"dateFormat-short":"M/d/yy","dateFormatItem-EHms":"E HH:mm:ss","dateFormatItem-Ehms":"E h:mm:ss a","dayPeriods-format-narrow-noon":"n","field-second":"Sekund\u0117","field-sat-relative+-1":"paskutinis \u0161e\u0161tadienis","dateFormatItem-yMMMEd":"E, MMM d, y","field-sun-relative+-1":"paskutinis sekmadienis","field-month-relative+0":"\u0161is m\u0117nuo","field-month-relative+1":"kitas m\u0117nuo","dateFormatItem-Ed":"d E","dateTimeFormats-appendItem-Timezone":"{0} {1}","field-week":"Savait\u0117",
"dateFormat-medium":"MMM d, y","field-year-relative+0":"\u0161ie metai","field-week-relative+-1":"pra\u0117jusi savait\u0117","field-year-relative+1":"kiti metai","dayPeriods-format-narrow-pm":"p","dateTimeFormat-short":"{1}, {0}","dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-hms":"HH:mm:ss","dateFormatItem-GyMMM":"MMM y G","field-mon-relative+-1":"paskutinis pirmadienis","field-week-relative+0":"\u0161i savait\u0117","field-week-relative+1":"kita savait\u0117"});