<?php


/**
 * Implements hook_theme_registry_alter().
 */
function village_green_theme_registry_alter(&$theme_registry) {

  // Defined path to the current module.
  $module_path = drupal_get_path('module', 'village_green');
  // Find all .tpl.php files in this module's folder recursively.
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);

  // Iterate through all found template file objects.
  foreach ($template_file_objects as $key => $template_file_object) {
    // If the template has not already been overridden by a theme.
    if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
      // Alter the theme path and template elements.
      $theme_registry[$key]['theme path'] = $module_path;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
      $theme_registry[$key]['type'] = 'module';
    }
  }
}



/**
 * Implements hook_menu().
 */
function village_green_menu() {
  $items = array();

  $items['village_green/api/getDataForCurrentMinute'] = array(
    'title' => 'Most Recent Observations',
    'page callback' => 'village_green_get_data_for_current_minute',
    'access callback' => 'user_is_logged_in',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Menu callback: Get data for current minute
 */
function village_green_get_data_for_current_minute() {

  // Create key based on site id requested and current time. Expires at the top of the minute
  // This allows multiple requests in a minute to pull once per minute.

  $cache_key = 'village_green_minute_update|' . $_GET['siteID'];

  $cache = cache_get($cache_key);
  // Check if cache was set and if the cache is stale, since cache_get() does not.
  // @see https://civicactions.com/blog/drupal-gotchya-cache_get-returns-expired-items/
  if ($cache && time() < $cache->expire) {
    // try cache first
    // @see https://www.lullabot.com/articles/a-beginners-guide-to-caching-data-in-drupal-7
    $response = $cache->data;
  }
  else {
    $url = 'http://villagegreen.airnowtech.org/welcome/getDataForCurrentMinuteWelcomePage?' . http_build_query(array('siteID'=>$_GET['siteID']));

    $ch = curl_init();
    curl_setopt($ch, CURLOPT_HEADER, false);
    curl_setopt($ch, CURLINFO_HEADER_OUT, false);
    curl_setopt($ch, CURLOPT_VERBOSE, false);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

    curl_setopt($ch, CURLOPT_URL, $url);

    $response = curl_exec($ch);

    curl_close($ch);
    // Expire on the next minute
    $next_min = ceil(time()/60)*60;
    cache_set($cache_key, $response, 'cache', $next_min);
  }

  print $response;
  exit;
}