banner_text: "<span>Welcome to the new E-Enterprise Portal, with an updated and improved look and performance! As we move everything over, you can find old widgets and services at the <a href=\"https://www2.e-enterprise.gov\" class=\"text-white text-underline\">original E-Enterprise</a> for the time being.</span>"
enabled: '1'
