<?php
/**
 * Implements hook_menu().
 **/
function agency_map_list_menu() {
    $items = array();
    $items['generateAgencyMapsTable'] = array(
        'page callback' => 'generateAgencyMapsTable',
        'access callback' => TRUE,
    );
    return $items;
}

/**
 * Implements hook_theme_registry_alter().
 */
function agency_map_list_theme_registry_alter(&$theme_registry) {
    // Defined path to the current module.
    $module_path = drupal_get_path('module', 'agency_map_list');
    // Find all .tpl.php files in this module's folder recursively.
    $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
    // Iterate through all found template file objects.
    foreach ($template_file_objects as $key => $template_file_object) {
        // If the template has not already been overridden by a theme.
        if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
            // Alter the theme path and template elements.
            $theme_registry[$key]['theme path'] = $module_path;
            $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
            $theme_registry[$key]['type'] = 'module';
        }
    }
}

/**
 * Implements hook_form_alter().
 */
function agency_map_list_form_alter(&$form, &$form_state, $form_id) {
    global $user;
    if ($form_id == 'agency_map_node_form') {

        // Hide title field
        $form['title']['#default_value'] = t('Map Set Value');
        hide($form['title']);

        // Hide backend variables
        hide($form['field_id']);
        hide($form['field_orgid']);

        $form_state['rebuild'] = TRUE;
        //$form_state['redirect'] = '/agency-map-list';
        $form['#validate'][] = 'agency_map_form_validate';

        // Check if user is not admin
        if ($user->uid > 1) {
            $user_data = user_load($user->uid);
            //$state = $user_data->field_admin_state[LANGUAGE_NONE][0]['safe_value'];
            hide($form['additional_settings']);
            hide($form['actions']['preview']);
        }
        //$form['actions'] = array('#type' => 'actions');
/*
			  $form['actions']['submit'] = array(
			    '#type' => 'submit',
			    '#value' => t('Save'),
			    '#submit' => 'new_agency_map_form_redirect',
			  );
*/
        $form['actions']['submit']['#submit'][] = 'new_agency_map_form_redirect';
        $form['actions']['cancel'] = array(
			    '#markup' => l(t('Cancel'), '/workbench'),
			  );
    }
}

function agency_map_form_validate($form, &$form_state){
    $url = $form_state['values']['field_ee_agency_map_url'][LANGUAGE_NONE][0]['value'];
    if (!valid_url($url, TRUE)) {
        $message = "Please provide a valid URL.";
        form_set_error('url', $message);
    } elseif (preg_match('/(https?\:\/\/)(.*)(\.maps.arcgis.com)/', $url, $matches)) {
    // Regex match of AGOL url
        // Get AGOL organization name and store it as "id"
        $form_state['values']['field_id'][LANGUAGE_NONE][0]['value']['#value'] = $matches[2];
        // Get only the domain name and ignore anything after it (e.g. /rest/sharing)
        $url = $matches[1] . $matches[2] . $matches[3];
        form_set_value($form['field_ee_agency_map_url'], array('und' => array(0 => array('value' => $url))), $form_state);
        // Get the AGOL metadata JSON
        $json_file = file_get_contents($url . '/sharing/rest/portals/self?culture=en&f=pjson');
        $result = json_decode($json_file);
        // Make sure it's a valid AGOL site
        if (!empty($result->id)) {
            // Extract the organizational ID and store it as "orgid"
            $form_state['values']['field_orgid'][LANGUAGE_NONE][0]['value']['#value'] = $result->id;
        } else {
            // If URL doesn't match AGOL type, throw error
            $message = "Please provide a valid ArcGIS Online URL.";
            form_set_error('url', $message);
        }
    } else {
        // If URL doesn't match AGOL type, throw error
        $message = "Please provide a valid URL.";
        form_set_error('url', $message);
    }

}

/**
 * Hook_node_presave
 */
function agency_map_list_node_presave($node) {
    global $user;
		// Ensure custom content type is assigned to correct author
    if($node->type === 'agency_map') {
        $node->uid = $user->uid;
    }
}

function new_agency_map_form_redirect($form, &$form_state) {
    drupal_goto('/agency-map-list');
}

function loadAgencyMaps() {
     $agency_maps = array();
     $query = new EntityFieldQuery;
     $query->entityCondition('entity_type', 'node')
         ->entityCondition('bundle', 'agency_map')
         ->propertyCondition('status', 1);
     $results = $query->execute();
     if (isset($results['node'])) {
         $nids = array_keys($results['node']);
         $agency_maps = entity_load('node', $nids);
     }
    return $agency_maps;
}

function generateAgencyMapsTable() {
		/// Add users admin state if applicable
    if (in_array('state_admin', $user->roles)) {
        if (isset($user_data->field_admin_state[LANGUAGE_NONE])) {
            $admin_state = $user_data->field_admin_state[LANGUAGE_NONE][0]['safe_value'];
            $states[] = $admin_state;
        }
    }

    $agency_maps = loadAgencyMaps();
    echo "<table id='agencymaps-table'>" .
        "<thead><tr><th>State</th><th>Map Site</th><th>Agency</th></tr></thead>" .
        "<tbody>";
    foreach ($agency_maps as $nid => $nid_data) {
        $agencymap = $nid_data->title;
        $description = $nid_data->field_ee_agency_map_description[LANGUAGE_NONE][0]['safe_value'];
        $url = $nid_data->field_ee_agency_map_url[LANGUAGE_NONE][0]['safe_value'];
        $email = $nid_data->field_ee_agency_map_email[LANGUAGE_NONE][0]['safe_value'];
        $agency = $nid_data->field_ee_agency_map_agency[LANGUAGE_NONE][0]['value'];
        $state = $nid_data->field_ee_agency_map_us_state[LANGUAGE_NONE][0]['value'];
        echo "<tr><td>$state</td>" .
            "<td><div class='agencymap-url-hyperlink'><a href='" . $url . "' target='_blank'>$agencymap</a></div>" .
            "<br /><div class='agencymap-url-text' title='" . $url . "'>$description</div>" .
            "<br /><div class='agencymap-email' href='mailto:". $email. "'>$email</div></td>" .
            "<td>$agency</td></tr>";

    }
    echo "</tbody> </table>";
}