<?php

/**
 *
 */
function progress_tracker_menu() {
  $items = array();

  $items['progress_tracker/load_data'] = array(
    'page callback' => 'load_progress_tracker_datatable_json',
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Implements hook_block_info().
 */
function progress_tracker_block_info() {
  $blocks = array();
  $blocks['progress_tracker'] = array(
    'info' => t('Progress Tracker Block'),
  );
  return $blocks;
}


/**
 * Implements hook_theme().
 * @see http://www.devdungeon.com/content/using-tpl-template-files-custom-drupal-7-modules
 */
function progress_tracker_theme() {
  return array(
    // Name to be called with theme(). theme('progress_tracker')
    'progress_tracker' => array(
      // Default variables
      'variables' => array(),
      // Which .tpl.php file to use my-cdx.tpl.php
      'template' => 'progress-tracker',
      'path' => drupal_get_path('module', 'progress_tracker') . '/templates'
    ),
    'progress_tracker_modal' => array(
      // Default variables
      'variables' => array(),
      // Which .tpl.php file to use my-cdx.tpl.php
      'template' => 'my-cdx-modal',
      'path' => drupal_get_path('module', 'progress_tracker') . '/templates'
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function progress_tracker_block_view($delta = '') {
  $block = array();

  if ($delta == 'progress_tracker') {
    drupal_add_js(drupal_get_path('module', 'datatables') . '/dataTables/media/js/jquery.dataTables.js', [
      'scope' => 'footer',
      'preprocess' => TRUE,
      'group' => JS_LIBRARY,
      'type' => 'file',
      'cache' => TRUE,
      'requires_jquery' => TRUE
    ]);
    drupal_add_js(drupal_get_path('module', 'progress_tracker') . '/js/progress_tracker.js', [
      'scope' => 'footer',
      'preprocess' => TRUE,
      'group' => JS_LIBRARY,
      'type' => 'file',
      'cache' => TRUE,
      'requires_jquery' => TRUE
    ]);
    drupal_add_css(drupal_get_path('module', 'progress_tracker') . '/css/progress_tracker.css', [
      'preprocess' => TRUE,
      'group' => CSS_THEME
    ]);


    if (user_access('access content')) { //good idea to check user perms here
      $block['subject'] = t('Progress Tracker');
      $block['content'] = theme('progress_tracker');
      return $block;
    }
  }

  return $block;
}

/**
 * Load the json and pass it to the progress tracker datatable
 * this is a menu item function
 */
function load_progress_tracker_datatable_json() {
  if (!module_exists('eactivity_dataflow')) {
    drupal_json_output('EACTIVITY DATAFLOW module is not enabled.');
  }

  // Json formatted for Datatables
  $eactivity_dt_json = [];
  $progress_tracker_data = load_eactivity_data('progress_tracker');

  foreach($progress_tracker_data as $id=>$eactivity_item) {
    $eactivity_dt_row = [
      "", // Empty to allow for datatables to have index column
      $eactivity_item['title'],
      $eactivity_item['domain'],
//      "<a class='favorites-ignore'>"$eactivity_item['status'],
      $eactivity_item['date'],
      $eactivity_item['actions']
      ];

    $eactivity_dt_json[] = $eactivity_dt_row;
  }

  drupal_json_output(array("data" => $eactivity_dt_json));
}

