/**
 * This allows the code to take advantage of tooling like linters, and putting
 * all constants in a single file allows your collaborators to get an
 * at-a-glance view of what mutations are possible in the entire application.
 *
 *  @SEE https://vuex.vuejs.org/guide/mutations.html
 */

export default {
  NAMESPACE: '',
  DECODE_JWT_TOKEN: 'DECODE_JWT_TOKEN',
  SET_APP: 'SET_APP',
  SET_DEEP_PROPERTY: 'SET_DEEP_PROPERTY',
  SET_JWT_TOKEN: 'SET_JWT_TOKEN',
  SET_USER_LOCATION: 'SET_USER_LOCATION',
  TOGGLE_HAS_LOCATION_SEARCH_BAR: 'TOGGLE_HAS_LOCATION_SEARCH_BAR',
  USER_LOG_IN: 'USER_LOG_IN',
  USER_LOG_OUT: 'USER_LOG_OUT',
  IS_USER_LOGGED_IN: 'IS_USER_LOGGED_IN',
  SET_MARGIN_TOP_NAV: 'SET_MARGIN_TOP_NAV',
  USER_TANDC_COOKIE_DISMISS: 'USER_TANDC_COOKIE_DISMISS',
  USER_POLICY_COOKIE_DISMISS: 'USER_POLICY_COOKIE_DISMISS',
  SET_USER_OBJECT: 'SET_USER_OBJECT',
  SET_USER_OBJECT_FAV_LINKS: 'SET_USER_OBJECT_FAV_LINKS',
  SET_USER_OBJECT_ORGANISATION: 'SET_USER_OBJECT_ORGANISATION',
  SET_USER_OBJECT_ROLE: 'SET_USER_OBJECT_ROLE',
  SET_BASIC_PAGES: 'SET_BASIC_PAGES',
  SET_BRIDGE_URN: 'SET_BRIDGE_URN',
  SET_UID: 'SET_UID',
  SET_LOGIN_VIEW_ACCOUNTS: 'SET_LOGIN_VIEW_ACCOUNTS',
  SET_LOGGED_IN_TOKEN: 'SET_LOGGED_IN_TOKEN',
  SET_LOGGED_IN_TIME: 'SET_LOGGED_IN_TIME',
  TIME_LEFT_UNTIL_LOG_OUT: 'TIME_LEFT_UNTIL_LOG_OUT',
  SET_COOKIE: 'SET_COOOKIE',
  SET_OPTIONS_AFTER_INPUT: 'SET_OPTIONS_AFTER_INPUT',
  SET_IS_AFTER_INPUT_DROPDOWN_DISPLAYED: 'SET_IS_AFTER_INPUT_DROPDOWN_DISPLAYED',
  SET_INPUT_BOX_TEXT_AFTER_SUBMIT: 'SET_INPUT_BOX_TEXT_AFTER_SUBMIT',
  SET_DEEP_LINK: 'SET_DEEP_LINK',
};
