/**
 * This allows the code to take advantage of tooling like linters, and putting
 * all constants in a single file allows your collaborators to get an
 * at-a-glance view of what mutations are possible in the entire application.
 *
 *  @SEE https://vuex.vuejs.org/guide/mutations.html
 */

export default {
  NAMESPACE: 'ModuleTemplate/',
  SET_PERMIT_TYPE: 'SET_PERMIT_TYPE',
  SET_FACILITY_NAME: 'SET_FACILITY_NAME',
  SET_NPDESID: 'SET_NPDESID',
  SET_FACILITY_CITY: 'SET_FACILITY_CITY',
  SET_FACILITY_STATE: 'SET_FACILITY_STATE',
  SET_FACILITY_ZIP: 'SET_FACILITY_ZIP',
  SET_STATUS: 'SET_STATUS',
  SET_FORM_TYPE: 'SET_FORM_TYPE',
  SET_OPERATOR_NAME: 'SET_OPERATOR_NAME',
  SET_FEDERAL_INDICATOR: 'SET_FEDERAL_INDICATOR',
  SET_DATE_SELECTION: 'SET_DATE_SELECTION',
  SET_START_DATE: 'SET_START_DATE',
  SET_END_DATE: 'SET_END_DATE',
  SET_TRIBAL_INDICATOR: 'SET_TRIBAL_INDICATOR',
  SET_TRIBE_SELECTION: 'SET_TRIBE_SELECTION',
  SET_FACILITY_COUNTY: 'SET_FACILITY_COUNTY',
  SET_MASTER_PERMIT_NUMBER: 'SET_MASTER_PERMIT_NUMBER',
  SET_TRIBAL_NAME: 'SET_TRIBAL_NAME',
  SET_ISSUER: 'SET_ISSUER',
  SET_SUBMISSION_TYPE: 'SET_SUBMISSION_TYPE',
  SET_APPLICATION_TYPE: 'SET_APPLICATION_TYPE',
  SET_FORM_STATUS: 'SET_FORM_STATUS',
  SET_SECTOR: 'SET_SECTOR',
  SET_SUBSECTOR: 'SET_SUBSECTOR',
  SET_SIC_CODE: 'SET_SIC_CODE',
  SET_ADDRESS: 'SET_ADDRESS',
};
