/**
 * This allows the code to take advantage of tooling like linters, and putting
 * all constants in a single file allows your collaborators to get an
 * at-a-glance view of what mutations are possible in the entire application.
 *
 *  @SEE https://vuex.vuejs.org/guide/mutations.html
 */

export default {
  NAMESPACE: 'ModuleTemplate/',
  SET_PERMIT_TYPE: 'SET_PERMIT_TYPE',
  SET_FACILITY_NAME: 'SET_FACILITY_NAME',
  SET_NPDESID: 'SET_NPDESID',
  SET_CITY_NAME: 'SET_CITY_NAME',
  SET_STATE_TERRITORY: 'SET_STATE_TERRITORY',
  SET_ZIP: 'SET_ZIP',
  SET_STATUS: 'SET_STATUS',
  SET_FORM_TYPE: 'SET_FORM_TYPE',
  SET_FACILITY_OPERATOR: 'SET_FACILITY_OPERATOR',
  SET_FEDERAL_FACILITY: 'SET_FEDERAL_FACILITY',
  SET_DATE_SELECTION: 'SET_DATE_SELECTION',
  SET_START_DATE: 'SET_START_DATE',
  SET_END_DATE: 'SET_END_DATE',
  SET_TRIBAL_LANDS_CONSTRUCTION: 'SET_TRIBAL_LANDS_CONSTRUCTION',
  SET_TRIBE_SELECTION: 'SET_TRIBE_SELECTION',
  SET_COUNTY_SELECTION: 'SET_COUNTY_SELECTION',
  SET_MASTER_GENERAL_PERMIT: 'SET_MASTER_GENERAL_PERMIT',
  SET_INDIAN_COUNTRY_SELECTION: 'SET_INDIAN_COUNTRY_SELECTION',
  SET_ISSUER: 'SET_ISSUER',
  SET_SUBMISSION_TYPE: 'SET_SUBMISSION_TYPE',
  SET_COVERAGE_TYPE: 'SET_COVERAGE_TYPE',
  SET_COVERAGE_STATUS: 'SET_COVERAGE_STATUS',
  SET_SECTOR: 'SET_SECTOR',
  SET_SUBSECTOR: 'SET_SUBSECTOR',
  SET_PRIMARY_SIC_CODE: 'SET_PRIMARY_SIC_CODE',
  SET_ADDRESS: 'SET_ADDRESS',
};
