<?php
/**
 * Implements hook_menu().
 **/


/**
 * Implements hook_page_build().
 * @see https://api.drupal.org/comment/56528#comment-56528
 * Add client-side business logic, tracking for prompt and logout
 */
function google_analytics_page_build(&$page) {
  drupal_add_js(drupal_get_path('module', 'google_analytics') . '/js/script.js');


  $iframe = array(
    '#theme' => 'html_tag',
    '#tag' => 'iframe',
    '#attributes' => array(
      'src' => '//www.googletagmanager.com/ns.html?id=GTM-L8ZB',
      'height' => "0",
      'width' => '0',
      'style' => 'display:none;visibility:hidden',
    )
  );
  $noscript = array(
    '#theme' => 'html_tag',
    '#tag' => 'noscript',
    '#value' => drupal_render($iframe),
  );
  drupal_add_html_head($noscript, 'noscript');
}
